



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-acc:ESPDRequest | A document issued by a Buyer defining how the Exclusion Grounds and the Selection Criteria should be addressed in an European Single Procurement Document for a specific procurement.
      
    
      
| epo-acc:InformationRequest | Specific question about at least one Procurement Element.
      
    
      
| epo-acc:InformationResponse | Answer to an Information Request.
      
    
      
| epo-acc:InvitationToTender | A formal request to submit a Tender.
      
    
      
| epo-acc:ProcurementDocumentsProvision | The provision by the Buyer to the Economic Operator of the Procurement Documents.
      
    
      
| epo-acc:ProcurementDocumentsRequest | The request by the Economic Operator to the Buyer to receive the latest version of all the Procurement Documents.
      
    
      
| epo-acc:ProcurementQuestion | Document requesting information about at least one Procurement Element.
      
    
      
| epo-acc:ProcurementQuestionReply | Answer to a Procurement Question.
      
    
      
| epo-acc:UnsubscribeFromProcedure | A formal request to stop receiving information on a Procedure.
      
    
      
| epo-acc:UnsubscribeFromProcedureResponse | A formal reply cancelling the subscription to a Procedure.
      
    
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
| epo:concernsProcedure| 
  Relates to Procedure.|epo-acc:ESPDRequest → epo:Procedure [1] +
epo-acc:InformationRequest → epo:Procedure [0..&#42;] +
epo-acc:InvitationToTender → epo:Procedure [1] +
epo-acc:ProcurementDocumentsProvision → epo:Procedure [1] +
epo-acc:ProcurementDocumentsRequest → epo:Procedure [1] +
epo-acc:UnsubscribeFromProcedure → epo:Procedure [1]

  

  
  
| epo-acc:refersToNotice| 
  Reference to a Notice.|epo-acc:ESPDRequest → epo:Notice [0..&#42;]

  

  
  
| epo:specifiesProcurementCriterion| 
  Relation indicating the Procurement Criterion to be used.|epo-acc:ESPDRequest → epo:ProcurementCriterion [1..&#42;]

  

  

  

  

  

  

  
  
| epo:concernsLot| 
  Relates to Lot.|epo-acc:InformationRequest → epo:Lot [0..&#42;]

  

  
  
| epo:concernsLotGroup| 
  Relates to Lot Group.|epo-acc:InformationRequest → epo:LotGroup [0..&#42;]

  

  
  
| epo-sub:answersQuestion| 
  Relation indicating that the Response replies to a question.|epo-acc:InformationResponse → epo-acc:InformationRequest [1]

  

  
  
| epo-acc:containsProvidedProcurementDocument| 
  Includes the supplied Procurement Document.|epo-acc:InvitationToTender → epo:ProcurementDocument [0..&#42;] +
epo-acc:ProcurementDocumentsProvision → epo:ProcurementDocument [0..&#42;]

  

  
  
| epo:specifiesEconomicOperator| 
  Relation indicating that the instance of the concept involves the Economic Operator.|epo-acc:InvitationToTender → epo:OfferingParty [1] +
epo-acc:ProcurementDocumentsProvision → epo:OfferingParty [1] +
epo-acc:ProcurementDocumentsRequest → epo:OfferingParty [1] +
epo-acc:ProcurementQuestion → epo:OfferingParty [0..1] +
epo-acc:UnsubscribeFromProcedure → epo:OfferingParty [1]

  

  

  

  

  

  

  

  

  
  
| epo:hasResourceType| 
  Relation indicating the Resource Type.|eli:LegalResource → at-voc:resource-type [1..&#42;]

  

  
  
| epo:hasSubdivision| 
  Relation indicating the Subdivision.|eli:LegalResourceSubdivision → at-voc:subdivision [0..1]

  

  
  
| epo:refersToProcurementDocumentsRequest| 
  |epo-acc:ProcurementDocumentsProvision → epo-acc:ProcurementDocumentsRequest [0..1]

  

  
  
| epo-acc:containsInformationRequest| 
  Includes Information Request.|epo-acc:ProcurementQuestion → epo-acc:InformationRequest [1..&#42;]

  

  
  
| epo-acc:containsInformationResponse| 
  Includes Information Response.|epo-acc:ProcurementQuestionReply → epo-acc:InformationResponse [1..&#42;]

  

  
  
| epo-acc:refersToUnsubscribeFromProcedure| 
  |epo-acc:UnsubscribeFromProcedureResponse → epo-acc:UnsubscribeFromProcedure [1]

  

  

  

  

  

  
  
| epo-sub:relatesToESPDRequest| 
  Is about an European Single Procurement Document (ESPD) Request.|epo-sub:ESPD → epo-acc:ESPDRequest [0..1]

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].