



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-acc:ESPDRequest | A document issued by a Buyer defining how the Exclusion Grounds and the Selection Criteria should be addressed in an European Single Procurement Document for a specific procurement.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
| epo:concernsProcedure| 
  Relates to Procedure.|epo-acc:ESPDRequest → epo:Procedure [1]

  

  
  
| epo-acc:refersToNotice| 
  Reference to a Notice.|epo-acc:ESPDRequest → epo:Notice [0..&#42;]

  

  
  
| epo:specifiesProcurementCriterion| 
  Relation indicating the Procurement Criterion to be used.|epo-acc:ESPDRequest → epo:ProcurementCriterion [1..&#42;]

  

  

  

  

  

  

  

  

  

  

  

  

  
  
| epo:hasResourceType| 
  Relation indicating the Resource Type.|eli:LegalResource → at-voc:resource-type [1..&#42;]

  

  
  
| epo:hasSubdivision| 
  Relation indicating the Subdivision.|eli:LegalResourceSubdivision → at-voc:subdivision [0..1]

  

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].