



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-awa:AwardDecisionNotification | A formal communication sent by the Buyer to inform Tenderers of the Award Decision.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
| epo-awa:AwardDecisionNotification
| epo-awa:hasStandstillPeriodEndDate| 
  The end date for the mandatory minimum time frame between the communication of a contract award decision and the formal conclusion of the contract, during which unsuccessful Tenderers have the opportunity to challenge the award before it becomes legally binding.|xsd:date [0..1]
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
| epo:concernsAwardOutcome| 
  Relates to Award Outcome.|epo-awa:AwardDecisionNotification → epo:AwardOutcome [1..&#42;]

  

  
  
| epo:concernsProcedure| 
  Relates to Procedure.|epo-awa:AwardDecisionNotification → epo:Procedure [1]

  

  
  
  

  
  
| epo:specifiesTenderer| 
  Relation indicating that the instance of the concept involves the Tenderer.|epo-awa:AwardDecisionNotification → epo:Tenderer [1]

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].