



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-cat:AbstractItem | Gathering class for the Items, Item Requests and Deliverables. Additional information: The subclasses have in common that they are related to a procurement need.
      
    
      
| epo-cat:Batch | A production lot in which the Item instances were produced.
      
    
      
| epo-cat:Brand | Name given by an organisation to its product or service, or range of products or services. Additional information: Brand name allows economic operators to distinctively describe an item in their eCatalogue. This may be different from the "item name".
      
    
      
| epo-cat:Catalogue | A phase-agnostic Document describing a set of Items offered for purchase that can be processed in an electronic way.
      
    
      
| epo-cat:CatalogueLine | Aggregated information about the Terms and specifications for procuring an Item. Details about an Item, like Prices, packaging, discounts, special promotions, etc. TC 440: Detailed information of an Item, Price and its composition in a Catalogue. Composition: e.g. information referring to its description, how to order it, what it is made of, properties, delivery conditions, etc.
      
    
      
| epo-cat:CatalogueResponse | A formal reply from the Catalogue Receiver to the Catalogue Provider stating the Catalogue Receiver's ability to apply the catalogue for placing orders. Additional Information: The Catalogue Response is used to inform on the acceptance or rejection of a Catalogue.
      
    
      
| epo-cat:CatalogueResponseInformation | Information about a Catalogue Response.
      
    
      
| epo-cat:CatalogueResponseLine | Details concerning the Catalogue Receiver’s ability to apply a given Catalogue Line for placing orders. Additional information: The Catalogue Response Line is used to inform on the acceptance or rejection of a Catalogue Line.
      
    
      
| epo-cat:ChargeInformation | Information about fee or duty imposed. Additional Information: Charge category indicates the nature of the duty/fee, for example CAR, etc. Charge category modifier may be used in case different levels, exemptions or other modifications apply. The charge can be fixed or relative to the price.
      
    
      
| epo-cat:DimensionInformation | Information about the physical or measurable attributes of the instance of the concept described.
      
    
      
| epo-cat:EnvironmentalEmissionInformation | Information about the emissions related to a product, work or service that are released into the environment.
      
    
      
| epo-cat:InformationHub | Grouping of data that may be associated to various concepts. Additional Information: For example, AllowanceChargeInformation may be associated to the Order or the Catalogue (either at the Line level or at the Document level), amongst others.
      
    
      
| epo-cat:Item | A product, work, service or any combination of them. Additional Information: An Item can be an atomic Thing or a composition of things that together are seen as a unit, e.g. a tetrabrik of milk or an indivisible package of six tetrabriks. No distinction is provided between services, goods and works to leave room for innovation. An Item is used to fulfill a need which is described in an Item Request.
      
    
      
| epo-cat:ItemAccessoryRelation | Combination of two Items where the former enhances the latter.
      
    
      
| epo-cat:ItemComplementaryRelation | Combination of two Items which mutually enhance one another.
      
    
      
| epo-cat:ItemComposition | Inclusion of an Item into in the described Item. Additional Information: The Item is provided with its components, however, the component Items may also be provided separately. For example, a bicycle has wheels as components, but they may be provided as spare parts as well. This relation is useful to describe different package levels of an item or hierarchies of Items.
      
    
      
| epo-cat:ItemModel | A specific design or version of a product or service. Additional information: This class is meant as a reusable reference to the model name rather than as a set of specifications of an Item of this particular model.
      
    
      
| epo-cat:ItemProperty | Construct meant to represent the association between an attribute defined in an external classification scheme and the value ascribed to it.
      
    
      
| epo-cat:ItemRelation | Connection between two Items.
      
    
      
| epo-cat:ItemReplacement | Supplantment, displacement or suspension of an Item by the described Item.
      
    
      
| epo-cat:ItemRequirement | Necessity of an Item by the described item. Additional Information: The described item is provided without other items that are required for proper functionality. For example, a printer cannot be used without ink cartridge; or a Server cannot be used without its installation.
      
    
      
| epo-cat:Line | Component of a document providing specific information.
      
    
      
| epo-cat:Manufacturer | The Producer of goods or provider of services. Additional Information: Also, known as Supplier and Manufacturer. We do not care who provides these service or products we care with whom Business is done. PEPPOL - Invoice: The Supplier is the Legal Person or Organisation who provides a product and/or service. PEPPOL - Order: The supplier is the legal person or organisation who provides a product or service. Examples of supplier roles: seller, despatch party, creditor, economic operator.
      
    
      
| epo-cat:PostAwardCatalogue | A Document describing a set of Items offered for purchase that can be processed in an electronic way, after a Contract is signed.
      
    
      
| epo-cat:PostAwardDocument | Document created after the award of a Contract during a Procurement Procedure.
      
    
      
| epo-cat:Price | Amount of money required or given in exchange for Items. Additional information: The Price excludes any charges (such as taxes, duties and fees) and discounts.
      
    
      
| epo-cat:ProductSpecification | Document providing information about an Item.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-cat:AbstractItem
| epo-cat:hasKeyword| 
  List of words (e.g, synonyms) to make the item searchable.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-cat:AbstractItem
| epo-cat:isInStock| 
  Indicator whether an item is in the supplier's stock. If not in stock the supplier has to order the item.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
| epo-cat:Batch
| epo-cat:hasBestBeforeDate| 
  The day until which the quality of the item will remain optimal.|xsd:date [0..1]
  
  
  
| epo-cat:Batch
| epo-cat:hasExpiryDate| 
  The last day until which the item can be used.|xsd:date [0..1]
  
  
  
| epo-cat:Batch
| epo-cat:hasManufactureDate| 
  The day of production.|xsd:dateTime [0..1]
  
  
  
  
  
  
  
  
  
| epo-cat:Catalogue
| epo-cat:hasSpecificPaymentArrangement| 
  Information about payment conditions applied to all items in the catalogue. Additional information: This property may need to be used together with the payment arrangements provided in the ContractTerms, where such terms exists.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-cat:CatalogueLine
| epo-cat:hasOrderableQuantityIncrement| 
  Orderable quantity increment: The increment of Orderable units that can be ordered.|xsd:integer [0..1]
  
  
  
  
  
| epo-cat:CatalogueLine
| epo-cat:hasOrderableUnitFactorRate| 
  The factor by which the Item net price of an unit of an item can be converted to the orderable unit.|xsd:decimal [0..1]
  
  
  
  
  
  
  
| epo-cat:CatalogueLine
| epo-cat:hasTransactionConditions| 
  Textual description of the specific transaction conditions (purchasing, sales, payment, delivery) for an item.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-cat:CatalogueLine
| epo-cat:hasWarrantyInformation| 
  Warranty information that applies to the catalogue line item.|rdf:PlainLiteral [0..1]
  
  
  
| epo-cat:CatalogueLine
| epo-cat:isContractedItem| 
  Indicator if the item is offered in accordance to an existing contract.|xsd:boolean [0..1]
  
  
  
| epo-cat:CatalogueLine
| epo-cat:isOrderable| 
  Indicator, if the item is orderable or not, e.g. because it is temporarily out of stock.|xsd:boolean [0..1]
  
  
  
  
  
| epo-cat:CatalogueResponse + 
epo-cat:CatalogueResponseLine
| epo-ord:hasResponseDescription| 
  Explanation of the response.|rdf:PlainLiteral [0..1] +
  rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-cat:DimensionInformation
| epo-cat:hasDimensionDescription| 
  Textual description of the item's dimensions.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
| epo-cat:EnvironmentalEmissionInformation
| epo:hasCalculationMethod| 
  Formula for obtaining values. Additional Information: The possible values are monetary values, ranking scores, criterion weighting.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
| epo-cat:ItemProperty
| epo-cat:hasAttributeType| 
  The property defined in a classification scheme. Additional Information: For example, the following two properties are defined in the ECLASS classification of goods and services: (0173-1#02-AAA026#007) drilling diameter: drilling diameter, (0173-1#02-AAA030#007) flange diameter: flange diameter .|rdf:PlainLiteral [0..1]
  
  
  
| epo-cat:ItemProperty
| epo-cat:hasClassificationCode| 
  The categorization of the instance of the concept expressed as a code.|rdf:PlainLiteral [0..1]
  
  
  
| epo-cat:ItemProperty
| epo-cat:hasClassificationScheme| 
  The classification scheme where a property is defined. Additional Information: For example, the following two properties are defined in the ECLASS classification of goods and services: (0173-1#02-AAA026#007) drilling diameter: drilling diameter, (0173-1#02-AAA030#007) flange diameter: flange diameter .|rdf:PlainLiteral [0..1]
  
  
  
| epo-cat:ItemProperty
| epo-cat:hasImportanceCode| 
  The significance of the instance of the concept expressed as a code.|xsd:integer [0..1]
  
  
  
| epo-cat:ItemProperty
| epo-cat:hasLiteralValue| 
  Simple value of the property, which is defined in a classification scheme. Additional Information: For example, the (0173-1#02-AAV139#001) coating 1 of an optical material has value of "silver". This simple literal value is for the cases when the property value does not have units, in which case the qualifiedValue shall be used.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
| epo-cat:ItemRelation
| epo-cat:hasFactor| 
  The number or the fraction of a related item.|xsd:decimal [0..1]
  
  
  
  
  
| epo-cat:Line
| epo:hasAdditionalInformation| 
  Supplementary data about the instance of the concept.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  

  
  
| epo-cat:hasAccessoryItem| 
  An additional item that can enhance the original item.|epo-cat:AbstractItem → epo-cat:AbstractItem [0..&#42;]

  

  
  
| epo-cat:hasBrand| 
  Relation indicating that the instance of the concept has a Brand.|epo-cat:AbstractItem → epo-cat:Brand [0..1]

  

  
  
| epo:hasBuyerItemID| 
  The general identifier assigned to the concept as defined by the Buyer.​|epo-cat:AbstractItem → adms:Identifier [0..1]

  

  
  
| epo:hasCertification| 
  Relation to the proof of conformance.|epo-cat:AbstractItem → epo:Certificate [0..&#42;]

  

  
  
| epo-cat:hasComplementaryItem| 
  An item that if used with another item provides mutual enhancements to both of them. Additional information: For example, gin and tonic; or smart-phone and smart-watch.|epo-cat:AbstractItem → epo-cat:AbstractItem [0..&#42;]

  

  
  
| epo-cat:hasCountryOfOrigin| 
  The source country of the product or service. Additional Information: The country of origin can be provided by the buyer as a requirement or by the tenderer information of the item to be provided.|epo-cat:AbstractItem → at-voc:country [0..1]

  

  
  
| epo-cat:hasDeliveryClassification| 
  Relation indicating the Delivery Item Type.|epo-cat:AbstractItem → at-voc-new:delivery-item-type [0..1]

  

  
  
| epo-cat:hasHazardousClassID| 
  Specification of the hazardous nature of an item according to a classification schema. Provides detail of the classification and nature of a hazardous item.|epo-cat:AbstractItem → adms:Identifier [0..&#42;]

  

  
  
| epo-cat:hasHazardousItemUNDGCode| 
  Specification of the hazardous nature of an item according to the UNDG classification schema. Provides detail of the classification and nature of a hazardous item.|epo-cat:AbstractItem → at-voc-new:dangerous-goods-list [0..&#42;]

  

  
  
| epo-cat:hasItemClassification| 
  A classification of this item according to a specific system for classifying products or services. Additional information: Examples of classification schemes are: CPV, UNSPC, eCl@ss, GPC, ...|epo-cat:AbstractItem → at-voc-new:item-classification [0..&#42;]

  

  
  
| epo-inv:hasItemClassificationIdentifier| 
  The Identifier of the Item categorisation.|epo-cat:AbstractItem → adms:Identifier [0..&#42;]

  

  
  
| epo:hasItemStandardID| 
  The general identifier assigned to the concept based on a standard scheme.​ Additional information: For example the GTIN scheme (Global Trade Item Number).|epo-cat:AbstractItem → adms:Identifier [0..&#42;]

  

  
  
  

  
  
| epo-cat:hasManufacturer| 
  The product maker or service provider.|epo-cat:AbstractItem → epo-cat:Manufacturer [0..1]

  

  
  
| epo:hasManufacturerItemID| 
  The general identifier assigned to the concept as defined by the Manufacturer. ​|epo-cat:AbstractItem → adms:Identifier [0..1]

  

  
  
| epo-cat:hasModel| 
  Relation indicating that the instance of the concept has an Item Model.|epo-cat:AbstractItem → epo-cat:ItemModel [0..1]

  

  
  
| epo-cat:hasNetQuantity| 
  The net quantity of the item that is contained in each consumable unit, excluding any packaging materials.|epo-cat:AbstractItem → epo:Quantity [0..1]

  

  

  
  
| epo-cat:hasQualifiedItemRelation| 
  Relation indicating that the instance of the concept has an Item Relation.|epo-cat:AbstractItem → epo-cat:ItemRelation [0..&#42;]

  

  
  
| epo:hasSellerItemID| 
  The general identifier assigned to the concept as defined by the Seller.​|epo-cat:AbstractItem → adms:Identifier [0..1]

  

  
  
| epo:hasSerialID| 
  The identifier assigned to the specific instance of the produced concept.|epo-cat:AbstractItem → adms:Identifier [0..1]

  

  
  
| epo-cat:hasSpecification| 
  Relation indicating that the instance of the concept has a Product Specification.|epo-cat:AbstractItem → epo-cat:ProductSpecification [0..&#42;]

  

  
  
| epo-ord:hasTaxInformation| 
  Relation indicating the Tax Information.|epo-cat:AbstractItem → epo-ord:TaxInformation [0..&#42;]

  

  
  
  

  

  

  

  

  
  
| epo:hasBatchID| 
  The identifier assigned to a specific batch of the produced Item.|epo-cat:Batch → adms:Identifier [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo-cat:isProductionOf| 
  Relation indicating the Item that is manufactured.|epo-cat:Batch → epo-cat:AbstractItem [1]

  

  
  
| epo-cat:comprisesCatalogueLine| 
  Incorporates Catalogue Line.|epo-cat:Catalogue → epo-cat:CatalogueLine [1..&#42;]

  

  
  
| epo-cat:hasActivityCode| 
  Relation indicating the Activity Code.|epo-cat:Catalogue → at-voc-new:activity-code [0..1] +
epo-cat:CatalogueLine → at-voc-new:activity-code [0..1]

  

  
  
  

  
  
| epo:hasValidityPeriod| 
  The relation indicating until when a given instance of a concept is applicable.|epo-cat:Catalogue → time:Interval [0..1]

  

  
  
| epo:specifiesBuyer| 
  Relation indicating that the instance of the concept involves the Buyer.|epo-cat:Catalogue → epo:Buyer [0..&#42;]

  

  
  
| epo:specifiesCatalogueProvider| 
  Relation indicating that the instance of the concept involves the Catalogue Provider.|epo-cat:Catalogue → epo:CatalogueProvider [0..1] +
epo-cat:CatalogueResponse → epo:CatalogueProvider [1]

  

  
  
| epo:specifiesCatalogueReceiver| 
  Relation indicating that the instance of the concept involves the Catalogue Receiver.|epo-cat:Catalogue → epo:CatalogueReceiver [0..1] +
epo-cat:CatalogueResponse → epo:CatalogueReceiver [1]

  

  
  
| epo:specifiesSeller| 
  Relation indicating that the instance of the concept involves the Seller.|epo-cat:Catalogue → epo-ord:Seller [0..&#42;]

  

  
  
| epo-cat:foreseesPackage| 
  Relation indicating that an instance of the concept plans to have a Package.|epo-cat:CatalogueLine → epo-ful:Package [0..1]

  

  
  
| epo-cat:hasCatalogueLineValidity| 
  The relation indicating until when a Catalogue Line instance is applicable.|epo-cat:CatalogueLine → time:Interval [0..1]

  

  
  
| epo-cat:hasChargeInformation| 
  Relation indicating that the instance of the concept has Charge Information.|epo-cat:CatalogueLine → epo-cat:ChargeInformation [0..&#42;]

  

  
  
| epo-cat:hasMaximumOrderQuantity| 
  The maximum number of orderable units that can be ordered according to details provided in the catalogue line, such as price.|epo-cat:CatalogueLine → epo:Quantity [0..1]

  

  
  
| epo-cat:hasMinimumQuantityGuaranteedForDelivery| 
  The minimum quantity of an item that is guaranteed by the seller to be delivered.|epo-cat:CatalogueLine → epo:Quantity [0..1]

  

  
  
  

  
  
| epo-cat:hasOrderableUnit| 
  The unit in which the item described in this catalogue line can be ordered.|epo-cat:CatalogueLine → at-voc-new:orderable-unit [0..1]

  

  
  
  

  
  
| epo-cat:hasPrice| 
  Relation indicating that the instance of the concept has a Price.|epo-cat:CatalogueLine → epo-cat:Price [0..&#42;]

  

  
  
| epo-cat:hasStandardisedUnitPrice| 
  The item price based on a standardised unit. Additional Information: The unit must be indicated in the Quantity, with a quantity value of 1.|epo-cat:CatalogueLine → epo-cat:Price [0..&#42;]

  

  
  
  

  
  
| epo-cat:hasTransactionConditionsCode| 
  Coded description of the specific transaction conditions (purchasing, sales, payment, delivery) for an item.|epo-cat:CatalogueLine → at-voc-new:transaction-conditions [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo-cat:comprisesCatalogueResponseLine| 
  Incorporates Catalogue Response Line.|epo-cat:CatalogueResponse → epo-cat:CatalogueResponseLine [0..&#42;]

  

  
  
  

  
  
| epo-cat:refersToCatalogue| 
  |epo-cat:CatalogueResponse → epo-cat:PostAwardCatalogue [1]

  

  
  
| epo-cat:specifiesCatalogueResponseInformation| 
  Relation indicating the Catalogue Response Information.|epo-cat:CatalogueResponse → epo-cat:CatalogueResponseInformation [1]

  

  
  
| epo-ord:hasResponseStatus| 
  Relation indicating the response status.|epo-cat:CatalogueResponseInformation → at-voc-new:ResponseStatus [1]

  

  
  
| epo-cat:isSpecificToCatalogueResponseLine| 
  Information that is particular to a Catalogue Response Line.|epo-cat:CatalogueResponseInformation → epo-cat:CatalogueResponseLine [0..1]

  

  
  
| epo:hasUUID| 
  A universally unique identifier for an instance of this document.|epo-cat:CatalogueResponseLine → adms:Identifier [1]

  

  
  
| epo-cat:refersToCatalogueLine| 
  Reference to a Catalogue Line.|epo-cat:CatalogueResponseLine → epo-cat:CatalogueLine [1]

  

  
  
| epo-inv:isSpecificToInvoiceLine| 
  Information that is particular to an Invoice Line.|epo-cat:ChargeInformation → epo-inv:InvoiceLine [0..&#42;]

  

  
  
| epo-ord:isSpecificToOrderLine| 
  Information that is particular to one or multiple Order Lines.|epo-cat:ChargeInformation → epo-ord:OrderLine [0..&#42;]

  

  
  
| epo-ful:concernsGoodsItem| 
  Relates to Goods Item.|epo-cat:DimensionInformation → epo-ful:GoodsItem [0..1]

  

  
  
| epo-cat:concernsItem| 
  Relates to Item.|epo-cat:DimensionInformation → epo-cat:AbstractItem [0..1] +
epo-cat:EnvironmentalEmissionInformation → epo-cat:AbstractItem [0..1]

  

  
  
| epo-ful:concernsPackage| 
  Relates to Package.|epo-cat:DimensionInformation → epo-ful:Package [0..1]

  

  
  
| epo-ful:concernsTransportEquipment| 
  Relates to Transport Equipment.|epo-cat:DimensionInformation → epo-ful:TransportEquipment [0..1]

  

  
  
| epo-ful:concernsTransportMeans| 
  Relates to Transport Means.|epo-cat:DimensionInformation → epo-ful:TransportMeans [0..1] +
epo-cat:EnvironmentalEmissionInformation → epo-ful:TransportMeans [0..1]

  

  
  
  

  
  
| epo-cat:hasMaximumMeasure| 
  Relation indicating the upper limit of the measure.|epo-cat:DimensionInformation → epo:Quantity [0..1]

  

  
  
| epo-cat:hasMeasure| 
  Relation indicating the unit used for stating the size.|epo-cat:DimensionInformation → epo:Quantity [0..1] +
epo-cat:EnvironmentalEmissionInformation → epo:Quantity [1]

  

  
  
| epo-cat:hasMeasuredAttributeCode| 
  Relation indicating the Measured Attribute Code.|epo-cat:DimensionInformation → at-voc-new:measured-attribute-code [1]

  

  
  
| epo-cat:hasMinimumMeasure| 
  Relation indicating the lower limit of the measure.|epo-cat:DimensionInformation → epo:Quantity [0..1]

  

  
  
  

  
  
| epo-cat:hasEnvironmentalEmissionCode| 
  Relation indicating the Environmental Emission Code.|epo-cat:EnvironmentalEmissionInformation → at-voc-new:environmental-emission-code [1]

  

  
  
| epo-cat:isSpecificToLine| 
  Information that is particular to a Line.|epo-cat:InformationHub → epo-cat:Line [0..&#42;]

  

  
  
| epo-cat:describesItem| 
  Characterises Item.|epo-cat:ItemProperty → epo-cat:AbstractItem [1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo-cat:hasMaximumValue| 
  Relation indicating the upper limit of the numerical quantity.|epo-cat:ItemProperty → epo:Quantity [0..1]

  

  
  
| epo-cat:hasMinimumValue| 
  Relation indicating the lower limit of the numerical quantity.|epo-cat:ItemProperty → epo:Quantity [0..1]

  

  
  
| epo-cat:hasQualifiedValue| 
  Qualified value of the property, which is defined in a classification scheme. Additional Information: For example, the (0173-1#02-AAA026#007) drilling diameter of an item has value of 12 inches.|epo-cat:ItemProperty → epo:Quantity [0..1]

  

  

  
  
  

  
  
| epo-cat:isRelatedToItem| 
  Relation indicating the association with an Item.|epo-cat:ItemRelation → epo-cat:AbstractItem [1]

  

  
  
  

  
  
| epo-ful:hasAssociatedDocument| 
  Is related to a Document.|epo-cat:Line → epo:Document [0..1]

  

  
  
| epo-cat:specifiesItem| 
  Relation indicating the Item.|epo-cat:Line → epo-cat:AbstractItem [1]

  

  
  
| epo:hasManufacturerID| 
  The manufacturer's identifier for the item.|epo-cat:Manufacturer → adms:Identifier [0..1]

  

  
  
| epo-cat:isSubordinatedToContract| 
  Relation indicating that the instance of the concept is governed by a specific Contract.|epo-cat:PostAwardCatalogue → epo:Contract [0..1]

  

  
  
| epo-ord:hasCustomerReference| 
  An identifier assigned by the Buyer used for internal routing purposes.|epo-cat:PostAwardDocument → adms:Identifier [0..1]

  

  
  
| epo:hasDocumentStatus| 
  https://test-docs.peppol.eu/logistics/transport-execution/codelist/DocumentStatusCode/|epo-cat:PostAwardDocument → at-voc-new:document-status [0..1]

  

  
  
| epo-cat:hasBaseQuantity| 
  The quantity at which the net monetary value applies.|epo-cat:Price → epo:Quantity [0..1]

  

  
  
| epo-cat:hasDeliveryLocation| 
  Location delivery area where the Item can be ordered to the given price.|epo-cat:Price → dct:Location [0..&#42;]

  

  
  
| epo-cat:hasExpectedDeliveryTime| 
  The expected amount of time between the order and delivery of an item.|epo-cat:Price → time:Duration [0..1]

  

  
  
| epo-ord:hasGrossMonetaryValue| 
  The Monetary Value before any deductions.|epo-cat:Price → epo:MonetaryValue [0..1]

  

  
  
| epo-cat:hasNetMonetaryValue| 
  The price amount of an Item exclusive of taxes and after subtracting price discounts.|epo-cat:Price → epo:MonetaryValue [1]

  

  
  
| epo-cat:hasOrderabableUnitFactorRate| 
  The factor by which the base unit of the price can be converted to orderable unit. Additional information: This is needed when the base price is provided different than the orderable unit. For example, when selling paper, the price may be set per page, but the orderable unit is a package of 500 pieces. Therefore the price needs to be converted to the orderable unit.|epo-cat:Price → epo:Quantity [0..1]

  

  
  
| epo-ord:hasPriceDiscountInformation| 
  Relation indicating the Allowance Information applied on the Price.|epo-cat:Price → epo-ord:AllowanceInformation [0..1]

  

  
  
| epo:hasPriceSurchargeInformation| 
  Relation indicating the Charge Information applied on the Price.|epo-cat:Price → epo-cat:ChargeInformation [0..1]

  

  
  
| epo-cat:hasPriceType| 
  Relation indicating the Price Type.|epo-cat:Price → at-voc-new:price-type [0..1]

  

  
  
| epo-cat:hasPriceValidity| 
  The period of time when the Item can be ordered to the given price.|epo-cat:Price → time:Interval [1]

  

  
  
| epo-cat:hasQuantityThreshold| 
  The minimum quantity of the item that can be ordered to the given net monetary value.|epo-cat:Price → epo:Quantity [0..1]

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].