



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-con:ContractAmendment | A change to an existing Contract that is agreed by the contracting parties.
      
    
      
| epo-con:ContractModificationInformation | Information about a Contract Amendment.
      
    
      
| epo-con:Deliverable | Item that the supplier is obligated to provide under a contract.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
  
  
| epo-con:ContractModificationInformation
| epo:hasModificationDescription| 
  An explanatory text about this context.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-con:ContractModificationInformation
| epo:hasModificationReasonDescription| 
  An explanation about the reasons for using the concept.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
| epo:amendsContract| 
  Modifies or changes the terms of an existing Contract.|epo-con:ContractAmendment → epo:Contract [1]

  

  
  
| epo:updatesContractValue| 
  Changes the Contract Monetary Value.|epo-con:ContractAmendment → epo:MonetaryValue [0..1]

  

  
  
| epo:concernsContractAmendment| 
  Relates to Contract Amendment.|epo-con:ContractModificationInformation → epo-con:ContractAmendment [1]

  

  
  
  

  
  
| epo:hasModificationJustification| 
  Explanation of why a contract was modified. The codelist to be used is at-voc:modification-justification which is available at http://publications.europa.eu/resource/dataset/modification-justification|epo-con:ContractModificationInformation → at-voc:modification-justification [1]

  

  
  
  

  
  
| epo:relatesToEFormSectionIdentifier| 
  Is about a specific eForms section.|epo-con:ContractModificationInformation → adms:Identifier [0..&#42;]

  

  
  
| epo-cat:hasQuantity| 
  Relation indicating that the instance of the concept has a Quantity.|epo-con:Deliverable → epo:Quantity [0..1]

  

  
  
| epo:hasTotalValue| 
  Relation indicating the overall Monetary Value.|epo-con:Deliverable → epo:MonetaryValue [0..1]

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].