



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-ful:AbstractContainer | Gathering class for Packages and Transport Handling Units.
      
    
      
| epo-ful:Carrier | The Role of an Agent who handles the physical Delivery/Transportation of the (Despatched) Shipment. Additional Information: This Role is often referred to as the deliverer.
      
    
      
| epo-ful:Consignment | A batch of goods destined for or delivered to someone. Additional information: Consignment is a Transport Agreement between the Despatcher and the Consignee as to who and how the goods are despatched and received.
      
    
      
| epo-ful:DespatchAdvice | A document notifying the sending of goods or the execution of works or services.
      
    
      
| epo-ful:DespatchLine | Details concerning the fulfilment of an Order Line.
      
    
      
| epo-ful:Despatcher | The Role of an Agent who sends the goods or notifies of the service or works execution. Additional Information: The Role is carried out by the Supplier or on behalf of the Supplier. This Role is often referred to as the Despatch Party, Consignor or Deliverer.
      
    
      
| epo-ful:FreightForwarder | The Role of an Agent who organise the logistic operations need for a fulfilment.
      
    
      
| epo-ful:GoodsItem | An Item including its initial packaging during transportation. Additional information: For example, the Item being bought is the computer. The weight of the computer is X. The weight of the Goods Item is the weight of the computer plus the weight of the initial packaging. During transportation you have for example trace ID which is applied to the GoodsItem, rather than on the Item itself. The declared statistical value can only apply once you have a GoodsItem.
      
    
      
| epo-ful:NotificationReceiver | The Role of an Agent that is informed about the arrival of a Shipment at a destination. Additional information: This could be for example customs and excise.
      
    
      
| epo-ful:Package | Container used for transportation.
      
    
      
| epo-ful:ReceiptAdvice | A formal reply from the Buyer to the Seller acknowledging the physical or electronic receipt of goods or services delivered under a Procurement Contract.
      
    
      
| epo-ful:ReceiptAdviceLine | Details concerning the Fulfilment of a Despatch Line.
      
    
      
| epo-ful:ShipmentAgreement | The commercial agreement between the Buyer and the Seller. Additional Information: The Shipment Agreement describes the items being shipped.
      
    
      
| epo-ful:ShipmentInformation | Information about the transportation of an identifiable collection of Goods Items from the Despatcher to the Consignee.
      
    
      
| epo-ful:ShipmentStage | Part of the itinerary of a shipment. Additional information: In the context of fulfilment only the last part of the itinerary is taken into consideration.
      
    
      
| epo-ful:TemperatureSpecification | Description of the temperature requirements during shipment.
      
    
      
| epo-ful:TransportEquipment | Description of the apparatus used during transportation. Additional information: The equipment may be a container, a trailer, means of assistance to load or unload the Goods Items.
      
    
      
| epo-ful:TransportEquipmentSeal | Means used to ensure that the Transport Equipment is not tampered during transportation.
      
    
      
| epo-ful:TransportHandlingUnit | The outermost Package that the Carrier is handling.
      
    
      
| epo-ful:TransportMeans | Description of a particular vehicle or vessel used for the conveyance of goods or persons.
      
    
      
| epo-ful:TransportMeansOperator | The Role of an Agent who is responsible for controlling the Transport Means.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ful:AbstractContainer
| epo-ful:hasPackingMaterialDescription| 
  Explanatory text about the physical substance that a Package is made of.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
| epo-ful:AbstractContainer + 
epo-ful:Consignment
| epo-ful:isHazardousRisk| 
  Indicates whether some of the contained Goods Items are hazardous.|xsd:boolean [0..1] +
  xsd:boolean [0..1]
  
  
  
| epo-ful:AbstractContainer
| epo-ful:isReturnableMaterial| 
  Indicates whether the container or part of the container is to be sent back.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ful:Consignment + 
epo-ful:TransportHandlingUnit
| epo-ful:hasHandlingInstruction| 
  Instruction on how to handle the Goods Items during transportation.|rdf:PlainLiteral [0..&#42;] +
  rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
| epo-ful:Consignment
| epo-ful:hasSpecialServiceInstruction| 
  Description about special services needed for loading or unloading the Goods Items.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ful:DespatchLine
| epo-ful:hasOutstandingQuantityReason| 
  Explanation of the outstanding quantity still to be despatched.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ful:Package
| epo-ful:hasPackagingStatusDescription| 
  Explanatory text about the condition of a Package.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-ful:Package
| epo-ful:hasPackagingTypeDescription| 
  Explanatory text about how the Goods Item is packed.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ful:ShipmentInformation
| epo-ful:hasDespatchDate| 
  The date of sending of goods or the execution of works or services.|xsd:dateTime [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ful:TransportEquipment
| epo-ful:isPowerIndicated| 
  Indicates whether the instance of the concept can supply electrical energy. Additional Information: The instance of the concept can be, for example, Transport Equipment.|xsd:boolean [0..1]
  
  
  
| epo-ful:TransportEquipment
| epo-ful:isRefrigerated| 
  Indicates whether the instance of the concept includes refrigeration. Additional Information: The instance of the concept can be, for example, Transport Equipment.|xsd:boolean [0..1]
  
  
  
| epo-ful:TransportHandlingUnit
| epo-ord:hasShippingMark| 
  A text that the buyer requests to be printed on the packing labels.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
| epo-ord:hasAcceptanceStatus| 
  Relation indicating the acceptance status.|epo-ful:AbstractContainer → at-voc-new:ResponseStatus [0..1]

  

  
  
| epo-ful:hasGrossVolume| 
  The amount of space that is required including the packaging.|epo-ful:AbstractContainer → epo:Quantity [0..1] +
epo-ful:Consignment → epo:Quantity [0..1]

  

  
  
| epo-ful:hasGrossWeight| 
  The total mass of goods including the packaging.|epo-ful:AbstractContainer → epo:Quantity [0..1] +
epo-ful:Consignment → epo:Quantity [0..1]

  

  
  
| epo-ful:hasHeight| 
  The vertical measurement.|epo-ful:AbstractContainer → epo:Quantity [0..1]

  

  
  
| epo-ful:hasLength| 
  The horizontal measurement. Additional Information: The length is the longer side between the length and the width.|epo-ful:AbstractContainer → epo:Quantity [0..1]

  

  
  
| epo-ful:hasNetVolume| 
  The amount of space that is required without the packaging.|epo-ful:AbstractContainer → epo:Quantity [0..1]

  

  
  
| epo-ful:hasNetWeight| 
  The total mass of goods without the packaging.|epo-ful:AbstractContainer → epo:Quantity [0..1] +
epo-ful:Consignment → epo:Quantity [0..1]

  

  
  
  

  
  
| epo-ful:hasTemperatureSpecification| 
  Relation indicating the Temperature Specification for the instance of the concept.|epo-ful:AbstractContainer → epo-ful:TemperatureSpecification [0..1]

  

  
  
| epo-ful:hasTotalGoodsItemQuantity| 
  Relation indicating the number of the Goods Items.|epo-ful:AbstractContainer → epo:Quantity [0..1] +
epo-ful:Consignment → epo:Quantity [0..1]

  

  
  
| epo-ful:hasWidth| 
  The measurement of the depth. Additional Information: The width is the shorter side between the length and the width.|epo-ful:AbstractContainer → epo:Quantity [0..1]

  

  

  
  
  

  
  
  

  
  
| epo-ful:containsTransportHandlingUnit| 
  Includes Transport Handling Unit.|epo-ful:Consignment → epo-ful:TransportHandlingUnit [1..&#42;]

  

  
  
| epo-ful:hasCarriageShipmentStage| 
  The Shipment Stage for the last mile covered in a transport chain.|epo-ful:Consignment → epo-ful:ShipmentStage [0..1]

  

  
  
| epo-ful:hasConsigneeConsignmentID| 
  The identifier of the the Consignment given by the Consignee.|epo-ful:Consignment → adms:Identifier [0..1]

  

  
  
| epo-ful:hasDeclaredStatisticalValue| 
  The Monetary Value declared for statistical purposes.|epo-ful:Consignment → epo:MonetaryValue [0..1] +
epo-ful:GoodsItem → epo:MonetaryValue [0..&#42;]

  

  
  
| epo-ful:hasDespatcherConsignmentID| 
  The identifier of the the Consignment given by the Despatcher.|epo-ful:Consignment → adms:Identifier [0..1]

  

  
  
| epo-ful:hasFreightCharge| 
  The total cost for moving the goods.|epo-ful:Consignment → epo-cat:ChargeInformation [0..&#42;]

  

  
  
  

  
  
| epo-ful:hasHandlingInstructionCode| 
  Instruction on how to handle the Goods Items during transportation, expressed as a code.|epo-ful:Consignment → at-voc-new:handling-instruction [0..1] +
epo-ful:TransportHandlingUnit → at-voc-new:handling-instruction [0..1]

  

  
  
| epo-ful:hasLoadingMeter| 
  The area of the Consignment in meters divided by the width of the truck, which is considered to be 2.4 meters.|epo-ful:Consignment → epo:Quantity [0..1]

  

  
  
| epo-ful:hasRequestedPickUpInformation| 
  Information about the requested despatch of the Goods Items.|epo-ful:Consignment → epo-ful:ShipmentInformation [1]

  

  
  
  

  
  
| epo-ful:hasTransportHandlingUnitQuantity| 
  Relation indicating the number of the Transport Handling Unit.|epo-ful:Consignment → epo:Quantity [0..1]

  

  
  
| epo:specifiesFreightForwarder| 
  Relation indicating that the instance of the concept involves the Freight Forwarder.|epo-ful:Consignment → epo-ful:FreightForwarder [0..&#42;]

  

  
  
| epo:specifiesNotificationReceiver| 
  Relation indicating that the instance of the concept involves the Notification Receiver.|epo-ful:Consignment → epo-ful:NotificationReceiver [0..&#42;]

  

  
  
| epo-ful:comprisesDespatchLine| 
  Incorporates Despatch Line.|epo-ful:DespatchAdvice → epo-ful:DespatchLine [1..&#42;]

  

  
  
| epo-ful:hasDespatchAdviceType| 
  Classification of a Despatch Advice.|epo-ful:DespatchAdvice → at-voc-new:despatch-advice-type [0..1]

  

  
  
| epo-ful:refersToConsignment| 
  Reference to a Consignment.|epo-ful:DespatchAdvice → epo-ful:Consignment [1]

  

  
  
| epo-ful:refersToOrder| 
  Reference to an Order.|epo-ful:DespatchAdvice → epo-ord:Order [0..1]

  

  
  
| epo-ful:refersToShipmentAgreement| 
  Reference to a Shipment Agreement.|epo-ful:DespatchAdvice → epo-ful:ShipmentAgreement [0..1]

  

  
  
| epo-ful:specifiesConsignee| 
  Relation indicating that the instance of the concept involves the Consignee.|epo-ful:DespatchAdvice → epo-ord:Consignee [1..&#42;] +
epo-ful:ReceiptAdvice → epo-ord:Consignee [1..&#42;]

  

  
  
| epo-ful:specifiesDespatcher| 
  Relation indicating that the instance of the concept involves the Despatcher.|epo-ful:DespatchAdvice → epo-ful:Despatcher [1..&#42;] +
epo-ful:ReceiptAdvice → epo-ful:Despatcher [1]

  

  
  
| epo-ful:specifiesOriginator| 
  Relation indicating that the instance of the concept involves the Originator.|epo-ful:DespatchAdvice → epo-ord:Originator [0..&#42;]

  

  
  
| epo-ful:hasDespatchedQuantity| 
  The Quantity that has been sent.|epo-ful:DespatchLine → epo:Quantity [1]

  

  
  
| epo-ful:hasOutstandingQuantity| 
  The Quantity of non-despatched Goods Items.|epo-ful:DespatchLine → epo:Quantity [0..1]

  

  
  
  

  
  
| epo-ful:refersToOrderLine| 
  Reference to an Order Line.|epo-ful:DespatchLine → epo-ord:OrderLine [1]

  

  
  
| epo-ful:hasTraceID| 
  The identifier used for tracking the Goods Item. Additional information: An example is the EPC number used in RFID.|epo-ful:GoodsItem → adms:Identifier [0..1]

  

  
  
| epo-ful:refersToDespatchLine| 
  Reference to a Despatch Line.|epo-ful:GoodsItem → epo-ful:DespatchLine [1]

  

  
  
| epo-ful:containsGoodsItem| 
  Includes Goods Item.|epo-ful:Package → epo-ful:GoodsItem [0..&#42;]

  

  
  
| epo-ful:containsPackage| 
  Includes Package.|epo-ful:Package → epo-ful:Package [0..&#42;]

  

  
  
| epo-ful:hasPackagingStatus| 
  Relation indicating the Packaging Status.|epo-ful:Package → at-voc-new:packaging-status [0..1]

  

  
  
  

  
  
| epo-ful:hasPackagingType| 
  The kind of Package.|epo-ful:Package → at-voc-new:packaging-type [0..1]

  

  
  
  

  
  
| epo-ful:comprisesReceiptAdviceLine| 
  Incorporates Receipt Advice Line.|epo-ful:ReceiptAdvice → epo-ful:ReceiptAdviceLine [0..&#42;]

  

  
  
| epo-ful:isSubmittedForDespatchAdvice| 
  Relation indicating that the instance of the concept is sent for a specific Despatch Advice.|epo-ful:ReceiptAdvice → epo-ful:DespatchAdvice [0..1]

  

  
  
| epo-ful:isSubmittedForShipment| 
  Relation indicating that the instance of the concept is sent for a specific Shipment.|epo-ful:ReceiptAdvice → epo-ful:ShipmentInformation [0..1]

  

  
  
| epo:specifiesBuyer| 
  Relation indicating that the instance of the concept involves the Buyer.|epo-ful:ReceiptAdvice → epo:Buyer [0..1]

  

  
  
| epo-ful:specifiesReceiptAdviceInformation| 
  Relation indicating the Receipt Advice Information.|epo-ful:ReceiptAdvice → epo-ful:ReceiptAdviceInformation [0..&#42;]

  

  
  
| epo:specifiesSeller| 
  Relation indicating that the instance of the concept involves the Seller.|epo-ful:ReceiptAdvice → epo-ord:Seller [0..1]

  

  
  
| epo-ful:hasOversupplyQuantity| 
  Relation indicating the Quantity surplus.|epo-ful:ReceiptAdviceLine → epo:Quantity [0..1]

  

  
  
| epo-ful:hasReceivedQuantity| 
  Relation indicating the delivered Quantity.|epo-ful:ReceiptAdviceLine → epo:Quantity [0..1]

  

  
  
| epo-ful:hasRejectedQuantity| 
  Relation indicating the non-accepted Quantity.|epo-ful:ReceiptAdviceLine → epo:Quantity [0..1]

  

  
  
| epo-ful:hasShortQuantity| 
  Relation indicating the Quantity deficit.|epo-ful:ReceiptAdviceLine → epo:Quantity [0..1]

  

  
  
| epo-ful:isSubmittedForDespatchLine| 
  Relation indicating that the instance of the concept is sent for a specific Despatch Line.|epo-ful:ReceiptAdviceLine → epo-ful:DespatchLine [1]

  

  
  
| epo-ful:agreedByBuyer| 
  Accepted by Buyer.|epo-ful:ShipmentAgreement → epo:Buyer [1..&#42;]

  

  
  
| epo-ful:agreedBySeller| 
  Accepted by Seller.|epo-ful:ShipmentAgreement → epo-ord:Seller [1..&#42;]

  

  

  
  
  

  
  
| epo-ful:hasDespatchPeriod| 
  The time period when the Despatcher picks-up the Goods Items to be delivered.|epo-ful:ShipmentInformation → time:Interval [0..1]

  

  
  
| epo-ful:hasEstimatedDeliveryPeriod| 
  The forecasted time period given by the Despatcher to provide the goods and services.|epo-ful:ShipmentInformation → time:Interval [0..1]

  

  
  
| epo-ful:isSpecificToDespatchLine| 
  Information that is particular to a Despatch Line.|epo-ful:ShipmentInformation → epo-ful:DespatchLine [0..1]

  

  
  
| epo-ful:refersToDeliveryInformation| 
  Reference to a Delivery Information.|epo-ful:ShipmentInformation → epo-ord:DeliveryInformation [1]

  

  
  
| epo-ful:specifiesPlaceOfDespatch| 
  Relation indicating the Location of the Despatch of the Goods Items to be delivered.|epo-ful:ShipmentInformation → dct:Location [0..1]

  

  
  
| epo:hasArrivalShipmentInformation| 
  Shipment Information about the destination of the Consignment for a given Shipment Stage.|epo-ful:ShipmentStage → epo-ful:ShipmentInformation [0..&#42;]

  

  
  
| epo-ful:hasDepartureShipmentInformation| 
  Shipment Information about the place the Consignment is leaving from in a given Shipment Stage.|epo-ful:ShipmentStage → epo-ful:ShipmentInformation [0..&#42;]

  

  
  
| epo:specifiesCarrier| 
  Relation indicating that the instance of the concept involves the Carrier.|epo-ful:ShipmentStage → epo-ful:Carrier [0..1]

  

  
  
| epo-ful:usesTransportMeans| 
  Relation indicating that a Shipment Stage utilises a Transport Means.|epo-ful:ShipmentStage → epo-ful:TransportMeans [1..&#42;]

  

  
  
| epo-ful:hasMaximumTemperature| 
  The highest tolerated temperature.|epo-ful:TemperatureSpecification → epo:Quantity [0..1]

  

  
  
| epo-ful:hasMinimumTemperature| 
  The lowest tolerated temperature.|epo-ful:TemperatureSpecification → epo:Quantity [0..1]

  

  
  
| epo-ful:hasSizeType| 
  An extension classification specifying the measurement of the Transport Equipment. Additional Information: This codelist should be used only in the case of a container.|epo-ful:TransportEquipment → at-voc-new:size-type [0..&#42;]

  

  
  
| epo-ful:hasTransportEquipmentSeal| 
  Relation indicating that the instance of the concept has a Transport Equipment Seal.|epo-ful:TransportEquipment → epo-ful:TransportEquipmentSeal [0..&#42;]

  

  
  
| epo-ful:hasTransportEquipmentType| 
  The kind of Transport Equipment.|epo-ful:TransportEquipment → at-voc-new:transport-equipment-type [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo-ful:usesTransportEquipment| 
  Relation indicating that a Transport Handling Unit utilises a Transport Equipment.|epo-ful:TransportHandlingUnit → epo-ful:TransportEquipment [0..&#42;]

  

  
  
| epo:hasDriverPerson| 
  Relation indicating the operator of the Transport Means.|epo-ful:TransportMeans → epo-ful:TransportMeansOperator [1..&#42;]

  

  
  
| epo-ful:hasTransportMeansType| 
  The kind of Transport Means.|epo-ful:TransportMeans → at-voc-new:transport-means-type [0..1]

  

  
  
| epo-ful:hasTransportMode| 
  The type of the transport used.|epo-ful:TransportMeans → at-voc-new:transport-mode [1]

  

  
  
| epo-ful:hasVehicleID| 
  The identifier of the Transport Means.|epo-ful:TransportMeans → adms:Identifier [1]

  

  
  
| epo-ful:hasVehicleSegmentID| 
  The identifier of a part of the Transport Means.|epo-ful:TransportMeans → adms:Identifier [0..1]

  

  
  
| epo:playedBy| 
  Relation indicating the Agent that fulfills the function of the instance of the concept.|epo-ful:TransportMeansOperator → foaf:Person [0..1]

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].