



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-inv:CreditNote | A Document sent by the Seller to the Buyer to reduce or cancel all or part of the amount previously invoiced.
      
    
      
| epo-inv:CreditNoteLine | Details concerning a given unit of goods, services or works mentioned in the Credit Note.
      
    
      
| epo-inv:CreditTransferInformation | Information about a direct payment of money from one bank account into another.
      
    
      
| epo-inv:Invoice | A commercial Document issued by the Seller to the Buyer to collect payments for the goods or services provided and to state the VAT amount due by the Buyer.
      
    
      
| epo-inv:InvoiceLine | Details concerning a given unit of goods, services or works mentioned in the Invoice.
      
    
      
| epo-inv:InvoiceNote | Textual note that is relevant to the Invoice as a whole.
      
    
      
| epo-inv:Payee | A Role of an Agent that receives the payment. Additional Information: The role of Payee may be fulfilled by another party than the Seller, e.g. a factoring service.
      
    
      
| epo-inv:PaymentCardInformation | Information about card used for payment contemporaneous with invoice issuance.
      
    
      
| epo-inv:PaymentInstructionsInformation | Information about the payment.
      
    
      
| epo-inv:SellerTaxRepresentative | A Role of an Agent that can represent an Organization for taxation purposes. Additional Information: The Seller Tax Representative Role is not a Legal Representative.
      
    
      
| epo-inv:TaxBreakdownInformation | Information about tax breakdown by different categories, rates and exemption reasons.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
  
  
  
  
| epo-inv:CreditTransferInformation
| epo-inv:hasPaymentAccountName| 
  The name of the account that can send and receive payments to and from a payment service provider.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
| epo-inv:Invoice
| epo-ord:hasAccountingCost| 
  |rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-inv:Invoice
| epo-inv:hasPaymentDueDate| 
  Final date until which the Payment can be made.|xsd:date [0..1]
  
  
  
  
  
| epo-inv:Invoice
| epo-ord:hasPaymentTerm| 
  Condition and stipulation of the Payment.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
| epo-inv:Invoice
| epo-inv:hasTaxPointDate| 
  The date when the tax becomes accountable for the Seller and for the Buyer. Additional Information: That date can be determined and differs from the date of issue of the invoice, according to the national implementation of the directive.|xsd:date [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-inv:InvoiceNote
| epo-inv:hasInvoiceNoteDescription| 
  A textual note that gives unstructured information that is relevant to the Invoice as a whole.|rdf:PlainLiteral [1..1]
  
  
  
  
  
| epo-inv:PaymentCardInformation
| epo-inv:hasPaymentCardHolderName| 
  The name of the account holder of the card used for payment. Additional Information: An account holder is the entity listed or identified as the holder of a Financial Account by the Financial Institution.|rdf:PlainLiteral [0..1]
  
  
  
| epo-inv:PaymentCardInformation
| epo-inv:hasPaymentCardPrimaryAccountNumber| 
  The series of digits embossed on the front of a card used for payment.|rdf:PlainLiteral [1..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-inv:PaymentInstructionsInformation
| epo-inv:hasPaymentMeansDescription| 
  The means for how a payment is expected to be or has been settled, expressed as text.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-inv:PaymentInstructionsInformation
| epo-inv:hasRemittanceInformation| 
  A textual value used to establish a link between the payment and the Invoice, issued by the Seller.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-inv:TaxBreakdownInformation
| epo-inv:hasTaxExemptionReasonDescription| 
  An explanation on why the amount is exempted from tax or why no tax is being charged according to the legislation, expressed as a text.|rdf:PlainLiteral [0..1]
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
| epo-inv:comprisesCreditNoteLine| 
  Incorporates Credit Note Line.|epo-inv:CreditNote → epo-inv:CreditNoteLine [1..&#42;]

  

  
  
| epo-inv:refersToInvoice| 
  Reference to an Invoice.|epo-inv:CreditNote → epo-inv:Invoice [0..1]

  

  
  
| epo-inv:isSubmittedForInvoiceLine| 
  Relation indicating that the instance of the concept is sent for a specific Invoice Line.|epo-inv:CreditNoteLine → epo-inv:InvoiceLine [0..1]

  

  
  
| epo-inv:hasPaymentAccountIdentifier| 
  A unique identifier of the financial payment account, at a payment service provider, to which payment should be made.|epo-inv:CreditTransferInformation → adms:Identifier [1]

  

  
  
  

  
  
| epo-inv:hasPaymentServiceProviderIdentifier| 
  An identifier for the payment service provider where a payment account is located.|epo-inv:CreditTransferInformation → adms:Identifier [0..1]

  

  
  
| epo-inv:comprisesInvoiceLine| 
  Incorporates Invoice Line.|epo-inv:Invoice → epo-inv:InvoiceLine [1..&#42;]

  

  
  
  

  
  
| epo-ord:hasAmountDueForPayment| 
  Relation indicating the Monetary Value that has to be paid.|epo-inv:Invoice → epo:MonetaryValue [1]

  

  
  
| epo-inv:hasInvoiceNote| 
  Contains Invoice Note.|epo-inv:Invoice → epo-inv:InvoiceNote [0..&#42;]

  

  
  
| epo-inv:hasInvoicedObjectIdentifier| 
  An identifier for an object on which the invoice is based, given by the Seller.|epo-inv:Invoice → adms:Identifier [0..1]

  

  
  
| epo-inv:hasInvoicingPeriod| 
  Relation indicating the time range for creating, sending, and managing Invoices.|epo-inv:Invoice → time:Interval [0..1]

  

  
  
| epo:hasLotReference| 
  Relation indicating the instance of the concept refers to a Lot.|epo-inv:Invoice → epo:Lot [1..&#42;]

  

  
  
  

  
  
| epo-inv:hasPaymentInstructionsInformation| 
  Relation indicating the Payment Instruction Information.|epo-inv:Invoice → epo-inv:PaymentInstructionsInformation [0..&#42;]

  

  
  
  

  
  
| epo-ord:hasPrepaidAmount| 
  Relation indicating the Monetary Value that is paid in advance.|epo-inv:Invoice → epo:MonetaryValue [0..&#42;]

  

  
  
| epo-ord:hasRoundingAmount| 
  Relation indicating the adjustment Monetary Value applied to bring calculated total to a convenient value.|epo-inv:Invoice → epo:MonetaryValue [0..1]

  

  
  
| epo-inv:hasTaxBreakdownInformation| 
  Relation indicating the Tax Breakdown Information.|epo-inv:Invoice → epo-inv:TaxBreakdownInformation [1..&#42;]

  

  
  
| epo-ord:hasTaxInformation| 
  Relation indicating the Tax Information.|epo-inv:Invoice → epo-ord:TaxInformation [1] +
epo-inv:InvoiceLine → epo-ord:TaxInformation [1] +
epo-inv:TaxBreakdownInformation → epo-ord:TaxInformation [1]

  

  
  
  

  
  
| epo-inv:hasTaxPointDateCode| 
  Relation indicating the a Tax Date.|epo-inv:Invoice → at-voc-new:tax-date [0..1]

  

  
  
| epo-inv:hasTotalAccountingCurrencyTaxAmount| 
  Relation indicating the overall Monetary Value of the Tax applied on the currency in which the financial transactions are recorded at the company level.|epo-inv:Invoice → epo:MonetaryValue [0..&#42;]

  

  
  
| epo-ord:hasTotalAllowanceAmount| 
  Relation indicating the overall Monetary Value of the Allowance.|epo-inv:Invoice → epo:MonetaryValue [0..&#42;]

  

  
  
| epo-ord:hasTotalChargeAmount| 
  Relation indicating the overall Monetary Value of the Charge.|epo-inv:Invoice → epo:MonetaryValue [0..&#42;]

  

  
  
| epo-ord:hasTotalLineAmount| 
  Relation indicating the overall Monetary Value of the Line.|epo-inv:Invoice → epo:MonetaryValue [1..&#42;]

  

  
  
| epo-inv:hasTotalTaxAmount| 
  Relation indicating the overall Monetary Value of the Tax applied.|epo-inv:Invoice → epo:MonetaryValue [0..&#42;]

  

  
  
| epo-ord:hasTotalTaxExclusiveAmount| 
  Relation indicating the overall Monetary Value without Tax.|epo-inv:Invoice → epo:MonetaryValue [1..&#42;]

  

  
  
| epo-ord:hasTotalTaxInclusiveAmount| 
  Relation indicating the overall Monetary Value with Tax.|epo-inv:Invoice → epo:MonetaryValue [1..&#42;]

  

  
  
| epo:refersToContract| 
  Reference to a Contract.|epo-inv:Invoice → epo:Contract [0..1]

  

  
  
| epo-inv:refersToDespatchAdvice| 
  Reference to a Despatch Advice.|epo-inv:Invoice → epo-ful:DespatchAdvice [0..1]

  

  
  
| epo-ful:refersToOrder| 
  Reference to an Order.|epo-inv:Invoice → epo-ord:Order [0..1]

  

  
  
| epo:refersToProject| 
  Reference to a Project.|epo-inv:Invoice → epo:Project [0..1]

  

  
  
| epo-inv:refersToReceiptAdvice| 
  Reference to a Receipt Advice.|epo-inv:Invoice → epo-ful:ReceiptAdvice [0..1]

  

  
  
| epo-ord:specifiesAllowanceInformation| 
  Relation indicating the Allowance Information.|epo-inv:Invoice → epo-ord:AllowanceInformation [0..&#42;]

  

  
  
| epo:specifiesBuyer| 
  Relation indicating that the instance of the concept involves the Buyer.|epo-inv:Invoice → epo:Buyer [1]

  

  
  
| epo-cat:specifiesChargeInformation| 
  Relation indicating the Charge Information.|epo-inv:Invoice → epo-cat:ChargeInformation [0..&#42;]

  

  
  
| epo-ord:specifiesDeliveryInformation| 
  Relation indicating the Delivery Information.|epo-inv:Invoice → epo-ord:DeliveryInformation [0..1]

  

  
  
| epo-inv:specifiesPayee| 
  Relation indicating that the instance of the concept involves the Payee.|epo-inv:Invoice → epo-inv:Payee [0..1]

  

  
  
| epo:specifiesSeller| 
  Relation indicating that the instance of the concept involves the Seller.|epo-inv:Invoice → epo-ord:Seller [1]

  

  
  
| epo-inv:specifiesSellerTaxRepresentative| 
  Relation indicating that the instance of the concept involves the Seller Tax Representative.|epo-inv:Invoice → epo-inv:SellerTaxRepresentative [0..1]

  

  
  
| epo-inv:hasInvoiceLineObjectIdentifier| 
  An identifier for an object on which the invoice line is based, given by the Seller. Additional Information: It may be a subscription number, telephone number, meter point etc., as applicable.|epo-inv:InvoiceLine → adms:Identifier [0..1]

  

  
  
| epo-inv:hasInvoiceLinePeriod| 
  Relation indicating the time range of the Invoice Line.|epo-inv:InvoiceLine → time:Interval [0..1]

  

  
  
| epo-inv:hasNetAmount| 
  Relation indicating the Monetary Value exclusive of taxes and after substracting price discounts.|epo-inv:InvoiceLine → epo:MonetaryValue [1]

  

  
  
| epo-cat:hasPrice| 
  Relation indicating that the instance of the concept has a Price.|epo-inv:InvoiceLine → epo-cat:Price [1..&#42;]

  

  
  
| epo-cat:hasQuantity| 
  Relation indicating that the instance of the concept has a Quantity.|epo-inv:InvoiceLine → epo:Quantity [1]

  

  
  
| epo-inv:refersToOrderLine| 
  Reference to an Order Line.|epo-inv:InvoiceLine → epo-ord:OrderLine [0..1]

  

  
  
  

  
  
| epo-inv:hasInvoiceNoteSubject| 
  Relation indicating the Invoice Note Subject Code.|epo-inv:InvoiceNote → at-voc-new:invoice-note-subject-code [0..1]

  

  
  
  

  
  
  

  
  
| epo-inv:hasBankingIdentifier| 
  An unique banking reference identifier of the Payee or Seller, assigned by the Payee or Seller bank.|epo-inv:PaymentInstructionsInformation → adms:Identifier [0..1]

  

  
  
| epo-inv:hasCreditTransferInformation| 
  Relation indicating the Credit Transfer Information.|epo-inv:PaymentInstructionsInformation → epo-inv:CreditTransferInformation [0..&#42;]

  

  
  
| epo-inv:hasDebitedAccountIdentifier| 
  An identifier for the account to be debited by the direct debit.|epo-inv:PaymentInstructionsInformation → adms:Identifier [0..1]

  

  
  
| epo-inv:hasMandateIdentifier| 
  An unique identifier for referencing the direct debit mandate, assigned by the Payee.|epo-inv:PaymentInstructionsInformation → adms:Identifier [0..1]

  

  
  
| epo-inv:hasPaymentCardInformation| 
  Relation indicating the Payment Card Information.|epo-inv:PaymentInstructionsInformation → epo-inv:PaymentCardInformation [0..1]

  

  
  
  

  
  
| epo-inv:hasPaymentMeansType| 
  The means for how a payment is expected to be or has been settled, expressed as code.|epo-inv:PaymentInstructionsInformation → at-voc-new:payment-means-type [1]

  

  
  
  

  
  
| epo-inv:hasTaxExemptionReason| 
  An explanation on why the amount is exempted from tax or why no tax is being charged according to the legislation, expressed as a code.|epo-inv:TaxBreakdownInformation → at-voc-new:tax-exemption-reason [0..1]

  

  
  
  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].