



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-pay:PaymentInformation | Information about a remittance.
      
    
      
| epo-pay:RemittanceAdvice | Document sent by the Buyer to the Seller, informing about the payment made.
      
    
      
| epo-pay:RemittanceAdviceLine | Details concerning a given Invoice from the Remittance Advice.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
| epo-pay:PaymentInformation
| epo-pay:hasPaymentDate| 
  The date of the Payment.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
| epo-pay:RemittanceAdvice
| epo-pay:hasPayerReference| 
  Reference to the Payer.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-pay:RemittanceAdvice
| epo-pay:hasPaymentOrderReference| 
  Reference to the Payment Order.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
  

  
  
| epo-pay:hasPaymentIdentifier| 
  Relation indicating the Identifier of the Payment.|epo-pay:PaymentInformation → adms:Identifier [0..1]

  

  
  
| epo-pay:hasPaymentMeansInformation| 
  Relation indicating the Payment Instruction Information.|epo-pay:PaymentInformation → epo-inv:PaymentInstructionsInformation [1]

  

  
  
| epo-pay:comprisesRemittanceAdviceLine| 
  Incorporates Remittance Advice Line.|epo-pay:RemittanceAdvice → epo-pay:RemittanceAdviceLine [1..&#42;]

  

  
  
  

  
  
| epo-pay:hasPaymentInformation| 
  Relation indicating the Payment Information.|epo-pay:RemittanceAdvice → epo-pay:PaymentInformation [0..1]

  

  
  
  

  
  
| epo-pay:hasTotalCreditAmount| 
  Relation indicating the overall Monetary Value that reduces the amount owed.|epo-pay:RemittanceAdvice → epo:MonetaryValue [0..1]

  

  
  
| epo-pay:hasTotalDebitAmount| 
  Relation indicating the overall Monetary Value that increases the amount owed.|epo-pay:RemittanceAdvice → epo:MonetaryValue [0..1]

  

  
  
| epo-pay:hasTotalPaymentAmount| 
  Relation indicating the overall paid Monetary Value.|epo-pay:RemittanceAdvice → epo:MonetaryValue [0..1]

  

  
  
| epo:specifiesBuyer| 
  Relation indicating that the instance of the concept involves the Buyer.|epo-pay:RemittanceAdvice → epo:Buyer [1]

  

  
  
| epo-inv:specifiesPayee| 
  Relation indicating that the instance of the concept involves the Payee.|epo-pay:RemittanceAdvice → epo-inv:Payee [0..1]

  

  
  
| epo:specifiesSeller| 
  Relation indicating that the instance of the concept involves the Seller.|epo-pay:RemittanceAdvice → epo-ord:Seller [1]

  

  
  
| epo-pay:hasBalanceAmount| 
  Relation indicating the outstanding amount that remains unpaid or unsettled.|epo-pay:RemittanceAdviceLine → epo:MonetaryValue [0..1]

  

  
  
| epo-pay:hasCreditAmount| 
  Relation indicating the Monetary Value that reduces the amount owed.|epo-pay:RemittanceAdviceLine → epo:MonetaryValue [0..1]

  

  
  
| epo-pay:hasDebitAmount| 
  Relation indicating the Monetary Value that increases the amount owed.|epo-pay:RemittanceAdviceLine → epo:MonetaryValue [0..1]

  

  
  
| epo-inv:refersToInvoice| 
  Reference to an Invoice.|epo-pay:RemittanceAdviceLine → epo-inv:Invoice [0..1]

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].