



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-sub:DocumentaryEvidence | An Evidence submitted by an Economic Operator to prove compliance with legal, technical or financial requirements, or inapplicability of exclusion grounds in a Procurement Procedure.
      
    
      
| epo-sub:ESPD | A self-declaration of an economic operator, stating that it does not fall under the Exclusion Grounds and that it meets the Selection Criteria for a specific procurement.
      
    
      
| epo-sub:EvidenceInformation | Information about a Certificate.
      
    
      
| epo-sub:LegalRepresentative | The Role of an Agent that can represent an Organization.
      
    
      
| epo-sub:Mandate | An authorization to act as a representative of an Organization.
      
    
      
| epo-sub:OrganisationInformationSummary | Information about the specific features or characteristics that qualify an economic operator to take part in a tendering process.
      
    
      
| epo-sub:PowerOfAttorney | A legal document that grants someone the authority to make decisions on behalf of an Organization.
      
    
      
| epo-sub:Response | An answer given to a question that is part of an ESPD Request.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
  
  
  
  
| epo-sub:EvidenceInformation
| epo-sub:coversAllSelectionCriteria| 
  Indicator that the Certificate proves whether the Organization fulfils all Selection Criteria.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-sub:OrganisationInformationSummary
| epo-sub:hasBusinessClassificationDescription| 
  Explanatory text about the size of the Business. Additional information: The values of this property may come from the recommended codelist: http://publications.europa.eu/resource/authority/economic-operator-size|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo-sub:OrganisationInformationSummary
| epo-sub:providesOrganisationCompletedTaskDescription| 
  Text describing the works, supplies or services executed, delivered or performed in a procurement project that can be used as an evidence for the classification of the Organization.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
| epo-sub:isContainedInTender| 
  Relation indicating that the instance of the concept is part of a Tender.|epo-sub:ESPD → epo:Tender [0..&#42;]

  

  
  
| epo-sub:providesInformationOn| 
  Offers information about an instance of a concept.|epo-sub:ESPD → org:Organization [0..&#42;]

  

  
  
| epo-sub:relatesToESPDRequest| 
  Is about an European Single Procurement Document (ESPD) Request.|epo-sub:ESPD → epo-acc:ESPDRequest [0..1]

  

  
  
| epo-sub:specifiesResponse| 
  Relation indicating that an ESPD Response contains a Response.|epo-sub:ESPD → epo-sub:Response [1..&#42;]

  

  
  
  

  

  
  
| epo-sub:summarisesInformationAboutEvidence| 
  Relation indicating the Certificate that the information refers to.|epo-sub:EvidenceInformation → cccev:Evidence [1]

  

  
  
| epo:actsOnBehalfOf| 
  |epo-sub:LegalRepresentative → epo:OfferingParty [0..1]

  

  
  
| epo-sub:hasMandate| 
  Relation indicating that a Legal Representative has a Mandate.|epo-sub:LegalRepresentative → epo-sub:Mandate [0..&#42;]

  

  
  
| epo-sub:hasPowerOfAttorney| 
  Relation indicating that a Legal Representative has a Power of Attorney.|epo-sub:LegalRepresentative → epo-sub:PowerOfAttorney [0..1]

  

  
  
| epo-sub:concernsOrganisation| 
  Relates to Organization.|epo-sub:OrganisationInformationSummary → org:Organization [1]

  

  
  
  

  
  
  

  
  
| epo-sub:providesOrganisationEmployeeQuantity| 
  The number of people hired by the Organization.|epo-sub:OrganisationInformationSummary → epo:Quantity [0..1]

  

  
  
| epo-sub:providesOrganisationFinancialCapability| 
  A monetary amount representing the financial capability of the Organization. Additional information: Used to represent the general Turnover of the Organization (for statistical purposes).|epo-sub:OrganisationInformationSummary → epo:MonetaryValue [0..1]

  

  
  
| epo-sub:answersQuestion| 
  Relation indicating that the Response replies to a question.|epo-sub:Response → cccev:InformationRequirement [0..&#42;]

  

  

  
  
| epo-sub:isReinforcedBy| 
  Relation indicating an Evidence that supports the Response.|epo-sub:Response → cccev:Evidence [0..&#42;]

  

  
  
| epo-sub:refersToApplicablePeriod| 
  Relation indicating the period to which the Response shall apply.|epo-sub:Response → time:Interval [0..1]

  

  

  

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].