



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo:AccessTerm | Conditions and stipulations about where and how to access the Procurement Documents.
      
    
      
| epo:AcquiringCentralPurchasingBody | Role of an Agent procuring activities conducted on a permanent basis in the form of the acquisition of supplies and/or services intended for other Buyers. Additional Information: In Public Procurement the Role of Acquiring Central Purchasing Body is carried out by a Central Purchasing Body for other Contracting Authorities.
      
    
      
| epo:AcquiringParty | The Role of an Agent that acts on the buying side of a Procurement Process.
      
    
      
| epo:AdHocChannel | Web page where tools and devices for electronic communication that are not generally available can be downloaded free of charge.
      
    
      
| epo:AgentInRole | Relative concept that ties an Agent to a part they play in a given Situational Context. Additional information: The classification of roles is based is based on the degree of involvement into the Procurement Process: - Primary (Procurement) Pole is directly involved in the Procurement Process; - Secondary (Procurement sub-) Role is secondary to the Procurement Process - Tertiary (Related) Role is not involved in the Procurement Process.
      
    
      
| epo-ord:AllowanceChargeInformation | Information about discounts, taxes, duties and fees imposed.
      
    
      
| epo-ord:AllowanceInformation | Information about the discounts imposed.
      
    
      
| epo:Asset | Resource necessary for the provision of a service.
      
    
      
| epo:AuxiliaryParty | Role of an Agent who may be mentioned in the information exchanged during the Procurement Process but who does not play an active part in it.
      
    
      
| epo:AwardCriteriaSummary | Overview of the Award Criteria.
      
    
      
| epo:AwardCriterion | Criterion that describes a Requirement that the Tender needs to resolve and on which the Tender is evaluated and ranked.
      
    
      
| epo:AwardDecision | Resolution of the Buyer as to the result of the Procurement Procedure.
      
    
      
| epo:AwardEvaluationTerm | Conditions and stipulations defining particularities of the evaluation of Award Criteria.
      
    
      
| epo:AwardOutcome | Result concerning the competition that was attributed by the Awarder.
      
    
      
| epo:Awarder | A Role of an Agent that signs the Award Decision. Additional information: BT-08 can be Awarding CBP; BG-03 is the Buyer. But Awarding CPB is not the same as the Buyer; the organisations may differ for these roles. Having the Awarder Role allows us to specify which Organisation is involved in the Award Decision.
      
    
      
| epo:AwardingCentralPurchasingBody | Role of an Agent procuring activities conducted on a permanent basis in the form of the award of Public Contracts or the conclusion of Framework Agreements for works, supplies or services intended for other Buyers. Additional Information: In Public Procurement the Role of Awarding Central purchasing Body is carried out by a Central Purchasing Body for other Contracting Authorities.
      
    
      
| epo:BudgetProvider | A role of an agent whose Budget is used to pay for the Contract.
      
    
      
| epo:Business | A private law company registered in a national registry.
      
    
      
| epo:Buyer | A Role of an Agent that awards a Contract and/or purchases items. Additional information: In Public Procurement the Role of Buyer is carried out by the following types of Organisation: Contracting Authority, Contracting Entity, a defense Contractor, an international Organisation, or an organisation awarding a Contract subsidized by a Contracting Authority. In Pre-Award, the Buyer generally awards the Contract, however future purchasers may be foreseen. In Post-Award the buyer generally refers to the purchaser of items.
      
    
      
| epo:Candidate | The Role of an Agent that has sought an invitation or has been invited to take part in a restricted Procedure, in a competitive Procedure with negotiation, in a negotiated Procedure without prior publication, in a competitive dialogue or in an innovation partnership.
      
    
      
| epo:CatalogueProvider | A Role of an Agent compiling and supplying a Catalogue. Additional Information: The Catalogue Provider Role is usually played by the Agent that acts as a Seller, or by another Agent that acts on behalf of the Seller.
      
    
      
| epo:CatalogueReceiver | A Role of an Agent processing a Catalogue. Additional Information: The Catalogue Receiver may not only receive it but also validate it, process it, etc. The Catalogue Receiver role is usually played by the agent that acts as a Buyer, or by another Agent that acts on behalf of the Buyer.
      
    
      
| epo:CentralPurchasingBody | Role of an Agent that provides centralised purchasing activities and, possibly, ancillary purchasing activities for other Buyers. Additional Information: In Public Procurement the Role of Central Purchasing Body is carried out by a Contracting Authority for other Contracting Authorities. Contracting Authority procuring activities conducted on a permanent basis, in one of the following forms:[...](b) the award of Public Contracts or the conclusion of Framework Agreements for works, supplies or services intended for Contracting Authorities;
      
    
      
| epo:Certificate | Proof of conformance of the instance of the concept to a defined set of criteria. Additional Information: Certificates provide assurance of credibility, trust, and transparency in the procurement process.
      
    
      
| epo:CertificationLabel | Concept that stands for a set of norms, expectations, standards and policies. Additional Information: Such standards may relate to social, ethical and quality etc.
      
    
      
| epo:Certifier | The role of an agent who issues a certificate. Additional Information: The certifier is responsible for verifying and confirming the conformance of the instance of the concept to a defined set of criteria.
      
    
      
| epo:ChangeInformation | Alteration to previously provided details.
      
    
      
| epo:CleanVehicleDirectiveInformation | Information related to clean vehicles legislation. Additional information: In the European Union, the legislation concerned is the European Parliament and Council 2009/33/EC (Clean Vehicles Directive – CVD).
      
    
      
| epo:ConcessionContract | A Contract between one or more Buyers and one or more Economic Operators giving the right to the Economic Operators to exploit the rights foreseen in the Contract which may include the receipt of Payments.
      
    
      
| epo:ConcessionEstimate | Approximation concerning the foreseen Concession Contract.
      
    
      
| epo-ord:Consignee | A Role of an Agent that receives the Shipment of the Procurement (service, goods or works) and who is taking possession. Additional information: The Role is carried out by the Customer or on behalf of the Customer. The possession of the goods does not necessary imply ownership. The Consignee may be the end-user or the beneficiary. (Consignee) Definition from PEPPOL Despatch: The Consignee is the person or Organisation to which the products will be shipped and who is taking possession. The Role is carried out by the Customer or on behalf of the Customer.
      
    
      
| epo:ContextDescription | A description concerning a Procurement Object or a Notice in a specific Situation Context. Additional Information: The description has its own identity (+I) but is dependent (+D) on the concerned Entity. We say that ContextDescription *concerns* an Entity.
      
    
      
| epo:ContextualProjection | Projection of an Entity and all of its properties that hold in a given Situation Context. Additional Information: The contextual projection does not have its own identity (-I), is dependent (+D) on the described Entity, and is anti-rigid (~R) We say that ContextualProjection *describes* an Entity. Adaptation of ContextSlices pattern encoding a 4D view. http://ontologydesignpatterns.org/wiki/Submissions:Context_Slices
      
    
      
| epo:Contract | A voluntary, deliberate, and legally binding agreement between two or more competent parties.
      
    
      
| epo-ord:ContractInformation | Information about the Contract.
      
    
      
| epo:ContractLotCompletionInformation | Information related to a given Lot at the end of the procurement.
      
    
      
| epo:ContractTerm | Conditions and stipulations defining particularities of the Post Award Phase.
      
    
      
| epo:Contractor | The Role of an Agent that has signed a Contract with a Buyer.
      
    
      
| epo-ord:DeliveryAgreement | Term applying to the delivery of goods, services and works. Additional Information: Delivery terms identifier can normally be Incoterms accompanied by the description of specific conditions related to the delivery.
      
    
      
| epo-ord:DeliveryInformation | Information about the timing, the delivery destination, the delivery agreement and the involved parties.
      
    
      
| epo:DesignContestRegimeTerm | Conditions and stipulations defining particularities of a Design Contest.
      
    
      
| epo:DirectAwardTerm | Conditions and stipulations defining particularities of the award of a Contract without prior publication. Addtional Information: Direct award may refer to a previous Procedure and/or specific Lot(s). It may also refer to other justified situations whereby there is no previous Procedure. See Directive 2014/24/EU Article 32.
      
    
      
| epo:DirectContract | A Contract resulting from Lot Award Outcome. Additional information: A Framework Agreement is not a Direct Contract.
      
    
      
| epo:Document | A set of interrelated Business Information representing the Business facts and associated metadata. The information may be conveyed in any language, medium or form, including textual, numerical, graphic, cartographic, audio-visual forms, etc.
      
    
      
| epo:Documentation | A structured collection of records, reports, or supporting materials that provide context or explanation regarding a process, requirement, or decision within a procurement activity.
      
    
      
| epo:DynamicPurchaseSystemTechnique | A Technique that allows the selection of Candidates throughout the Procedure via the Qualification Criteria, followed by individual Mini-Competitions for the Award of Purchase Contracts.
      
    
      
| epo:EAuctionTechnique | A repetitive Technique in which new Prices, revised downwards, and/or new values concerning certain elements of Tenders are bid on-line.
      
    
      
| epo:EconomicStandingSummary | Overview of the financial viability of the economic operator.
      
    
      
| epo:ElectronicSignature | Data in electronic form which is attached to or logically associated with other data in electronic form and which is used by the signatory to sign. Additional information: The definition comes from REGULATION (EU) No 910/2014.
      
    
      
| epo:EmploymentDocumentation | Documentation concerning the general regulatory framework for employment protection and working conditions.
      
    
      
| epo:EmploymentInformationProvider | A Role of an Agent responsible for providing information concerning the general regulatory framework for employment protection and working conditions applicable in the place where the contract is to be performed.
      
    
      
| epo:EnergyEfficiencyInformation | Information about the energy performance, consumption, or sustainability characteristics of a product, service, building, or process relevant to the execution or evaluation of a procurement procedure.
      
    
      
| epo:EnvironmentalDocumentation | Documentation concerning the general regulatory framework for Environmental Protection.
      
    
      
| epo:EnvironmentalProtectionInformationProvider | A Role of an Agent responsible for providing information concerning the general regulatory framework for Environmental Protection applicable in the place where the contract is to be performed.
      
    
      
| epo:Estimate | An approximate calculation or a judgement of the value, number, Quantity or extent of something.
      
    
      
| epo:EvaluationTerm | Conditions and stipulations defining particularities of the Tender evaluation.
      
    
      
| epo:ExclusionGround | Criterion that describes a legal Requirement to be met by the Economic Operator to be a Candidate in the Procurement.
      
    
      
| epo:ExclusionGroundsSummary | Overview of the Exclusion Grounds.
      
    
      
| epo:ExpressionOfInterest | Document presenting an Economic Operator's Request to be considered for Procedures covering a specific domain.
      
    
      
| epo:FrameworkAgreement | An agreement between one or more Contracting Authorities and one or more Economic Operators. Additional Information: When a Framework Agreement is concerned, the FA will result from LotAwardOutcome which describes a Lot which specifies the both the Qualification and Award Criteria.
      
    
      
| epo:FrameworkAgreementTechnique | Technique that establishes the terms governing Contracts to be awarded during a given Period, in particular with regard to Price and, where appropriate, the Quantity envisaged.
      
    
      
| epo:FrameworkAgreementTerm | Conditions and stipulations defining particularities in a Framework Agreement.
      
    
      
| epo:Fund | A financial resource used to support the Procurement. Additional Information: In the context of EU, Funds can be divided into programmes, actions and projects. Examples of EU funds are: the European Structural and Investment Funds, European Social Fund (ESF), the Connecting Europe Facility (CEF) programme, or the ISA2 programme and its actions (e.g. Action 2016.05 European Public Procurement Initiative, which supports the eProcurement Ontology under sub-action 3). Funds may change between the lot and the contract, for example in the case of an emergency crisis, a contract may be financed by a budget that was not foreseen in the call.
      
    
      
| epo:GreenProcurement | Approach whereby Buyers seek to procure with a reduced Environmental Impact. Additional Information: The approach may apply to the complete life cycle. The reduced Environmental Impact is in comparison to goods, services and works with the same primary function that would otherwise be procured. Tightly related are article 68 - Life-cycle costing and article 67 - most economically advantageous Tender (see GPP handbook) https://ec.europa.eu/environment/gpp/pdf/Buying-Green-Handbook-3rd-Edition.pdf An instance of the class GreenProcurement is represented in eForms with the code "env-imp" defined in the codelist Strategic-Procurement.Paragraphs) https://ec.europa.eu/environment/gpp/pdf/Buying-Green-Handbook-3rd-Edition.pdf
      
    
      
| epo:InnovativeProcurement | Approach whereby Buyers seek to procure an innovative work, supply or service. Additional Information: ‘innovation’ means the implementation of a new or significantly improved product, service or process, including but not limited to production, building or construction processes, a new marketing method, or a new organizational method in business practices, workplace Organisation or external relations inter alia with the purpose of helping to solve societal challenges or to support the Europe 2020 strategy for smart, sustainable and inclusive growth; See: Directive 2014/24 Articles: 2, 26 (3), 31, 67 (2.a)
      
    
      
| epo:InternationalProcurementInstrumentMeasuresInformation | Information about the legislative framework adopted by the European Union to promote reciprocity in international public procurement markets.
      
    
      
| epo-ord:Invoicee | The Role of an Agent who receives and processes the Invoices.
      
    
      
| epo:JuryMember | Role of an Agent who evaluates a design contest.
      
    
      
| epo:LeadBuyer | A Role of an Agent who is a Buyer and takes the administrative lead of the Procedure.
      
    
      
| epo:LocalLegalBasisInformation | Information about the legal basis at the level of the Member State.
      
    
      
| epo:Lot | A qualitative, quantitative or strategic subdivision of the goods, services or works to be procured, allowing the award of one or more Contracts.
      
    
      
| epo:LotAwardOutcome | Result concerning the Lot that was attributed by the Awarder.
      
    
      
| epo:LotGroup | Combination of several Lots to conduct comparative assessment of the Tenders. Additional Information: The comparative assessment may refer to the Selection Criteria, Award and Value that apply to several Lots. Pending of discussion with eForms Member States may provide that, where more than one lot may be awarded to the same tenderer, contracting authorities may award contracts combining several or all lots where they have specified in the contract notice or in the invitation to confirm interest that they reserve the possibility of doing so and indicate the lots or groups of lots that may be combined.
      
    
      
| epo:LotGroupAwardInformation | Award information related to a given Group of Lots.
      
    
      
| epo:MaskableObject | Entity within the procurement data model whose visibility, accessibility, or disclosure may be conditionally restricted due to legal, confidentiality, or security requirements.
      
    
      
| epo:Mediator | A Role of an Agent that attempts to resolve a dispute between different Agents and come to an agreement.
      
    
      
| epo:MiniCompetitionAwardOutcome | Result concerning the mini-competition that was attributed by the Awarder. Additional Information: The mini-competition is the process where multiple winners or candidates of previous stages of a procedure bid for a specific procurement. It is typically used in framework agreements where the suppliers have already been pre-selected, and the mini competition is used to determine which supplier is best suited for a particular project or contract. It is also used in a Dynamic Purchasing System where the suppliers come from a list of Candidates.
      
    
      
| epo:MonetaryValue | A number of monetary units specified using a given unit of currency. Additional information: In the pre-award phase of the procurement, all monetary values are considered to exclude VAT based on the Directive 2014/24/EU.
      
    
      
| epo:MultipleStageProcedureTerm | Conditions and stipulations defining particularities of Procedures carried out in several steps Additional Information: Generally this refers to Procedures where selection is carried out to qualify Tenderers who are then requested to submit the rest of their Tender for evaluation is Restricted Procedure.
      
    
      
| epo:NonDisclosureAgreementTerm | Conditions and stipulations about a non-disclosure agreement. Additional information: A non-disclosure agreement is a Contract between different parties which ensures information is not shared with other parties.
      
    
      
| epo:NonPublishedInformation | Information about fields not published in this Notice. Additional Information: The non-published information may become available at a later date and may differ from one element to another within a given Document. Examples of fields that may not be immediately published are Winner, Tender and Procedure Lot Result, etc., e.g. for security reasons.
      
    
      
| epo:Notice | Document published by the Buyer about market opportunities and results.
      
    
      
| epo:NoticeAwardInformation | Information about an Award Notice.
      
    
      
| epo:Offer | Document providing the Monetary Value and the details to fulfill the Requirements set out in the Procurement Documents or Request for Offer. Additional information: A quotation is considered to be an Offer in the eProcurement Ontology.
      
    
      
| epo:OfferIssuer | The Role of an Agent that distributes an Offer.
      
    
      
| epo:OfferingParty | The Role of an Agent that acts on the Economic Operator side during a Procurement Process. Additional information: As per the European Procurement Directives the notion of ‘Economic Operators’ should be interpreted in a broad manner so as to include any Persons and/or Entities which offer the execution of works, the supply of products or the provision of services on the market, irrespective of the legal form under which they have chosen to operate. Thus, firms, branches, subsidiaries, partnerships, cooperative societies, limited companies, universities, public or private, and other forms of entities than natural Persons should all fall within the notion of Economic Operator, whether or not they are ‘Legal Persons’ in all circumstances.
      
    
      
| epo:OfflineAccessProvider | A Role of an Agent responsible for providing offline access to the Procurement Documents.
      
    
      
| epo:OpeningTerm | Conditions and stipulations defining particularities of the opening of Tenders. Additional Information: The opening of Tenders is the event when Tenders are made accessible for evaluation, it is generally the same date and time for all Tenders.
      
    
      
| epo-ord:Order | A formal request of the Buyer to the Seller specifying the goods, services or works to be delivered. Additional Information: A Buyer submits an Order for delivery of goods, services or works to a Seller.
      
    
      
| epo-ord:OrderAgreement | A Document sent from the Seller to Buyer specifying the goods, services or works to be delivered concerning a specific Order.
      
    
      
| epo-ord:OrderAgreementLine | Details concerning a given unit of goods, services or works mentioned in the Order Agreement.
      
    
      
| epo-ord:OrderCancellation | A Document providing information on the formal response from the Buyer to the Seller to cancel a previous Order or Order Change.
      
    
      
| epo-ord:OrderCancellationConfirmation | A Document providing information on the acknowledgment of the Order Cancellation.
      
    
      
| epo-ord:OrderCancellationRejection | A Document providing information on the non-acceptance of the Order Cancellation.
      
    
      
| epo-ord:OrderChange | A Document providing information on the formal request from the Buyer to the Seller specifying the requested change in goods, services or works to be delivered in respect to a previous Order.
      
    
      
| epo-ord:OrderChangeConfirmation | A Document providing information on the acknowledgment of the Order Change.
      
    
      
| epo-ord:OrderChangeLine | Details concerning a given unit of goods, services or works requested in the Order Change.
      
    
      
| epo-ord:OrderChangeRejection | A Document providing information on the non-acceptance of the Order Change.
      
    
      
| epo-ord:OrderLine | Details concerning a given unit of goods, services or works requested in the Order. Additional information: In general, an Order Line contains the Quantity and Price of the goods, services and goods requested in the Order. However, in certain cases, the Price may not be known, as the Price may fluctuate from one day to the other.
      
    
      
| epo-ord:OrderResponse | A formal reply from the Seller to the Buyer stating the Seller's ability to fulfil the order. Additional Information: The Order Response is used to inform on the acceptance or rejection of an Order or to make a counter-offer.
      
    
      
| epo-ord:OrderResponseInformation | Information about an Order Response.
      
    
      
| epo-ord:OrderResponseLine | Details concerning the Seller's ability to fulfil a given Order Line. Additional Information: The Order Response Line is used to inform on the acceptance or rejection of an Order Line or to make a counter-offer.
      
    
      
| epo:OrganisationGroup | Agreed collaboration of several Organisations. Additional Information: This concept has been created to fulfill the need to represent a grouping of Organisations that is not necessarily registered i.e, consortia.
      
    
      
| epo-ord:Originator | A Role of an Agent that expresses the needs to trigger the Procurement. Additional Information: The Originator is often the end-user or the Beneficiary.
      
    
      
| epo-ord:OriginatorInformation | Information about the Originator of the Order.
      
    
      
| epo:OriginatorRequest | Document in which the Originator describes his needs.
      
    
      
| epo:ParticipationCondition | Criterion that describes a Requirement to take part in a procurement.
      
    
      
| epo:ParticipationConditionsSummary | Overview of the Participation Conditions.
      
    
      
| epo:ParticipationRequestProcessor | A Role of an Agent responsible for processing Requests To Participate.
      
    
      
| epo:ParticipationRequestReceiver | A Role of an Agent responsible for receiving Requests To Participate.
      
    
      
| epo:ParticipationRequestTerm | Conditions and stipulations defining particularities of requesting participation in a Procedure.
      
    
      
| epo:PaymentExecutor | A Role of an Agent responsible for executing the Payment.
      
    
      
| epo:PlannedProcurement | A high-level description of a procurement activity foreseen by a Buyer.
      
    
      
| epo:PlannedProcurementPart | A subdivision of a Planned Procurement that may later become one or more Lots or a self-standing Procedure. Additional Information: A Lot or a Procedure can also cover one or more parts of the Planned Procurement.
      
    
      
| epo:Prize | A reward given in a Contest.
      
    
      
| epo:Procedure | A legally defined set of administrative activities conducted to conclude one or more Contracts. Additional Information The Procedure is categorised in the law according to different rules determining whether the Procedure is Open, Restricted, Negotiated with or without publicity, etc. (see Procedure Type).
      
    
      
| epo:ProcedureTerm | Conditions and stipulations defining particularities of the Procedure.
      
    
      
| epo:ProcessPlanningTerm | Conditions and stipulations defining particularities of the unfolding of the Procurement Process.
      
    
      
| epo:ProcurementCriteriaSummary | Overview of the Procurement Criteria.
      
    
      
| epo:ProcurementCriterion | A criterion specific to Procurement.
      
    
      
| epo:ProcurementDocument | Document produced or referred to by the Buyer to describe or determine elements of the Procurement. Additional information: Procurement Documents are to be accessible since the date of publication of the Contract Notice or the prior information Notice when used as a call for competition. Examples of Procurement Documents are Technical Specifications, the Descriptive Document, proposed conditions of Contract, formats for the presentation of Documents by Candidates and Tenderers, information on generally applicable obligations. Other Documents related to the Procedure such as Notices are not considered to be Procurement Documents.
      
    
      
| epo:ProcurementElement | Gathering class for critical/central elements in the Procurement Process. TODO: add definition Additional information: Alias: ProcurementComponent
      
    
      
| epo:ProcurementObject | The whole or a division of goods, services or works to be procured. Additional Information: Anything that can specify the procurement content (i.e. goods, services, work) is a Procurement Object. In a sense, such an "object" can constitute the "object of a Contract". To test whether something is a Procedure Object check if it can have a Purpose and/or CPV classification (<i>The CPV establishes a single classification system for public procurement aimed at standardising the references used by Contracting Authorities and entities to describe the subject of Procurement Contracts.</i>). Note: Procedure, seems to be an exception from this rule. Because it is a conflated term: it carries process properties and "purpose" properties.
      
    
      
| epo:ProcurementProcedureInformationProvider | A Role of an Agent responsible for providing additional information about the Procurement Procedure.
      
    
      
| epo:ProcurementProcessInformation | Information about the temporal unfolding or succession of Procurement Objects.
      
    
      
| epo:ProcurementServiceProvider | Role of a public or private body which offers ancillary purchasing activities on the market. Additional information: "Ancillary Purchasing Activities" means activities consisting in the provision of support to purchasing activities, in particular in the following forms: (a) technical infrastructure enabling Contracting Authorities to award Public Contracts or to conclude Framework Agreements for works, supplies or services; (b) advice on the conduct or design of public Procurement Procedures; (c) preparation and management of Procurement Procedures on behalf and for the account of the Contracting Authority concerned; This would be equivalent to the concept of 'ProcuringEntity' in OCDS: 'The Entity managing the Procurement, which may be different from the Buyer who is paying / using the items being procured'.
      
    
      
| epo:ProfessionalSuitabilitySummary | Overview of the professional ability required for the economic operator to execute the contract.
      
    
      
| epo:Project | A collaborative enterprise that is carefully planned to achieve a particular aim.
      
    
      
| epo:PurchaseContract | A Contract resulting from using a Dynamic Purchasing System Technique or Framework Agreement Technique.
      
    
      
| epo:Purpose | The description of the objectives related to a Procurement. Additional information: The description of the objectives includes the Subject Matter and Quantities. The quantification of the objectives related to a procurement. To be re-reviewed by the WG the soonest. (WG to be discussed, this was pointed out on the 09/04/2019 14:38:25 WG Meeting) The old definition read as follows: The description of the objectives related to a procurement.
      
    
      
| epo:QualificationCriteriaSummary | Overview of the Qualification Criteria.
      
    
      
| epo:QualificationCriterion | Criterion used in the first stage of procurement.
      
    
      
| epo:QualityTargetInformation | Information about a specific performance goal.
      
    
      
| epo:Quantity | A counted number of non-monetary units possibly including fractions.
      
    
      
| epo:ReliedUponEntity | Economic Operator (who is not a Subcontractor) on which the Tenderer relies upon, to meet Selection Criteria.
      
    
      
| epo:ReviewDecision | Information about Review Decisions.
      
    
      
| epo:ReviewIrregularitySummary | Overview of the number and type of requests the Buyer received to review any of its decisions (e.g. the Technical Specifications, Award Decision).
      
    
      
| epo:ReviewProcedureInformationProvider | A Role of an Agent who is providing more information on the time limits for review Procedures.
      
    
      
| epo:ReviewRequest | Information about requests to review procedures.
      
    
      
| epo:ReviewRequestSummary | Overview of the requests received by the Buyer to review any of its decisions (e.g. the technical specifications, award decision), as set out in Art. 1(5) of Directive 89/665/EEC and Directive 92/13/EEC, and about the complainants that submitted the requests.
      
    
      
| epo:ReviewRequester | Role of an Agent who requests the review of a (Procurement) Procedure.
      
    
      
| epo:ReviewTerm | Conditions and stipulations defining particularities of the review.
      
    
      
| epo:Reviewer | Role of an Agent who investigates the overall correctness of a Procurement Procedure, producing a related report. Additional Information: Any Organisation or Person may request a review of a Procurement Procedure.
      
    
      
| epo:SecurityClearanceTerm | Conditions and stipulations about the status requested of individuals allowing them access to classified information (state or organisational secrets) or to restricted areas, after completion of a thorough background check.
      
    
      
| epo:SelectedCandidateList | Record of Candidates admitted to take part in award phases of procurements.
      
    
      
| epo:SelectionCriteriaSummary | Overview of the Selection Criteria.
      
    
      
| epo:SelectionCriterion | Criterion that describes a capacity Requirement that the Economic Operator needs to fulfill to participate in the procurement. Additional Information: Selection criteria may relate to: (a) suitability to pursue the professional activity; (b) economic and financial standing; (c) technical and professional ability
      
    
      
| epo:SelectionEvaluationTerm | Conditions and stipulations defining particularities of the evaluation of Selection Criteria.
      
    
      
| epo-ord:Seller | A Role of an Agent who transfers the ownership of the Procurement results (goods, services or works) to the Buyer. Additional information: A Role of an Agent that sells a Procurement Result (goods, services or work) to a Buyer. The Seller is bound by a Contract i.e. it has legal responsibility. The Seller may or may not be the same as the Supplier. The Seller may or may not issue the Invoice. The Seller may or may not be the owner of the credit owed by the Buyer.
      
    
      
| epo:SocialProcurement | Approach whereby Buyers seek to procure by fulfilling social objectives. Additional Information: Socially Responsible Public Procurement (SRPP) - ‘SRPP’ means Procurement Operations that take into account one or more of the following social considerations: employment opportunities, decent work, compliance with social and labour rights, social inclusion (including persons with disabilities), equal opportunities, accessibility design for all, taking account of sustainability criteria, including ethical trade issues and wider voluntary compliance with corporate social responsibility (CSR), while observing the principles enshrined in the Treaty for the European Union (TFEU) and the Procurement Directives. See Article 18 and Annex X Directive 2014/24.
      
    
      
| epo:SpecificationInformation | Information about the characteristics and standards used in a technical implementation.
      
    
      
| epo:StatisticalInformation | Statistical data on the Procedure and the Lot. Additional Information At the present time Procurement Procedures are not fully electronic. At a later date, information on the Tenders received could be inferred by the data in the eProcurement System. Therefore this class is temporal and should cease to exist in fully electronic Procurement. The need for its presence responds also to the alignment with the Regulation (EU) 2019/1780 (eForms). Attention will have to be paid in the future to possible inconsistencies derived from data placed in other classes and data held in the Statistical Information class; e.g. the TenderEvaluation class (see eEvaluation diagram) has the attribute admissibileTender indicator, which in case of being false, may enter in contradiction with the highest or lowest Tender value for that very same inadmissible Tender.
      
    
      
| epo:StrategicProcurement | Public Procurement that contributes to achieving pressing policy goals. Additional Information: Specific strategic goals could be, for example, Environmental Protection, innovation, job creation and the development of small and medium enterprises. The subclasses are given by the choices in BT-06 Strategic Procurement. Based on https://legalinstruments.oecd.org/en/instruments/OECD-LEGAL-0411 (see paragraph on "background information".
      
    
      
| epo:SubcontractTerm | A concept to describe the main information regarding the share of parts of the Contract to third parties.
      
    
      
| epo:SubcontractingEstimate | Approximation concerning the foreseen Subcontracting.
      
    
      
| epo:Subcontractor | A Role of an Agent that has an agreement to perform part or all of the obligations of another Agents's Contract. Additional information For some Procedures, the Subcontractor signs as well the Contract between the Buyer and the Contractor. At tendering time, entities relied upon by the Economic Operators can be Subcontractors or not. When modelling ESPD we will analyze whether we need or not a Role named "relied upon".
      
    
      
| epo:SubmissionStatisticalInformation | Statistical information about submissions on a given competition, either at Lot level or Mini-Competition level.
      
    
      
| epo:SubmissionTerm | Conditions and stipulations defining particularities of submitting Documents to the Buyer. Additional Information: These Documents can be Tenders, Request To Participate and expressions of interest.
      
    
      
| epo:System | Software application used for performing Procurement activities.
      
    
      
| epo:TaxDocumentation | Documentation concerning the general regulatory framework for taxes.
      
    
      
| epo-ord:TaxInformation | Information about the imposition of mandatory levies required by law.
      
    
      
| epo:TaxInformationProvider | A Role of an Agent responsible for providing information concerning the general regulatory framework for taxes applicable in the place where the contract is to be performed.
      
    
      
| epo:TechnicalAbilitySummary | Overview of the expertise required for the economic operator to execute the contract.
      
    
      
| epo:TechnicalSpecification | A set of documented Requirements applicable to the object of the Procurement. Additional Information: A specification often includes technical standards.
      
    
      
| epo:Technique | Method used for conducting Procurement Procedures. Several Techniques can be combined in one single Procurement Procedure (e.g. eAuction can be carried out in a Framework Agreement or DPS).
      
    
      
| epo:Tender | Information submitted by the Economic Operator to specify its Offer regarding a specific Lot, in response to the call for Tender.
      
    
      
| epo:TenderAwardOutcome | Result concerning the Tender attributed by the Awarder.
      
    
      
| epo:TenderGroup | Specific Offer in response to a Lot Group. Additional Information: This class is generally used to provide the Monetary Value in response to a Lot Group.
      
    
      
| epo:TenderProcessor | A Role of an Agent responsible for processing Tenders.
      
    
      
| epo:TenderReceiver | A Role of an Agent responsible for receiving Tenders.
      
    
      
| epo:Tenderer | A Role of an Agent that has submitted a Tender. Additional Information: A Tenderer is an Economic Operator or group of Economic Operators that has submitted a Tender.
      
    
      
| epo:Term | A governing condition or stipulation.
      
    
      
| epo:UniqueResponsibleOfTheProcurement | A Role of an Agent that holds sole responsibility for initiating, managing, and executing a procurement procedure.
      
    
      
| epo:Winner | A Role of an Agent to whom a Lot is awarded.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
  
  
  
  
  
  
  
  
| epo:AccessTerm
| epo:hasAdditionalInformationDeadline| 
  The time limit for requesting further information. Additional information: This is generally used to indicate the deadline for Economic Operators to request further information of the procedure before the submission deadline.|xsd:dateTime [0..1]
  
  
  
  
  
| epo:AccessTerm
| epo:hasPublicAccessURL| 
  Web page where the procurement documents can be downloaded.|xsd:anyURI [0..1]
  
  
  
| epo:AccessTerm
| epo:hasRestrictedAccessURL| 
  The internet address with information on accessing the restricted (part of the) procurement document.|xsd:anyURI [0..1]
  
  
  
  
  
| epo:AccessTerm
| epo:isProcurementDocumentRestricted| 
  The access to certain procurement documents is restricted.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| foaf:Agent
| epo:hasAlias| 
  Acronym or alternative name of the Agent.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ord:AllowanceChargeInformation
| epo-ord:hasVATExemptionReason| 
  Explanation on why the instance of the concept is not subject to value-added tax.|rdf:PlainLiteral [0..1]
  
  
  
| epo-ord:AllowanceChargeInformation
| epo-ord:hasVATExemptionReasonDescription| 
  Explanatory text about the VAT Exemption Reason.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-ord:AllowanceChargeInformation
| epo-ful:hasAllowanceChargeReasonDescription| 
  Explanatory text about the motive of the Allowance Charge.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo-ord:AllowanceChargeInformation + 
epo-ord:TaxInformation
| epo-cat:hasPercentage| 
  The factor relative to the price charged in addition.|xsd:decimal [0..1] +
  xsd:decimal [0..1]
  
  
  
  
  
  
  
  
  
  
  
| epo:Asset
| epo:hasPredominance| 
  Estimated percentage-share of Assets provided compared to Assets used for activities other than the public services.|rdf:PlainLiteral [0..1]
  
  
  
| epo:Asset
| epo:hasSignificance| 
  Estimated percentage-share of Assets provided in overall Assets used to provide services under Contract.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo:AwardCriterion
| epo:hasAwardCriteriaStatedInProcurementDocuments| 
  The Award Criteria are provided in the Procurement Documents.|xsd:boolean [0..1]
  
  
  
  
  
| epo:AwardCriterion
| epo:hasFixedValue| 
  Constant number.|xsd:decimal [0..1]
  
  
  
  
  
  
  
| epo:AwardDecision
| epo:hasAwardDecisionDate| 
  The official date of the award decision.|xsd:dateTime [0..1]
  
  
  
| epo:AwardEvaluationTerm
| epo:hasAwardCriteriaEvaluationFormula| 
  The mathematical equation or any other description used for complicated weighing of criteria (e.g. non-linear weighing, the analytic hierarchy process) when a weighing cannot be expressed per criterion.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:AwardEvaluationTerm
| epo:hasAwardCriteriaOrderJustification| 
  The justification for only indicating the award criteria's order of importance, not their weighing.|rdf:PlainLiteral [0..1]
  
  
  
| epo:AwardEvaluationTerm
| epo:hasOverallCostAwardCriteriaPonderation| 
  The weighting given to cost. Additional Information: This weighting covers usually all cost criteria against price or quality criteria.|xsd:decimal [0..1]
  
  
  
| epo:AwardEvaluationTerm
| epo:hasOverallPriceAwardCriteriaPonderation| 
  The weighting given to price. Additional Information: This weighting covers usually all price criteria against cost or quality criteria.|xsd:decimal [0..1]
  
  
  
| epo:AwardEvaluationTerm
| epo:hasOverallQualityAwardCriteriaPonderation| 
  The weighting given to quality. Additional Information: This weighting covers usually all quality criteria against price or cost criteria.|xsd:decimal [0..1]
  
  
  
  
  
| epo:AwardOutcome
| epo:hasAwardJustification| 
  Description of the reason behind an award or non-award of a given Tender. Additional information: This is generally used when the non award justification code is set to "Other" and when the Lot is awarded. It may highlight the justification of the non-award of a Tender with regard to awarded Tenders.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:Business
| epo:isListedCompany| 
  Public companies listed on a stock exchange and subject to disclosure requirements (either by stock exchange rules or through law or enforceable means), which impose requirements to ensure adequate transparency of beneficial ownership. <u>Additional Information:</u> In eForms this indicator is used when the nationality of beneficial owner is not provided because the Economic Operator is registered in a regulated market that is subject to disclosure requirements consistent with Union law or subject to equivalent international standards which ensure adequate transparency of ownership information.|xsd:boolean [0..1]
  
  
  
  
  
| epo:Buyer
| epo:hasActivityDescription| 
  In the ePO ontology a taxonomy with all activities, based on different classifications (COFOG, UTILITIES, NACE), will be provided. In ePO this field is to be used exclusively to complement the definition attached to the MainActivityCode. However, in eForms there is the code "other" to cover undefined activities. For mapping to this eForms feature one could also use this property.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:Buyer
| epo:hasBuyerProfile| 
  Website address where the buyer publishes information on its procurement procedures and general information.|xsd:anyURI [0..1]
  
  
  
| epo:Buyer
| epo:isContractingEntity| 
  Role of entities, which: (a) are contracting authorities or public undertakings and which pursue one of the activities referred to in Articles 8 to 14 of the Directive 2014/25/EU. (b) when they are not contracting authorities or public undertakings, have as one of their activities any of the activities referred to in Articles 8 to 14, or any combination thereof and operate on the basis of special or exclusive rights granted by a competent authority of a Member State. Additional Information: The indicator is needed in order to discriminate between those contracts where the Contracting Entity acts as a Contracting Authority undergoing the limits and the rules of Directive 24 and those where it acts as a Contracting Entity, with certain relaxed constraints. For example, the Contracting Entities have different thresholds for the application of Directive 24 if compared with Contracting Authorities.|xsd:boolean [0..1]
  
  
  
  
  
| epo:Certificate
| epo:hasCertificationNumber| 
  The unique identifier of the certificate.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
| epo:CertificationLabel
| epo:hasReferenceURI| 
  A reference to where the label specification (norms, expectations, standards and policies) can be found.|xsd:anyURI [0..1]
  
  
  
  
  
| epo:ChangeInformation + 
epo:Document + 
epo:ProcurementCriterion + 
epo:ProcurementElement
| epo:hasAdditionalInformation| 
  Supplementary data about the instance of the concept.|rdf:PlainLiteral [0..1] +
  rdf:PlainLiteral [0..&#42;] +
  rdf:PlainLiteral [0..1] +
  rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:ChangeInformation
| epo:hasChangeDescription| 
  Explanatory text about the instance of the concept.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo:ChangeInformation
| epo:hasChangeReasonDescription| 
  Explanatory text about why the element is altered.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:ChangeInformation
| epo:hasProcurementDocumentChangeDate| 
  The date and time of the change.|xsd:dateTime [0..1]
  
  
  
| epo:ChangeInformation
| epo:isProcurementDocumentChanged| 
  One or more procurement documents have been changed.|xsd:boolean [0..1]
  
  
  
  
  
  
  
| cv:Channel + 
epo:Documentation
| epo:hasAddressURL| 
  The resource identifier for a Channel.|xsd:anyURI [0..1] +
  xsd:anyURI [0..1]
  
  
  
  
  
  
  
| epo:CleanVehicleDirectiveInformation
| epo:hasCleanVehicles| 
  The number of all clean vehicles that have either been purchased, leased, rented, hired-purchased or their use has been contractually committed to for the provision of a purchased service. Additional Information: In the European Union, the legal requirements and scope for the provision of these vehicles or services are covered by Directive 2009/33/EC.|xsd:integer [0..1]
  
  
  
| epo:CleanVehicleDirectiveInformation
| epo:hasTotalVehicles| 
  The number of all vehicles (regardless of whether clean or not) that have either been purchased, leased, rented, hired-purchased or their use has been contractually committed to for the provision of a purchased service. Additional Information: In the European Union, the legal requirements and scope for the provision of these vehicles or services are covered by Directive 2009/33/EC.|xsd:integer [0..1]
  
  
  
| epo:CleanVehicleDirectiveInformation
| epo:hasZeroEmissionVehicles| 
  The number of all zero-emission heavy-duty vehicles that have either been purchased, leased, rented, hired-purchased or their use has been contractually committed to for the provision of a purchased service. Additional Information: In the European Union, the legal requirements and scope for the provision of these vehicles or services are covered by Directive 2009/33/EC.|xsd:integer [0..1]
  
  
  
  
  
  
  
  
  
| epo:ConcessionEstimate
| epo:hasCalculationMethod| 
  Formula for obtaining values. Additional Information: The possible values are monetary values, ranking scores, criterion weighting.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
| cccev:Constraint
| epo:hasThresholdValue| 
  The cut-off level for a given concept. Additional Information: This value is given as e.g. a minimum score, a maximum number of tenders with the highest score passing (see codelist at-voc:number-threshold).|xsd:decimal [1..1]
  
  
  
  
  
| cpov:ContactPoint
| epo:hasContactName| 
  A short text by which a contact is known or referred to.|rdf:PlainLiteral [0..1]
  
  
  
| cpov:ContactPoint
| epo:hasFax| 
  The fax number used to reach a person or an organisation.|rdf:PlainLiteral [0..&#42;]
  
  
  
| cpov:ContactPoint + 
org:Organization
| epo:hasInternetAddress| 
  The main web page used by the instance of the concept.|xsd:anyURI [0..1] +
  xsd:anyURI [0..&#42;]
  
  
  
  
  
  
  
  
| epo:Contract
| epo:hasContractConclusionDate| 
  The date the contract was signed by the last signatory party. <u>Additional Information:</u> In exceptional cases contracts may be concluded without signature and therefore another date may be used. The date of contract conclusion is always later than the end of any standstill period. This concept is not to be confused with the date of completion/end of the contract.|xsd:date [0..1]
  
  
  
  
  
| epo:Contract
| epo:hasEntryIntoForceDate| 
  The date on which the contract enters into force. Additional information: This is generally the date on which the fulfillment of the contract begins.|xsd:date [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:ContractLotCompletionInformation
| epo:hasPaymentValueDiscrepancyJustification| 
  Justification for the actual value being different to the value in the initial Contract.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:ContractTerm
| epo:hasEInvoicing| 
  Electronic means will be used for invoicing in the post-award process. Additional Information: This attribute is used for standard form mappings.|xsd:boolean [0..1]
  
  
  
  
  
| epo:ContractTerm
| epo:hasEOrdering| 
  Electronic means will be used for requesting and purchasing in the post-award process.|xsd:boolean [0..1]
  
  
  
| epo:ContractTerm
| epo:hasEPayment| 
  Electronic means must be used for paying.|xsd:boolean [0..1]
  
  
  
  
  
  
  
| epo:ContractTerm
| epo:hasCompensationCostParametersDescription| 
  Explanatory text about the parameters of the financial compensation.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo:ContractTerm
| epo:hasDurationAdditionalInformation| 
  Supplementary data about the Duration of the Contract.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ContractTerm
| epo:hasGrantedExclusiveRightsDescription| 
  Explanatory text about the applicable right entitling a public service operator to operate certain public passenger transport services on a particular route or network or in a particular area, to the exclusion of any other such operator.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ContractTerm
| epo:hasLegalFormRequirement| 
  The legal form to be taken by a Contractor. Additional Information: Generally, this is defined to cover the case where an Organisation Group is involved. Note that the codelist provided at national level should be used.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ContractTerm
| epo:hasMaximumNumberOfRenewals| 
  The maximum number of times the contract can be renewed. Additional Information By renewing, the buyer reserves the right (i.e. not an obligation) to renew the contract (i.e. extend its duration) without a new procurement procedure. For example, a contract may be valid for one year and the buyer may keep a possibility to renew it (e.g. once, twice) for another three months, if he is content with the services he received. PLEASE REVIEW THIS DEFINITION AGAIN WITH THE WORKING GROUP. It was originally taken from eForms.|xsd:integer [0..1]
  
  
  
| epo:ContractTerm
| epo:hasOptions| 
  The buyer reserves the right (not an obligation) for additional purchases from the contractor (while the contract is valid).|xsd:boolean [0..1]
  
  
  
| epo:ContractTerm
| epo:hasOptionsDescription| 
  The motivation and details about additional purchases that the buyer may undertake while the contract is valid.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:ContractTerm
| epo:hasParticularConditionsDescription| 
  Explanatory text about conditions not mentioned elsewhere.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ContractTerm
| epo:hasPaymentArrangement| 
  Information about financial clauses that will govern some economic aspects of the execution of the contract. Additional Information: These clauses usually refer to financial and payment provisions. This type of information should be structured instead of a free text in order to reuse it an ideal world. Unfortunately this is an information that in the real life no one is willing to provide pro-actively. WG Pending of discussion with eForms|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:ContractTerm
| epo:hasPenaltiesAndRewardsDescription| 
  Explanatory text about the applicable penalties and rewards.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ContractTerm
| epo:hasPerformanceConditions| 
  The particular conditions and additional information related to the execution of the contract. Additional Information: For example, specific information about the place of performance, intermediary deliverables, compensation for damages, intellectual property rights.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo:ContractTerm
| epo:hasPlaceOfPerformanceAdditionalInformation| 
  Further details on the location of the execution of the contract.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:ContractTerm
| epo:hasPublicServiceObligationsDescription| 
  Explanatory text about the requirement defined or determined by a competent authority in order to ensure public passenger transport services in the general interest that an operator, if it were considering its own commercial interests, would not assume or would not assume to the same extent or under the same conditions without reward.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ContractTerm
| epo:hasRenewalDescription| 
  Any other information about the renewal(s).|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo:ContractTerm
| epo:hasReservedExecutionJustification| 
  An explanation about why the Contract must be performed in the framework of sheltered employment programmes.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ContractTerm
| epo:hasSocialStandardsDescription| 
  Explanatory text about the standards required, including staff concerned, detail of their contractual rights and obligations and conditions under which employees are considered to be linked to the services.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ContractTerm
| epo:hasTicketsSalesRevenueAllocation| 
  Share of revenue with regard to ticket sales.|xsd:decimal [0..1]
  
  
  
  
  
| epo:ContractTerm + 
epo:DynamicPurchaseSystemTechnique
| epo:hasUnknownDuration| 
  Indicates the Duration is undetermined.|xsd:boolean [0..1] +
  xsd:boolean [0..1]
  
  
  
| epo:ContractTerm + 
epo:DynamicPurchaseSystemTechnique
| epo:hasUnlimitedDuration| 
  Indicates the Duration is endless.|xsd:boolean [0..1] +
  xsd:boolean [0..1]
  
  
  
| epo:ContractTerm
| epo:isRenewalIndicator| 
  Indicates whether the contract is subject to a renewal clause.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ord:DeliveryAgreement
| epo-ord:hasGeneralDeliveryTerm| 
  Terms and conditions related to the delivery of goods.|rdf:PlainLiteral [0..1]
  
  
  
| epo-ord:DeliveryAgreement
| epo-ord:hasRequestedShippingPriority| 
  The level of importance or sequence assigned to the delivery.|rdf:PlainLiteral [0..1]
  
  
  
| epo-ord:DeliveryAgreement
| epo-ord:isPartialDeliveryAllowed| 
  An indicator to state if partial delivery is allowed or not.|xsd:boolean [0..1]
  
  
  
  
  
  
  
| epo-ord:DeliveryInformation + 
epo:Document
| epo:hasAccessURL| 
  Location where the resource can be accessed.|xsd:anyURI [0..&#42;] +
  xsd:anyURI [0..&#42;]
  
  
  
| epo-ord:DeliveryInformation
| epo-inv:hasActualDeliveryDate| 
  The date when the Delivery occured.|xsd:dateTime [0..1]
  
  
  
| epo-ord:DeliveryInformation
| epo-ord:hasDeliveryDeadline| 
  The final accepted date for Delivery.|xsd:dateTime [0..1]
  
  
  
| epo-ord:DeliveryInformation
| epo-ord:hasDeliveryEmail| 
  The electronic address to which the products or services are to be delivered.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-ord:DeliveryInformation
| epo-ord:hasDownloadURL| 
  Location where the resource can be downloaded.|xsd:anyURI [0..&#42;]
  
  
  
  
  
| epo-ord:DeliveryInformation
| epo-ord:hasShippingMark| 
  A text that the buyer requests to be printed on the packing labels.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:DesignContestRegimeTerm
| epo:hasDescriptionOfPrizes| 
  Explanatory text about Prizes.|rdf:PlainLiteral [0..1]
  
  
  
| epo:DesignContestRegimeTerm
| epo:hasFollowupContract| 
  Any subsequent service contract will be awarded to the winner or, in the case of a design contest, winners.|xsd:boolean [0..1]
  
  
  
| epo:DesignContestRegimeTerm
| epo:hasFollowupContractInformation| 
  Further information about follow-up contracts, prizes and payments (for example non-monetary prizes, payments given for participation).|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:DesignContestRegimeTerm
| epo:hasParticipationPayment| 
  Details on payments to participants|rdf:PlainLiteral [0..1]
  
  
  
| epo:DesignContestRegimeTerm
| epo:isJuryDecisionBinding| 
  Indicates whether the procuring entity is bound to apply the decision of the jury.|xsd:boolean [0..1]
  
  
  
| epo:DirectAwardTerm
| epo:hasJustification| 
  An explanation about the reasons for using the concept.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
| epo:Document
| epo:hasDispatchDate| 
  Date and time of transmission of a record to an Organization.|xsd:dateTime [0..1]
  
  
  
  
  
  
  
  
  
  
  
| epo:Document
| epo:hasPublicationDate| 
  Date of formal public issuance of the document.|xsd:date [0..1]
  
  
  
| epo:Document
| epo:hasReceptionDate| 
  Date when a record is acknowledged by an Organization.|xsd:date [0..1]
  
  
  
  
  
  
  
| epo:Document
| epo:hasVersion| 
  A number that identifies a specific state of a document.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:EnergyEfficiencyInformation
| epo:concernsTotalItems| 
  Number of total Items the instance of the concept relates to.|xsd:decimal [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
| cccev:Evidence + 
epo:Fund
| epo:hasURL| 
  The identifier of a resource. Additional Information For example: 1. The URL of the system from where to access the procurement documents; 2. The URL of the system for the submission of tender documents; 3. The URL of the system from where to download a tool to communicate with the Buyer; 4. The URL of the system used by a Technique to allow Economic Operators to exchange information with the Buyer (e.g. eAuction and DPS Systems) 5. The URL of the system used to exchange information between Buyer and EO for questions and clarifications;|xsd:anyURI [0..1] +
  xsd:anyURI [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:FrameworkAgreementTerm
| epo:hasBuyerCategoryDescription| 
  A classification of buyers participating in a framework agreement. Additional Information: Buyers that can use the Framework Agreement not mentioned by name. For example, the classification "all hospitals in the Tuscany region" is used instead of naming each individual buyer.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:FrameworkAgreementTerm
| epo:hasDurationExtensionJustification| 
  The explanation of the reason why the framework agreement has an extended duration. Additional Information: The justification for exceptional cases when the duration of the framework agreement exceeds the legal limits. Four years in the case of the general procurement Directive, seven years in the case of the defence Directive, and eight years in the case of the sectoral Directive.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo:FrameworkAgreementTerm
| epo:hasMaximumParticipantsNumber| 
  The maximum number of participants in the framework agreement. Additional Information: Maximum number of tenderers who may be awarded a contract within the framework agreement. The number is a positive integer.|xsd:integer [0..1]
  
  
  
  
  
  
  
  
  
  
| epo:GreenProcurement
| epo:usesCleanVehicleDirective| 
  The procurement falls within the scope of the European Parliament and Council 2009/33/EC (Clean Vehicles Directive – CVD).|xsd:boolean [0..1]
  
  
  
| adms:Identifier
| epo:hasExtension| 
  The name of the addition to the Identifier.|rdf:PlainLiteral [0..1]
  
  
  
| adms:Identifier
| epo:hasScheme| 
  The name of the identification scheme.|rdf:PlainLiteral [0..&#42;]
  
  
  
| adms:Identifier
| epo:hasSchemeVersion| 
  The version of the identification scheme.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:InternationalProcurementInstrumentMeasuresInformation
| epo:hasNumberOfTendersConcerned| 
  Number of Tenders the instance of the concept relates to.|xsd:integer [0..1]
  
  
  
| epo:InternationalProcurementInstrumentMeasuresInformation
| epo:hasPublicInterestExceptionJustification| 
  The reason why a derogation from international procurement access rules is applied under the International Procurement Instrument (IPI) Regulation.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:LotAwardOutcome
| epo:hasNonAwardedContractNumber| 
  The number the contract would have had if it had been awarded. Additional information: This field is provided to support the data provided in the TED Standard Forms, and it should be discontinued in the future.|rdf:PlainLiteral [0..1]
  
  
  
| epo:LotAwardOutcome
| epo:hasNonAwardedContractTitle| 
  The title the contract would have had if it had been awarded. Additional information: This field is provided to support the data provided in the TED Standard Forms, and it should be discontinued in the future.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
| epo:LotGroup + 
epo:ProcurementElement
| epo:isSMESuitable| 
  The procurement is suitable for small and medium enterprises (SMEs).|xsd:boolean [0..1] +
  xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:MonetaryValue
| epo:hasAmountValue| 
  The numeric value of the amount, including decimals.|xsd:decimal [1..1]
  
  
  
  
  
| epo:MonetaryValue
| epo:hasCurrencyCodeListID| 
  Concept scheme URI used for the currency code list.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:MonetaryValue
| epo:hasCurrencyCodeListAgencyID| 
  Identifier of the agency that maintains the currency code list used.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:MonetaryValue
| epo:hasCurrencyCodeListAgencyName| 
  Name of the agency that maintains the currency code list used.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:MultipleStageProcedureTerm
| epo:hasEstimatedInvitationToExpressInterestDate| 
  The estimated date of dispatch of the invitations to confirm interest.|xsd:date [0..1]
  
  
  
| epo:MultipleStageProcedureTerm
| epo:hasEstimatedInvitationToTenderDate| 
  The estimated date of dispatch of the invitations to submit tenders in two (or more) stage procedures.|xsd:date [0..1]
  
  
  
| epo:MultipleStageProcedureTerm
| epo:hasMaximumNumberOfCandidates| 
  Maximum number of candidates to be invited for the second stage of the procedure.|xsd:integer [0..1]
  
  
  
| epo:MultipleStageProcedureTerm
| epo:hasMinimumNumberOfCandidates| 
  Minimum number of candidates to be invited for the second stage of the procedure.|xsd:integer [0..1]
  
  
  
| epo:MultipleStageProcedureTerm
| epo:hasNoNegotiationNecessary| 
  The buyer reserves the right to award the contract on the basis of the initial tenders without any further negotiations. Additional information: See Article 29(4) of Directive 2014/24/EU.|xsd:boolean [0..1]
  
  
  
  
  
| epo:MultipleStageProcedureTerm
| epo:hasQualificationSystemRenewalDescription| 
  Explanation of how a Qualification System is re-established. Additional information: A Qualification System qualifies an economic operator to take part in a tendering process. Usually, in such cases the economic operator passes the Exclusion Grounds and Selection Criteria.|rdf:PlainLiteral [0..1]
  
  
  
| epo:MultipleStageProcedureTerm
| epo:hasSuccessiveReduction| 
  The number of solutions or tenders will be reduced in iterative evaluations for multiple staged procedures. Additional information: This refers to multiple-stage procedures (included two-stage procedures, at least). Open Procedures can be seen as one-stage procedures.|xsd:boolean [0..1]
  
  
  
| epo:NonDisclosureAgreementTerm
| epo:isNonDisclosureAgreementRequired| 
  A non-disclosure agreement is needed. Additional information: A non-disclosure agreement is a Contract between different parties which ensures information is not shared with other parties.|xsd:boolean [0..1]
  
  
  
  
  
| epo:NonPublishedInformation
| epo:hasAccessibilityDate| 
  The date at which unpublished data shall be published.|xsd:date [0..1]
  
  
  
| epo:NonPublishedInformation
| epo:hasConfidentialityJustification| 
  A narrative explanation of why data is not published. Additional Information: This element is generally used when the non-publication-justification code chosen is "other".|rdf:PlainLiteral [0..1]
  
  
  
| epo:NonPublishedInformation
| epo:hasMaskableProperty| 
  Resource that has a hidden value.|xsd:anyURI [1..1]
  
  
  
  
  
  
  
| epo:Notice
| epo:hasESenderDispatchDate| 
  The date and time the notice was transmitted electronically by the eSender to the Publications Office of the European Union. Additional Information: Typically, eSenders include national Official Journals, Buyers sending a large number of electronic Notices, public or private bodies acting on behalf of Buyers and eProcurement software developers.|xsd:dateTime [0..1]
  
  
  
| epo:Notice
| epo:hasOJSIssueNumber| 
  The issue identifier of the Supplement to the EU Official Journal. Additional information: The format of this identifier is XX-YYYY.|rdf:PlainLiteral [0..1]
  
  
  
| epo:Notice
| epo:hasFormNumber| 
  The number of the form used to create the Standard Form Notice and not an eForms Notice.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo:Notice
| epo:hasNoticePublicationNumber| 
  The identifier of the published Notice. Additional information: The format of this identifier is XXXXXXXX-YYYY.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:OpeningTerm
| epo:hasOpeningURL| 
  The identifier of the address of the Opening of Tenders.|xsd:anyURI [0..1]
  
  
  
| epo:OpeningTerm
| epo:hasOpeningDateTime| 
  Date and time for the opening of tenders.|xsd:dateTime [1..1]
  
  
  
| epo:OpeningTerm
| epo:hasOpeningDescription| 
  Further information about the opening of tenders. Additional Information For example, who may participate in the opening and whether any authorization is needed.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:OpeningTerm
| epo:hasOpeningPlace| 
  The place (e.g. physical address, URL) where the tenders will be publicly opened.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-ord:Order + 
epo-ord:OrderLine
| epo-ord:hasAccountingCost| 
  The accounting reference used by the Buyer to specify the account to which the order and the corresponding invoice are booked.|rdf:PlainLiteral [0..1] +
  rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-ord:Order
| epo-ord:hasPaymentTerm| 
  Condition and stipulation of the Payment.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ord:OrderResponse
| epo-ord:hasResponseDescription| 
  Explanation of the response.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
| epo:OrganisationGroup
| epo:hasGroupType| 
  Form of collaboration agreement between organisations. Additional Information: This is not a legal type; not to be mistaken with epo:hasLegalFormType which may also be used for Organisation Groups.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
| org:Organization
| epo:hasBuyerLegalTypeDescription| 
  Self-explanatory text about the Buyer Legal Type. Additional information: This field is used when the Buyer Legal Type is not available in the controlled list at-voc:buyer-legal-type . This is necessary in to cover data provided in the TED Standard Forms. It shall be deprecated in the future.|rdf:PlainLiteral [0..1]
  
  
  
| org:Organization
| epo:hasLegalFormType| 
  The classification of an Organisation according to legislation. Additional Information: Generally, this is defined for Tenderers who want to submit as an Organisation Group. Note that the codelist provided at national level should be used.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| org:Organization
| epo:hasLegalName| 
  The officially registered name of an organisation.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| org:Organization
| epo:hasMainActivityDescription| 
  Self-explanatory text about the Main Activity . Additional information: This field is used when the Main Activity is not available in the controlled list at-voc:main-activity-type . This is necessary in to cover data provided in the TED Standard Forms. It shall be deprecated in the future.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:ParticipationConditionsSummary
| epo:describesObjectiveParticipationRules| 
  General explanatory text on the rules and criteria to be fulfilled by the Tender.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ParticipationConditionsSummary
| epo:describesVerificationMethod| 
  General explanatory text on the means used to validate the Participation Conditions.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:Prize
| epo:hasPrizeRank| 
  The position of the prize (e.g. first place, second place) in a design contest list of prizes.|xsd:integer [0..1]
  
  
  
  
  
| epo:Procedure
| epo:hasAcceleratedProcedureJustification| 
  The reasons why the procedure is accelerated. Additional Information: A procedure is accelerated to cover needs of extraordinary circumstances ie earthquake relief.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:Procedure
| epo:hasMainFeature| 
  Main features of the procedure and information about where the full rules for the procedure can be found. Additional Information: This information should be given when the procedure is not one of those mentioned in the procurement directives. This can be the case for example for concessions, for social and other specific services, and in case of voluntary publication of procurement procedures below the EU procurement thresholds.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
| epo:Procedure
| epo:isAccelerated| 
  Statement about the fact that the procedure will be reduced due to a state of urgency. Additional Information This modifies the time limit for the receipt of requests to participate or the receipt of tenders.|xsd:boolean [0..1]
  
  
  
| epo:Procedure
| epo:isDesignContest| 
  A competition which enables the buyer to acquire a plan or design via a jury. Additional information: Design contests have traditionally mostly been used in the fields of town and country planning, architecture and engineering or data processing, other purposes, such as to obtain plans for financial engineering The contest may include or not the award of prizes;|xsd:boolean [0..1]
  
  
  
  
  
| epo:Procedure
| epo:isJointProcurement| 
  Multiple buyers procure together within the same procedure. Addition Information: In case the joint procurement involves buyers from different countries, the national law is specified by the epo:hasCrossBorderLaw in the ProcedureTerm .|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:ProcedureTerm
| epo:hasCrossBorderLaw| 
  The applicable law when buyers from different countries procure together within one procurement procedure.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:ProcedureTerm
| epo:hasGroupLotEvaluationMethod| 
  Description of how lots and groups of lots are evaluated against one another in the procedure.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:ProcedureTerm
| epo:hasLotAwardCombination| 
  The contracting authority reserves the right to award contracts combining lots or groups of lots. Additional Information: This property contains information about the Lots concerned. This property is required by the regulation (EU)-2015-1986 (modeled in the TED Standard Forms).|rdf:PlainLiteral [0..1]
  
  
  
| epo:ProcedureTerm
| epo:hasMaximumLotSubmissionAllowed| 
  The total number of lots for which one Tenderer can submit Tenders. Additional information: This field is used to complement the SubmissionTerms (which are at the Lot level) for the Procedure level which is covered by the regulation (EU)-2015-1986 (modeled in the TED Standard Forms).|xsd:integer [0..1]
  
  
  
| epo:ProcedureTerm
| epo:hasMaximumNumberOfLotsToBeAwarded| 
  The maximum number of lots for which contract(s) can be awarded to one tenderer. Additional information: This field is used to complement the SubmissionTerms (which are at the Lot level) for the Procedure level which is covered by the regulation (EU)-2015-1986 (modeled in the TED Standard Forms).|xsd:integer [0..1]
  
  
  
| epo:ProcedureTerm
| epo:hasNationalProcedureRules| 
  The resource identifier where the information about the national rules applicable to the procedure can be found.|xsd:anyURI [0..&#42;]
  
  
  
| epo:ProcedureTerm
| epo:isAwardedByCPB| 
  Procedure is awarded by a Central Purchasing Body.|xsd:boolean [0..1]
  
  
  
| epo:ProcedureTerm
| epo:isOneLotOnlyAllowed| 
  Indicates whether tenders may be submitted for only one Lot. Additional information: This field is used to complement the SubmissionTerms (which are at the Lot level) for the Procedure level which is covered by the regulation (EU)-2015-1986 (modeled in the TED Standard Forms).|xsd:boolean [0..1]
  
  
  
| epo:ProcedureTerm
| epo:isSubmissionForAllLotsRequired| 
  Indicates whether tenders must be submitted for all Lots.|xsd:boolean [0..1]
  
  
  
| epo:ProcessPlanningTerm
| epo:hasAwardDateScheduled| 
  Planned date for the award decision.|xsd:date [0..1]
  
  
  
| epo:ProcessPlanningTerm
| epo:hasEstimatedContractNoticePublicationDate| 
  Foreseen date for publication of Contract Notice.|xsd:date [0..1]
  
  
  
| epo:ProcessPlanningTerm
| epo:hasEstimatedTenderInvitationDate| 
  The planned date for the dispatch of the invitations to submit tenders.|xsd:date [0..1]
  
  
  
| epo:ProcurementCriteriaSummary
| epo:indicatesPerformingStaffInformationRequirement| 
  Obligation to indicate the names and professional qualifications of the staff assigned to performing the contract.|xsd:boolean [0..1]
  
  
  
| epo:ProcurementCriterion
| epo:hasFormula| 
  The mathematical equation or any other description used for complicated weighing of criteria (e.g. non-linear weighing, the analytic hierarchy process) when a weighing cannot be expressed per criterion.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo:ProcurementElement
| epo:appliesForeignSubsidiesRegulation| 
  Indicates whether the Foreign Subsidies Regulation is implemented.|xsd:boolean [0..1]
  
  
  
  
  
  
  
| epo:ProcurementElement
| epo:hasLegalBasisDescription| 
  Explanatory text about the legal basis.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo:ProcurementElement
| epo:isCoveredByGPA| 
  Specifies whether the Agreement on Government Procurement (GPA) applies. Additional information: The GPA aims to establish a multilateral framework of balanced rights and obligations relating to public contracts with a view to achieving the liberalization and expansion of world trade.|xsd:boolean [0..1]
  
  
  
  
  
  
  
| epo:ProcurementObject
| epo:hasRecurrenceDescription| 
  Any additional information about the recurrence of the Procurement. Additional Information: For example estimated timing of the Procedure.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ProcurementObject
| epo:isRecurrent| 
  The Procurement being notified is likely to be included in another procedure in the foreseeable future. Additional Information: For example, a regularly re-tendered municipal service. This does not include awarding multiple contracts within a single qualification system, framework agreement, or a dynamic purchasing system.|xsd:boolean [0..1]
  
  
  
| epo:ProcurementObject
| epo:isUsingEUFunds| 
  The procurement foresees funding by the Union. Additional Information: The funding may cover the whole procurement or part of the procurement. For example the European Structural and Investment Funds or grants awarded by the European Union.|xsd:boolean [0..1]
  
  
  
  
  
| epo:ProcurementProcessInformation
| epo:isDPSTerminated| 
  End of the Dynamic Purchase System (DPS). Additional Information: This property can be used in the contract award notice even if no contracts are awarded.|xsd:boolean [0..1]
  
  
  
| epo:ProcurementProcessInformation
| epo:isCompetitionTerminated| 
  No further contracts will be awarded in this procedure. Additional Information: This can be instantiated in the post award phase. PIN for Competition needs to be signaled. This field can be used even if no contracts are awarded in the contract award notice.|xsd:boolean [0..1]
  
  
  
| epo:ProcurementProcessInformation
| epo:isToBeRelaunched| 
  Indicator of whether the procurement object is to be relaunched. Additional information: This can be instantiated in the post award phase.|xsd:boolean [0..1]
  
  
  
  
  
| epo:ProfessionalSuitabilitySummary
| epo:describesProfession| 
  Explanatory text about the profession.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ProfessionalSuitabilitySummary
| epo:describesProfessionRelevantLaw| 
  Explanatory text about the law concerning the profession.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ProfessionalSuitabilitySummary
| epo:hasServiceReservedToParticularProfession| 
  Execution of the contract is limited to a particular profession.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:QualificationCriteriaSummary
| epo:hasConditionVerificationMethod| 
  Means used to validate the qualification requirements.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:QualificationCriteriaSummary
| epo:hasQualificationCondition| 
  Requirements to be fulfilled by tenders in view of their qualification.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:QualificationCriterion
| epo:hasQualificationCriteriaStatedInESPDRequest| 
  The Qualification Criteria is specified in the ESPD Request.|xsd:boolean [0..1]
  
  
  
| epo:QualificationCriterion
| epo:hasQualificationCriteriaStatedInNotice| 
  The Qualification Criteria is specified in the Notice.|xsd:boolean [0..1]
  
  
  
| epo:QualificationCriterion
| epo:hasQualificationCriteriaStatedInProcurementDocuments| 
  The Qualification Criteria is specified in the Procurement Documents.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
| epo:QualityTargetInformation
| epo:hasQualityTargetDescription| 
  Explanatory text about the performance goal.|rdf:PlainLiteral [1..1]
  
  
  
| epo:Quantity
| epo:hasQuantityValue| 
  The numeric value of the quantity, including decimals.|xsd:decimal [1..1]
  
  
  
  
  
| epo:Quantity
| epo:hasUnitDescription| 
  A narrative explanation defining the units of items being counted Additional information: This could be for example individual items or pack or two.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:ReviewDecision
| epo:hasWithdrawalDate| 
  The date and time when the request for review was withdrawn.|xsd:date [0..1]
  
  
  
| epo:ReviewDecision
| epo:hasWithdrawalReason| 
  The explanation for withdrawing the request for review.|rdf:PlainLiteral [0..1]
  
  
  
| epo:ReviewDecision
| epo:isWithdrawn| 
  The review request was withdrawn.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
| epo:ReviewIrregularitySummary
| epo:hasReviewIrregularityCount| 
  The number of requests for a given irregularity.|xsd:integer [1..1]
  
  
  
  
  
  
  
  
  
  
  
| epo:ReviewRequestSummary
| epo:hasNumberOfReviewRequests| 
  The number of requests the buyer received to review any of its decisions.|xsd:integer [1..1]
  
  
  
  
  
| epo:ReviewRequestSummary
| epo:hasTotalNumberOfComplainants| 
  The number of economic operators that requested the buyer to review any of its decisions (e.g. the technical specifications, award decision), as set out in Art. 1(5) of Directive 89/665/EEC and Directive 92/13/EEC.|xsd:integer [0..1]
  
  
  
  
  
  
  
| epo:ReviewTerm
| epo:hasReviewDeadline| 
  The time limit for review procedures.|xsd:dateTime [0..1]
  
  
  
| epo:ReviewTerm
| epo:hasReviewDeadlineInformation| 
  The description of the time limits for review procedures.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:ReviewTerm
| epo:hasReviewProcedure| 
  The description of the method used to request the verification that the procedure has been carried out correctly.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo:SecurityClearanceTerm
| epo:hasDeadline| 
  The time limit by which the security clearance must be submitted to the buyer.|xsd:dateTime [0..1]
  
  
  
| epo:SecurityClearanceTerm
| epo:isSecurityClearanceRequired| 
  Security Clearance is needed.|xsd:boolean [0..1]
  
  
  
  
  
  
  
| epo:SelectionCriteriaSummary
| epo:describesMinimumLevelOfStandards| 
  Explanatory text regarding the minimum level of standards required.|rdf:PlainLiteral [0..1]
  
  
  
| epo:SelectionCriteriaSummary
| epo:hasSelectionCriteriaStatedInProcurementDocuments| 
  The Selection Criteria are present in the Procurement Documents.|xsd:boolean [0..1]
  
  
  
  
  
| epo:SelectionCriterion
| epo:isUsedForCandidateRestriction| 
  The criterion will be used to select the candidates to be invited for the second stage of a multistage procedure. Additional Information: This property is only used if a maximum number of candidates was foreseen in the procedure.|xsd:boolean [0..1]
  
  
  
| epo:SocialProcurement
| epo:hasNonAccessibilityCriterionJustification| 
  Reason for not applying accessibility criteria.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
| epo:StrategicProcurement
| epo:hasStrategicProcurementDescription| 
  Self-explanatory text about a concept.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:SubcontractTerm
| epo:hasMaximumShare| 
  The maximum proportion of something to be distributed. Additional Information: In the case of subcontracting the share may refer to the proportion of works, services or supplies being subcontracted.|xsd:decimal [0..1]
  
  
  
| epo:SubcontractTerm
| epo:hasMinimumShare| 
  The minimum proportion of something to be distributed. Additional Information: In the case of subcontracting the share may refer to the proportion of works, services or supplies being subcontracted.|xsd:decimal [0..1]
  
  
  
| epo:SubcontractTerm
| epo:hasMinimumSubcontractorsProposedObligation| 
  The minimum percentage of the contract value that the contractor must subcontract. Additional information: This is used for the competitive procedure described in Title III of Directive 2009/81/EC.|xsd:decimal [0..1]
  
  
  
| epo:SubcontractTerm
| epo:hasSubcontractingInvolved| 
  List of Subcontractors and the subject matter they cover are required. Additional Information: The tenderer will ned to supply this information in the tender.|xsd:boolean [0..1]
  
  
  
  
  
| epo:SubcontractTerm
| epo:hasSubcontractorsProposedAboveObligation| 
  The maximum percentage of the contract value that the contractor must subcontract. Additional information: This is used for the competitive procedure described in Title III of Directive 2009/81/EC.|xsd:decimal [0..1]
  
  
  
| epo:SubcontractingEstimate
| epo:hasEstimatedPercentage| 
  The estimated proportion foreseen to be subcontracted.|xsd:decimal [0..1]
  
  
  
  
  
| epo:SubcontractingEstimate
| epo:hasSubjectMatter| 
  Description of the share of the contract that is to be subcontracted. Additional information: This can be an aggregate of several subcontracts.|rdf:PlainLiteral [0..&#42;]
  
  
  
| epo:SubcontractingEstimate
| epo:isSubcontractingPercentageKnown| 
  Indicates whether the ratio of the Subcontracting Estimate is defined.|xsd:boolean [0..1]
  
  
  
| epo:SubcontractingEstimate
| epo:isSubcontractingValueKnown| 
  Indicates whether the amount of the Subcontracting Estimate is defined.|xsd:boolean [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasEEAReceivedTenders| 
  The amount of tenders received from economic operators in other EEA countries other than the country of the buyer.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasEUReceivedTenders| 
  The amount of tenders received from economic operators in other EU countries other than the country of the buyer.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasSMEReceivedTenders| 
  The amount of tenders received from micro, small and medium-sized enterprises. <u>Additional Information:</u> See Commission Recommendation 2003/361/EC. The ReceivedSMETenderLots is used when the size of the company is not exactly known.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasSMEReceivedTendersExcludingSubcontractors| 
  The amount of Tenders received from economic operators that are SMEs without taking into account Subcontractors.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasAbnormallyLowTenders| 
  Tenders received that were found irregular and non-acceptable due to an abnormally low price or cost. Additional Information The definition implies that abnormally Low Tender Lots are Inadmissible Tender Lots.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasElectronicTenders| 
  Electronic Tender Lots received.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasEstimatedTotalSubcontracts| 
  The estimated amount of work to be subcontracted in the contract resulting from the lot.|xsd:integer [0..1]
  
  
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasInadmissibleTenders| 
  Tenders received that cannot be awarded due to non-compliance to procurement document requirements or having an abnormally low price or cost. <u>Additional Information: </u> Non-compliance with a Procurement Document requirements include exclusion grounds, selection criteria and submission deadline, etc.|xsd:integer [0..1]
  
  
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasMediumTenderPerLots| 
  Tenders from medium-sized enterprise. <u>Additional Information:</u> See Commission Recommendation 2003/361/EC.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasNonEEAReceivedTenders| 
  The amount of tenders received from economic operators in non-EEA countries.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasNonEUReceivedTenders| 
  The amount of tenders received from economic operators in non-EU countries.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasNumberOfTenderersInvited| 
  Number of economic operators invited to tender. Additional Information This may be used for single-stage procedures or to indicate the number of candidates invited to tender in multi-stage procedures.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasOtherCountriesReceivedTenders| 
  The amount of Tenders received from European Economic Area countries other than that of the Buyer.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasReceivedMicroTenders| 
  The amount of tenders received from a micro enterprise. <u>Additional Information:</u> See Commission Recommendation 2003/361/EC.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasReceivedParticipationRequests| 
  The amount of applications to participate from economic operators.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasReceivedSmallTenders| 
  Tenders from small enterprise. <u>Additional Information:</u> See Commission Recommendation 2003/361/EC.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasReceivedTenders| 
  The total amount of tenders received.|xsd:integer [0..1]
  
  
  
| epo:SubmissionStatisticalInformation
| epo:hasUnverifiedTenders| 
  Offers received for which it has not been verified if they are admissible or inadmissible (e.g. because award criteria have been evaluated for all tenders and admissibility is checked only for the winning tender).|xsd:integer [0..1]
  
  
  
  
  
  
  
  
  
| epo:SubmissionTerm
| epo:hasEAuctionURL| 
  The internet address of the electronic auction.|xsd:anyURI [0..1]
  
  
  
  
  
  
  
| epo:SubmissionTerm
| epo:hasGuaranteeDescription| 
  Information on the financial commitment required from the economic operator. Additional Information: 1. This information may include the amount and the way of delivering of the guarantee 2. The financial commitment may be retained by the buyer in the case the tenderer withdraws the submitted information (i.e. tender, expression of interest and request for participation, but not request for clarifications) before the award of the contract or does not sign the contract. 3. Usual modalities are bonds, cheques, loans, other.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo:SubmissionTerm
| epo:hasLateSubmissionInformationDescription| 
  A narrative text explaining the content of the economic operator information that can be submitted late. Additional Information This does not apply to requests for clarifications.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo:SubmissionTerm
| epo:hasNonElectronicSubmissionDescription| 
  Textual explanation of how non-electronic information is to be presented.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo:SubmissionTerm
| epo:hasReceiptDeadline| 
  The time limit for receiving submissions. Additional Information This is the deadline by which the buyer must receive submissions (e.g. tenders, requests to participate, clarifications, etc.) and is not the time at which the information is submitted by the economic operator. This attribute should be used for standard forms mappings.|xsd:dateTime [0..1]
  
  
  
| epo:SubmissionTerm
| epo:hasReceiptExpressionDeadline| 
  Time limit for receipt of expressions of interest. Pending of review by the WG|xsd:dateTime [0..1]
  
  
  
| epo:SubmissionTerm
| epo:hasReceiptParticipationRequestDeadline| 
  The time limit until which requests to participate can be received.|xsd:dateTime [0..1]
  
  
  
| epo:SubmissionTerm
| epo:hasReceiptPreliminaryMarketConsultationDeadline| 
  The time limit until which answers to the Preliminary Market Consultation can be received.|xsd:dateTime [0..1]
  
  
  
| epo:SubmissionTerm
| epo:hasReceiptTenderDeadline| 
  The time limit until which the Tenders can be received.|xsd:dateTime [0..1]
  
  
  
| epo:SubmissionTerm
| epo:hasSubmissionURL| 
  The identifier of a resource used for Submission.|xsd:anyURI [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
| epo:SubmissionTerm
| epo:isAdvancedElectronicSignatureRequired| 
  Advanced or qualified electronic signature or seal (as defined in Regulation (EU) No 910/2014) is required. The submitted information is required to be signed electronically. Additional Information: Signature can be defined as "data in electronic form which is attached to or logically associated with other data in electronic form and which is used by the signatory to sign. For more details on the meaning and uses of electronic signature you may consult different authoritative sources, a relevant one being for instance the Regulation (EU) 910/2014 on electronic identification and trust services for electronic transactions in the internal market.|xsd:boolean [0..1]
  
  
  
| epo:SubmissionTerm
| epo:isGuaranteeRequired| 
  The submitted information must include a financial commitment to be used in case of default. Additional Information: See the additional information provided in the definition of the 'Guarantee Description' element.|xsd:boolean [0..1]
  
  
  
| epo:SubmissionTerm
| epo:isMultipleTenderSubmissionAllowed| 
  Tenderers may submit more than one competing tenders.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:Tender
| epo:hasElectronicSubmission| 
  Transmission of tenders is possible by electronic means of communication.|xsd:boolean [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo:Tender
| epo:isVariant| 
  Alternative solution to fulfil the buyer's needs as opposed to solutions indicated in the procurement documents. Additional Information: The permission to offer variants is only allowed if specified in a Contract Notice or a Prior Information Notice that used as a means for calling for a competition. The buyer lays out minimum requirements in the procurement documents that must be respected by tenderers submitting variants.|xsd:boolean [0..1]
  
  
  
  
  
| epo:TenderAwardOutcome
| epo:hasAwardRank| 
  The position of the tender (i.e. whether the tender ended up first, second, third, etc.) in a design contest, some framework agreements with multiple winners (e.g. cascades) or an innovation partnership.|xsd:integer [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
| epo:definesCatalogueProvider| 
  Relation indicating an AccessTerm has a CatalogueProvider.|epo:AccessTerm → epo:CatalogueProvider [0..&#42;]

  

  
  
| epo:definesCatalogueReceiver| 
  Relation indicating an AccessTerm has a CatalogueReceiver.|epo:AccessTerm → epo:CatalogueReceiver [0..&#42;]

  

  
  
| epo:definesOfflineAccessProvider| 
  Relation indicating an AccessTerm has an OfflineAccessProvider.|epo:AccessTerm → epo:OfflineAccessProvider [0..1]

  

  
  
| epo:definesProcurementProcedureInformationProvider| 
  Relation indicating an AccessTerm has a ProcurementProcedureInformationProvider.|epo:AccessTerm → epo:ProcurementProcedureInformationProvider [0..1]

  

  
  
  

  
  
| epo:hasDocumentRestrictionJustification| 
  An explanation about the reasons why some procurement documents are restricted.|epo:AccessTerm → at-voc:communication-justification [0..1]

  

  
  
  

  
  
  

  
  
| epo:involvesProcurementDocument| 
  Is about Procurement Document.|epo:AccessTerm → epo:ProcurementDocument [0..1]

  

  
  
  

  
  
| epo:providesProcurementDocumentsInOfficialLanguage| 
  Relation indicating the official language of the provided Procurement Documents.|epo:AccessTerm → at-voc:language [0..&#42;]

  

  
  
| epo:providesProcurementDocumentsInUnofficialLanguage| 
  Relation indicating the unofficial language of the provided Procurement Documents.|epo:AccessTerm → at-voc:language [0..&#42;]

  

  
  
| epo:refersToPlannedPart| 
  Reference to a Planned Procurement Part.|epo:AccessTerm → epo:PlannedProcurementPart [0..&#42;]

  

  

  

  

  
  
| epo:hasCountryCode| 
  Relation indicating the Country code.|locn:Address → at-voc:country [0..1] +
dct:Location → at-voc:country [0..1]

  

  
  
| epo:hasNutsCode| 
  Relation indicating the Nomenclature of Territorial Units for Statistics code.|locn:Address → at-voc:nuts [0..1] +
dct:Location → at-voc:nuts [0..1]

  

  

  

  

  

  

  
  
  

  
  
| epo:hasCertification| 
  Relation to the proof of conformance.|foaf:Agent → epo:Certificate [0..&#42;]

  

  

  
  
| epo:ownsSystem| 
  Relation indicating the Agent who holds the legal rights over the instance of the concept. Relation indicating the System over which the instance of the concept holds the legal rights.|foaf:Agent → epo:System [0..&#42;]

  

  

  
  
| epo:contextualisedBy| 
  The place of the AgentInRole in the procurement is expressed by a ProcurementObject.|epo:AgentInRole → epo:ProcurementElement [0..&#42;]

  

  

  
  
| epo:exposesChannel| 
  Makes available a Channel.|epo:AgentInRole → cv:Channel [0..&#42;] +
org:Organization → cv:Channel [0..&#42;]

  

  
  
| epo:hasContactPointInRole| 
  Relation indicating the Agent In Role has a Contact Point.|epo:AgentInRole → cpov:ContactPoint [0..&#42;]

  

  
  
| epo:playedBy| 
  Relation indicating the Agent that fulfills the function of the instance of the concept.|epo:AgentInRole → foaf:Agent [1] +
epo:JuryMember → person:Person [0..1] +
epo:UniqueResponsibleOfTheProcurement → person:Person [0..1]

  

  
  
  

  
  
  

  
  
| epo-ful:hasAllowanceChargeReason| 
  The justification for using the Allowance or the Charge.|epo-ord:AllowanceChargeInformation → at-voc-new:allowance-charge-reason [0..1]

  

  
  
  

  
  
| epo-cat:hasAmount| 
  The predetermined monetary value charged in addition to the price.|epo-ord:AllowanceChargeInformation → epo:MonetaryValue [0..1] +
epo-ord:AllowanceChargeInformation → epo:MonetaryValue [0..1] +
epo-ord:TaxInformation → epo:MonetaryValue [0..1] +
epo-ord:TaxInformation → epo:MonetaryValue [0..1]

  

  
  
  

  
  
| epo-ord:hasTaxInformation| 
  Relation indicating the Tax Information.|epo-ord:AllowanceChargeInformation → epo-ord:TaxInformation [0..1] +
epo:Contract → epo-ord:TaxInformation [0..1] +
epo:Contract → epo-ord:TaxInformation [0..1]

  

  
  
| epo:isCalculatedOn| 
  The monetary amount to which the multiplier factor is applied in calculating the amount of this allowance, charge or tax.|epo-ord:AllowanceChargeInformation → epo:MonetaryValue [0..1] +
epo-ord:AllowanceChargeInformation → epo:MonetaryValue [0..1] +
epo-ord:TaxInformation → epo:MonetaryValue [0..1] +
epo-ord:TaxInformation → epo:MonetaryValue [0..1]

  

  
  
| epo-inv:isSpecificToInvoiceLine| 
  Information that is particular to an Invoice Line.|epo-ord:AllowanceInformation → epo-inv:InvoiceLine [0..&#42;]

  

  
  
| epo-ord:isSpecificToOrderLine| 
  Information that is particular to one or multiple Order Lines.|epo-ord:AllowanceInformation → epo-ord:OrderLine [0..&#42;] +
epo-ord:ContractInformation → epo-ord:OrderLine [0..&#42;] +
epo-ord:DeliveryInformation → epo-ord:OrderLine [0..&#42;] +
epo-ord:OriginatorInformation → epo-ord:OrderLine [0..&#42;]

  

  
  
  

  
  
  

  
  
| epo:providesDocumentation| 
  Makes available the Documentation.|epo:AuxiliaryParty → epo:Documentation [0..&#42;]

  

  
  
  

  
  
| epo:hasAwardCriterionType| 
  Category of award criterion.|epo:AwardCriterion → at-voc:award-criterion-type [0..1]

  

  
  
  

  
  
| epo:hasFixedValueType| 
  The method to interpret the fixed value as pertaining to a total or unit.|epo:AwardCriterion → at-voc:number-fixed [0..1]

  

  
  
| epo:comprisesAwardOutcome| 
  Incorporates AwardOutcome.|epo:AwardDecision → epo:AwardOutcome [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:comprisesTenderAwardOutcome| 
  Incorporates TenderAwardOutcome.|epo:AwardOutcome → epo:TenderAwardOutcome [0..&#42;]

  

  
  
  

  
  
| epo:hasAwardStatus| 
  Indicates whether the lot is awarded, not awarded or still open.|epo:AwardOutcome → at-voc:winner-selection-status [0..1]

  

  
  
| epo:hasAwardedValue| 
  The value of the procurement provided by the Award Decision. Additional Information: Different cases of awarded values may refer to a lot, the global value of the procedure, or of a combinatorial value of a group of lots. In the case of framework agreements and dynamic purchasing systems this refers to the maximum awarded value.|epo:AwardOutcome → epo:MonetaryValue [0..1]

  

  
  
| epo:hasBargainPrice| 
  The value of procured supplies that have used a particularly advantageous opportunity available for a very short time at a value considerably lower than normal market prices.|epo:AwardOutcome → epo:MonetaryValue [0..1]

  

  
  
| epo:hasNonAwardJustification| 
  On hold; Enumeration.|epo:AwardOutcome → at-voc:non-award-justification [0..1]

  

  
  
| epo:hasBeneficialOwner| 
  A role of any natural person(s) who ultimately owns or controls the organisation or on whose behalf a transaction or activity is being conducted. Additional Information: This role is defined in the directive EU 2015/849 and it's beyond the scope for public eProcurement domain.|epo:Business → person:Person [0..&#42;]

  

  
  
| epo:hasBusinessSize| 
  The category of the business depending on number of employees and turnover. Additional information: See Commission Recommendation of 6 May 2003 concerning the definition of micro, small and medium-sized enterprises.|epo:Business → at-voc:economic-operator-size [0..1]

  

  
  
  

  
  
| epo:delegatesAncillaryActivitiesTo| 
  Entrusts ancillary purchasing activities to ProcurementServiceProvider. Additional Information: Directive 2014/24/EU describes ancillary purchasing activities as activities consisting in the provision of support to purchasing activities, in particular in the following forms: (a) technical infrastructure enabling contracting authorities to award public contracts or to conclude framework agreements for works, supplies or services; (b) advice on the conduct or design of public procurement procedures; (c) preparation and management of procurement procedures on behalf and for the account of the contracting authority concerned.|epo:Buyer → epo:ProcurementServiceProvider [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:attestedByLabel| 
  Relation indicating which label the certificate is about.|epo:Certificate → epo:CertificationLabel [0..1]

  

  
  
  

  
  
| epo:issuedByCertifier| 
  Relation indicating the Certifier responsible for providing the ItemCertificate. Additional Information: Certifier is a role played by an organisation.|epo:Certificate → epo:Certifier [0..1]

  

  
  
| epo:hasLabelType| 
  The label type such environmental, quality, social etc.|epo:CertificationLabel → at-voc-new:certification-label-type [0..1]

  

  
  
  

  
  
| epo:concernsNotice| 
  Relates to Notice.|epo:ChangeInformation → epo:Notice [1] +
epo:NonPublishedInformation → epo:Notice [1]

  

  
  
  

  
  
  

  
  
| epo:hasChangeJustification| 
  Code explaining the change.|epo:ChangeInformation → at-voc:change-corrig-justification [1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:refersToPreviousNotice| 
  Reference to a Notice published before.|epo:ChangeInformation → epo:Notice [1]

  

  
  
| epo:relatesToEFormSectionIdentifier| 
  Is about a specific eForms section.|epo:ChangeInformation → adms:Identifier [1..&#42;]

  

  
  
  

  
  
| epo:hasEndpointIdentifier| 
  The identifier of the specific location, address, or interface where a system, service, or application can be accessed.|cv:Channel → adms:Identifier [0..&#42;]

  

  
  
| epo:concernsGreenProcurement| 
  Relates to Green Procurement.|epo:CleanVehicleDirectiveInformation → epo:GreenProcurement [0..1] +
epo:EnergyEfficiencyInformation → epo:GreenProcurement [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:specifiesCleanVehicleDirectiveContractType| 
  Relation indicating the Clean Vehicle Directive Contract type.|epo:CleanVehicleDirectiveInformation → at-voc:cvd-contract-type [0..1]

  

  
  
| epo:specifiesCleanVehicleDirectiveVehicleCategory| 
  Relation indicating the Clean Vehicle Directive Category.|epo:CleanVehicleDirectiveInformation → at-voc:vehicle-category [0..1]

  

  
  
| epo:resultsFromLotAwardOutcome| 
  Relation to indicate that a given type of Contract is a consequence of a given Lot Award Outcome.|epo:ConcessionContract → epo:LotAwardOutcome [0..&#42;] +
epo:DirectContract → epo:LotAwardOutcome [0..&#42;] +
epo:FrameworkAgreement → epo:LotAwardOutcome [0..&#42;]

  

  
  
  

  
  
| epo:hasConcessionEstimatedValue| 
  Relation indicating the estimated Monetary Value of the Concession.|epo:ConcessionEstimate → epo:MonetaryValue [0..1]

  

  
  
| epo:hasEstimatedBuyerConcessionRevenue| 
  The expected payments made by the buyer to the economic operator awarded the concession that are not directly related to the use of the concession. <u>Additional Information:</u> For example the public buyer pays a yearly fee to provide a ticketing solution to the public. The fee the public pays for every ticket sold through the solution is not included in this estimation but in the estimation of the user concession revenue.|epo:ConcessionEstimate → epo:MonetaryValue [0..1]

  

  
  
| epo:hasEstimatedUserConcessionRevenue| 
  The estimated revenue coming from the use of the concession. Additional Information: Revenues are for example fees and fines. For example, the fees and fines coming from the cars using a motorway.|epo:ConcessionEstimate → epo:MonetaryValue [0..1]

  

  

  
  
| epo:hasThresholdType| 
  The method to interpret the threshold value as minimum or a maximum.|cccev:Constraint → at-voc:number-threshold [0..&#42;]

  

  
  
  

  

  

  
  
  

  
  
  

  
  
  

  

  
  
| epo:bindsBuyer| 
  Provides legal constraint on the Buyer.|epo:Contract → epo:Buyer [0..&#42;]

  

  
  
| epo:bindsContractor| 
  Provides legal constraint on the Contractor.|epo:Contract → epo:Contractor [0..&#42;]

  

  
  
  

  
  
| epo:hasContractValue| 
  Relation indicating the Monetary value of the Contract.|epo:Contract → epo:MonetaryValue [0..1]

  

  
  
  

  
  
| epo:hasLotReference| 
  Relation indicating the instance of the concept refers to a Lot.|epo:Contract → epo:Lot [1..&#42;]

  

  
  
| epo:hasPurpose| 
  Relation indicating the Purpose of a concept.|epo:Contract → epo:Purpose [0..1] +
epo:ProcurementElement → epo:Purpose [0..1]

  

  
  
| epo:includesTender| 
  Contains Tender.|epo:Contract → epo:Tender [0..&#42;]

  

  
  
| epo:isFundedBy| 
  Funding is provided either completely or partially by a Fund. Additional information: Funds may change between the lot and the contract, for example in the case of an emergency crisis, a contract may be financed by a budget that was not foreseen in the call.|epo:Contract → epo:Fund [0..&#42;] +
epo:ProcurementObject → epo:Fund [0..&#42;]

  

  
  
| epo:isSubjectToTerm| 
  Relation indicating that the instance of the concept applies a Term.|epo:Contract → epo:Term [0..&#42;] +
epo:LotGroup → epo:Term [0..&#42;] +
epo:ProcurementElement → epo:Term [0..&#42;]

  

  
  
| epo:signedByBuyer| 
  Relation indicating the Buyer that signs the instance of the concept.|epo:Contract → epo:Buyer [0..&#42;]

  

  
  
| epo:signedByContractor| 
  Relation indicating the Contractor that signs the instance of the concept.|epo:Contract → epo:Contractor [0..&#42;]

  

  
  
| epo:specifiesDeliverable| 
  Relation indicating the Deliverable.|epo:Contract → epo-con:Deliverable [0..&#42;]

  

  
  
| epo-ord:concernsContract| 
  Relates to Contractor.|epo-ord:ContractInformation → epo:Contract [1] +
epo-ord:ContractInformation → epo:Contract [1]

  

  
  
| epo:concernsLot| 
  Relates to Lot.|epo:ContractLotCompletionInformation → epo:Lot [0..1] +
cccev:InformationRequirement → epo:Lot [0..&#42;] +
epo:LotAwardOutcome → epo:Lot [1] +
epo:ProcurementProcessInformation → epo:Lot [0..1]

  

  
  
| epo:concernsLotGroup| 
  Relates to Lot Group.|epo:ContractLotCompletionInformation → epo:LotGroup [0..1] +
cccev:InformationRequirement → epo:LotGroup [0..&#42;]

  

  
  
  

  
  
| epo:providesContractTotalPaymentValue| 
  Makes available the overall Monetary Value of the Contract to be paid.|epo:ContractLotCompletionInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:providesContractTotalPenaltyValue| 
  Makes available the overall Monetary Value of the penalties of the Contract.|epo:ContractLotCompletionInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:refersToContract| 
  Reference to a Contract.|epo:ContractLotCompletionInformation → epo:Contract [1]

  

  
  
| epo:definesContractDuration| 
  Relation indicating a Contract has a Duration.|epo:ContractTerm → time:Duration [0..1]

  

  
  
| epo:definesContractPeriod| 
  Relation indicating a ContractTerm has a Period.|epo:ContractTerm → time:Interval [0..1]

  

  
  
| epo:definesEstimatedContractDuration| 
  Relation indicating a Contract has an estimated Duration.|epo:ContractTerm → time:Duration [0..1]

  

  
  
| epo:definesPaymentExecutor| 
  Relation indicating a ContractTerm has a PaymentExecutor.|epo:ContractTerm → epo:PaymentExecutor [0..1]

  

  
  
| epo:definesPublicTransportationKilometers| 
  Relation indicating the distance of passenger transport services of general economic interest provided to the public on a non-discriminatory and continuous basis.|epo:ContractTerm → epo:Quantity [0..1]

  

  
  
| epo:definesSpecificPlaceOfPerformance| 
  Relation indicating a ContractTerm has a specific place of performance.|epo:ContractTerm → dct:Location [0..&#42;]

  

  
  
| epo:definesSubcontractingTerm| 
  Relation indicating a ContractTerm has a SubcontractingTerm. Relation indicating a term has a subterm.|epo:ContractTerm → epo:SubcontractTerm [0..1]

  

  
  
| epo:describesAsset| 
  Characterises Asset.|epo:ContractTerm → epo:Asset [0..&#42;]

  

  
  
  

  
  
| epo:hasEInvoicingPermission| 
  Relation indicating the eInvoicing Permission.|epo:ContractTerm → at-voc:permission [0..1]

  

  
  
  

  
  
  

  
  
| epo:hasAdditionalContractNature| 
  Additional type of acquisition taken into consideration in the contract.|epo:ContractTerm → at-voc:contract-nature [0..&#42;]

  

  
  
| epo:hasBroadPlaceOfPerformance| 
  Geopolitical zone where the contract can be executed. Additional Information Used for setting restrictions that cannot be established with one country code or a geographical zone identifier (like NUTS), because they have a broader scope (geographical, economic, political, other).|epo:ContractTerm → at-voc:other-place-service [0..1]

  

  
  
  

  
  
| epo:hasContractNatureType| 
  Subject of the acquisition.|epo:ContractTerm → at-voc:contract-nature [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasPerformingStaffQualificationInformation| 
  Explanation as to if and/or when information of the persons to carry out the contract is to be provided. The codelist to be used is at-voc:requirement-stage which is available at http://publications.europa.eu/resource/dataset/requirement-stage|epo:ContractTerm → at-voc:requirement-stage [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasReservedExecution| 
  Relation indication whether the execution of the contract must be performed in the framework of sheltered employment programmes.|epo:ContractTerm → at-voc:applicability [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasTransportServiceType| 
  Relation indicating the Transport Service category.|epo:ContractTerm → at-voc:transport-service [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:foreseesSubcontractor| 
  Relation indicating that an Organization plans to have a Subcontractor. Additional information: In eForms, in a Result Notice, the foreseen Subcontractors in a Tender are associated to the Organization that proposes the Subcontractors. The Subcontractor is associated to the Organization, rather than the Tenderer, so that, in the case of multiple Organizations being a Tenderer, it is clear to which Organization the proposed Subcontractor is associated.|epo:Contractor → epo:Subcontractor [0..1] +
org:Organization → epo:Subcontractor [0..&#42;]

  

  
  
| epo:hasSubcontractor| 
  Relation indicating the Subcontractor.|epo:Contractor → epo:Subcontractor [0..1]

  

  
  
| epo:needsToBeAWinner| 
  The Contractor must be a Winner.|epo:Contractor → epo:Winner [0..1]

  

  

  

  

  

  
  
  

  
  
  

  
  
  

  
  
| epo-ord:specifiesDeliveryAgreementLocation| 
  Relation indicating the Location from the Delivery Agreement.|epo-ord:DeliveryAgreement → dct:Location [0..1] +
epo-ord:DeliveryAgreement → dct:Location [0..1]

  

  
  
| epo-ord:concernsConsignee| 
  Relates to Consignee.|epo-ord:DeliveryInformation → epo-ord:Consignee [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo-ord:hasDeliveryPeriod| 
  Relation indicating the time range for the delivery.|epo-ord:DeliveryInformation → time:Interval [0..1] +
epo-ord:DeliveryInformation → time:Interval [0..1]

  

  
  
  

  
  
| epo-ord:hasRequestedDeliveryPeriod| 
  Relation indicating the sought time range for the delivery.|epo-ord:DeliveryInformation → time:Interval [0..1] +
epo-ord:DeliveryInformation → time:Interval [0..1]

  

  
  
  

  
  
| epo-ful:hasTrackingID| 
  Relation indicating that thedelivery has an identifier for traceability purposes.|epo-ord:DeliveryInformation → adms:Identifier [0..1] +
epo-ord:DeliveryInformation → adms:Identifier [0..1]

  

  
  
| epo-ord:isSpecificToRequestForOfferLine| 
  Information that is particular to a Request For Offer Line.|epo-ord:DeliveryInformation → epo-req:RequestForOfferLine [0..&#42;]

  

  
  
| epo-ord:specifiesDeliveryAgreement| 
  Relation indicating the Delivery Agreement.|epo-ord:DeliveryInformation → epo-ord:DeliveryAgreement [0..1]

  

  
  
| epo-ord:specifiesPlaceOfDelivery| 
  Relation indicating the Location of the despatch.|epo-ord:DeliveryInformation → dct:Location [0..1] +
epo-ord:DeliveryInformation → dct:Location [0..1]

  

  
  
| epo:definesPrize| 
  Relation indicating a DesignContestRegimeTerm has a Prize.|epo:DesignContestRegimeTerm → epo:Prize [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:refersToPreviousProcedure| 
  Reference to a previous procedure. Additional Information: In the case of Direct Award Terms, this property points to a previous Procedure justifying the use of Direct Award without a prior publication.|epo:DirectAwardTerm → epo:Procedure [0..1]

  

  
  
| epo:refersToPreviousProcedureLot| 
  Reference to one or more Lots in a previous procedure. Additional Information: In the case of Direct Award Terms, this property points to a previous Procedure justifying the use of Direct Award without a prior publication.|epo:DirectAwardTerm → epo:Lot [0..&#42;]

  

  
  
| epo:associatedWith| 
  The document to which a document is associated.|epo:Document → epo:Document [0..&#42;]

  

  
  
| epo:hasUUID| 
  A universally unique identifier for an instance of this document.|epo:Document → adms:Identifier [0..1]

  

  
  
  

  
  
| epo:hasDocumentType| 
  Relation indicating the Document Type.|epo:Document → at-voc-new:document-type [0..1]

  

  
  
| epo:hasElectronicDigest| 
  Relation indicating the digital summary that represents the content of the instance of the concept.|epo:Document → epo:Document [0..&#42;]

  

  
  
| epo:hasElectronicSignature| 
  Relation indicating that the instance of the concept has an Electronic Signature.|epo:Document → epo:ElectronicSignature [0..&#42;]

  

  
  
| epo:hasOfficialLanguage| 
  The language(s) in which the instances of the given concepts are officially available. These linguistic versions are equally legally valid.|epo:Document → at-voc:language [1..&#42;]

  

  
  
  

  
  
  

  
  
| epo:hasSpecificationInformation| 
  Relation indicating the Specification Information.|epo:Document → epo:SpecificationInformation [0..&#42;]

  

  
  
| epo:hasUnofficialLanguage| 
  The language translation(s) in which the instances of the given concepts are available. These linguistic versions are not an official translation, they are provided only for information.|epo:Document → at-voc:language [0..&#42;]

  

  
  
  

  

  
  
| epo:refersToPrevious| 
  Reference to a prior instance of the concept.|epo:Document → epo:Document [0..&#42;]

  

  

  

  
  
| epo:hasDPSScope| 
  Explanation as to whether a dps is used and by whom. The codelist to be used is at-voc:dps-usage which is available at http://publications.europa.eu/resource/dataset/dps-usage|epo:DynamicPurchaseSystemTechnique → at-voc:dps-usage [0..1]

  

  
  
| epo:hasEstimatedDuration| 
  Relation indicating a Dynamic Purchase System has an estimated Duration.|epo:DynamicPurchaseSystemTechnique → time:Duration [0..1]

  

  
  
| epo:concernsEnergyEfficiencyItemCategory| 
  Relates to Energy Efficiency Item Category.|epo:EnergyEfficiencyInformation → at-voc:energy-efficiency-item [0..1]

  

  
  
  

  
  
| epo:hasCalculationBasedOn| 
  Relation indicating the basis for the calculation of the energy efficiency.|epo:EnergyEfficiencyInformation → at-voc:energy-efficiency-basis [0..1]

  

  
  
| epo:hasEnergyEfficiencyLabel| 
  Relation indicating the Energy Efficiency Label.|epo:EnergyEfficiencyInformation → at-voc:energy-efficiency-label [0..1]

  

  
  
| epo:hasItemConsumption| 
  Relation indicating the amount of resources an Item uses.|epo:EnergyEfficiencyInformation → epo:Quantity [0..1]

  

  
  
| epo:hasItemConsumptionSavings| 
  Relation indicating the amount of resources an Item saves.|epo:EnergyEfficiencyInformation → epo:Quantity [0..1]

  

  

  

  
  
  

  
  
| epo:hasValidityPeriod| 
  The relation indicating until when a given instance of a concept is applicable.|cccev:Evidence → time:Interval [0..1] +
epo-ord:Order → time:Interval [0..1] +
epo-ord:Order → time:Interval [0..1] +
epo:Technique → time:Interval [0..1]

  

  

  

  

  
  
| epo:hasExclusionGroundType| 
  Relation indicating the exclusion ground classification.|epo:ExclusionGround → at-voc:exclusion-ground [0..1]

  

  
  
| epo:concernsProcedure| 
  Relates to Procedure.|epo:ExpressionOfInterest → epo:Procedure [1] +
cccev:InformationRequirement → epo:Procedure [0..&#42;] +
epo:ProcurementProcessInformation → epo:Procedure [0..1]

  

  
  
| epo:hasPreferredLanguageForProcurementDocument| 
  Relation indicating the language in which the Procurement Documents should be submitted.|epo:ExpressionOfInterest → at-voc:language [0..&#42;]

  

  
  
| epo:specifiesEconomicOperator| 
  Relation indicating that the instance of the concept involves the Economic Operator.|epo:ExpressionOfInterest → epo:OfferingParty [0..&#42;]

  

  
  
  

  
  
  

  
  
| epo:hasFrameworkAgreementType| 
  The form of framework agreement used in a procurement procedure. Addition information: A concept to distinguish the different types of framework agreement, which are: 1. Framework agreement without reopening of competition, 2. Framework agreement with reopening of competition, or 3. Framework agreement partly without reopening of competition.|epo:FrameworkAgreementTerm → at-voc:framework-agreement [1]

  

  
  
  

  
  
| epo:hasFundProgramme| 
  Relation indicating the EU programme used for funding.|epo:Fund → at-voc:EU-programme [0..1]

  

  

  

  

  
  
| epo:fulfillsRequirement| 
  The requirement to which the concept meets.|epo:GreenProcurement → at-voc:green-public-procurement-criteria [0..&#42;] +
epo:GreenProcurement → at-voc:environmental-impact [0..&#42;] +
epo:InnovativeProcurement → at-voc:innovative-acquisition [0..&#42;] +
epo:SocialProcurement → at-voc:social-objective [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
  

  

  

  

  
  
| epo:hasConstraint| 
  Relation indicating that the instance of the concept has a Constraint.|cccev:InformationRequirement → cccev:Constraint [0..&#42;] +
epo:ProcurementCriterion → cccev:Constraint [0..&#42;]

  

  

  

  
  
| epo:concernsInternationalProcurementInstrumentMeasure| 
  Relates to International Procurement Instrument Measure.|epo:InternationalProcurementInstrumentMeasuresInformation → at-voc:international-procurement-instrument-measure [0..1]

  

  
  
| epo:concernsLotAwardOutcome| 
  Relates to Lot Award Outcome.|epo:InternationalProcurementInstrumentMeasuresInformation → epo:LotAwardOutcome [0..&#42;]

  

  
  
| epo:hasInternationalProcurementInstrumentExceptionInformation| 
  Relation indicating the International Procurement Instrument Application.|epo:InternationalProcurementInstrumentMeasuresInformation → at-voc:international-procurement-instrument-application [0..1]

  

  
  
  

  
  
  

  
  
| epo:concernsProcurementElement| 
  Relates to Procurement Element.|epo:LocalLegalBasisInformation → epo:ProcurementElement [1]

  

  
  
| epo:hasLegalBasis| 
  The legal basis under which the procurement procedure takes place. Additional Information: For example European Directives or Regulations, national laws etc. The recommended code list is the example for the legal basis at the European level.|epo:LocalLegalBasisInformation → at-voc:legal-basis [0..1] +
epo:ProcurementElement → at-voc:legal-basis [0..&#42;]

  

  

  

  

  
  
| epo:fulfillsStrategicProcurement| 
  Relation indicating that the concept has a Strategic Procurement goal.|epo:LotAwardOutcome → epo:StrategicProcurement [0..&#42;] +
epo:ProcurementObject → epo:StrategicProcurement [0..&#42;]

  

  
  
| epo:hasApproximateFrameworkAgreementValue| 
  The estimated value to be spent within the Framework Agreement(s). Additional information: In the case of an Award Decision for a Lot, this relation represents the estimated value for the awarded Framework Agreement. In the case of a Notice, this relation represents the estimated value for all Framework Agreements covered by the Notice.|epo:LotAwardOutcome → epo:MonetaryValue [0..1] +
epo:NoticeAwardInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:hasFrameworkAgreementMaximumValue| 
  Relation indicating the maximum Monetary Value of the Framework Agreement.|epo:LotAwardOutcome → epo:MonetaryValue [0..1]

  

  
  
  

  
  
  

  
  
| epo:hasEstimatedValue| 
  A forecast of the value of the procurement before competition. Additional Information: Different cases of estimated values may refer to a lot, the global value of the procedure, or of a combinatorial value of a group of lots. The forecast is calculated by the buyer and covers all revenues whether coming from the buyer or third parties. See for example recital (19), Article 5 of Directive 2014/24/EU and other articles from the rest of Directives about procurement. In the case of framework agreements and dynamic purchasing systems this refers to the maximum estimated value.|epo:LotGroup → epo:MonetaryValue [0..1] +
epo:ProcurementElement → epo:MonetaryValue [0..1]

  

  
  
| epo:hasInternalIdentifier| 
  Relation indicating the in-house Identifier used by an Organization.|epo:LotGroup → adms:Identifier [0..&#42;] +
epo:ProcurementElement → adms:Identifier [0..&#42;]

  

  
  
| epo:hasLaunchFrameworkAgreementMaximumValue| 
  Relation indicating that the maximum value allowed for a Framework Agreement as defined by the Buyer at the outset.|epo:LotGroup → epo:MonetaryValue [0..1] +
epo:ProcurementObject → epo:MonetaryValue [0..1]

  

  
  
  

  
  
| epo:setsGroupingContextForLot| 
  Incorporates Lot.|epo:LotGroup → epo:Lot [1..&#42;]

  

  
  
| epo:specifiesProcurementCriterion| 
  Relation indicating the Procurement Criterion to be used.|epo:LotGroup → epo:ProcurementCriterion [0..&#42;] +
epo:ProcurementElement → epo:ProcurementCriterion [0..&#42;]

  

  
  
| epo:describesLotGroup| 
  Characterises Lot Group.|epo:LotGroupAwardInformation → epo:LotGroup [1]

  

  
  
| epo:hasApproximateGroupFrameworkAgreementValue| 
  Relation indicating the estimated Monetary Value of the Lot Group within the Framework Agreement.|epo:LotGroupAwardInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:hasGroupFrameworkAgreementMaximumValue| 
  Relation indicating the maximum Monetary Value of the Lot Group within the Framework Agreement.|epo:LotGroupAwardInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:resultsFromUsingCandidateList| 
  Relation to indicate that a given type of Mini Competition Award Outcome is a consequence from using a given Selected Candidate List.|epo:MiniCompetitionAwardOutcome → epo:SelectedCandidateList [0..1]

  

  
  
  

  
  
| epo:hasCurrency| 
  The identifier of the currency as in the standard code list used.|epo:MonetaryValue → at-voc:currency [1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasQualificationSystemDuration| 
  Relation indicating a Qualification System has a Duration.|epo:MultipleStageProcedureTerm → time:Duration [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:concernsMaskedObject| 
  Relates to Masked Object.|epo:NonPublishedInformation → epo:MaskableObject [1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasNonPublicationJustification| 
  The reason why data is not published.|epo:NonPublishedInformation → at-voc:non-publication-justification [1]

  

  
  
| epo:conformsToLegalBasis| 
  The Notice was designed in accordance with the given legal basis. Additional Information: This Notice can be used for Procedures which do not have the same legal basis. This holds for standard forms.|epo:Notice → at-voc:legal-basis [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasFormType| 
  A categorisation of the steps in which the Notice is used.|epo:Notice → at-voc:form-type [0..1]

  

  
  
  

  
  
| epo:hasNoticeType| 
  Relation indicating the Notice Type.|epo:Notice → at-voc:notice-type [1]

  

  
  
| epo:isBasedOnImplementingRegulation| 
  Indicates under which Implementing Regulation a Notice is created.|epo:Notice → at-voc:legal-basis [0..1]

  

  
  
| epo:refersToLot| 
  Reference to a Lot.|epo:Notice → epo:Lot [0..&#42;]

  

  
  
| epo:refersToNotice| 
  Reference to a Notice.|epo:Notice → epo:Notice [0..1]

  

  
  
| epo:refersToProcedure| 
  Reference to a Procedure.|epo:Notice → epo:Procedure [0..1]

  

  
  
| epo:describesDirectAwardPrenotificationNotice| 
  Characterises Direct Award Prenotification Notice.|epo:NoticeAwardInformation → epo-not:DirectAwardPrenotificationNotice [0..1]

  

  
  
| epo:describesResultNotice| 
  Characterises Result Notice.|epo:NoticeAwardInformation → epo-not:ResultNotice [0..1]

  

  
  
| epo:hasMaximumFrameworkAgreementAwardedValue| 
  The maximum value which can be spent through all the framework agreements announced in this notice, including options and renewals of contracts. Additional information: The value provided is a threshold value that implicity means that it cannot be exceeded however it may not be reached during the execution of a contract. The Framework Agreements in a CAN are to be traced back and added to provide this value.|epo:NoticeAwardInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:hasProcurementHighestReceivedTenderValue| 
  The highest received tender value for the procurement. Additional Information: This corresponds to section II.1.7.3. according to Regulation (EU) 2015/1986.|epo:NoticeAwardInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:hasProcurementLowestReceivedTenderValue| 
  The lowest received tender value for the procurement. Additional Information: This corresponds to section II.1.7.2. according to Regulation (EU) 2015/1986.|epo:NoticeAwardInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:hasTotalAwardedValue| 
  The awarded value of all lots announced in this notice, including options and renewals. Additional information: The values of the individual Lots awarded under a framework agreement and mentioned in this notice are included. The values of the individual lots announced in a CAN are to be traced back and added to provide this value.|epo:NoticeAwardInformation → epo:MonetaryValue [0..1]

  

  
  
| epo:providesEvidence| 
  Makes available the Evidence.|epo:Offer → cccev:Evidence [1]

  

  
  
| epo:distributesOffer| 
  Sends the Offer.|epo:OfferIssuer → epo:Offer [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo-ord:comprisesOrderLine| 
  Incorporates Order Line.|epo-ord:Order → epo-ord:OrderLine [0..&#42;]

  

  
  
  

  
  
| epo-ord:hasAmountDueForPayment| 
  Relation indicating the Monetary Value that has to be paid.|epo-ord:Order → epo:MonetaryValue [1] +
epo-ord:Order → epo:MonetaryValue [1]

  

  
  
  

  
  
| epo-ord:hasPrepaidAmount| 
  Relation indicating the Monetary Value that is paid in advance.|epo-ord:Order → epo:MonetaryValue [0..1] +
epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasRoundingAmount| 
  Relation indicating the adjustment Monetary Value applied to bring calculated total to a convenient value.|epo-ord:Order → epo:MonetaryValue [0..1] +
epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasSellerOrderID| 
  The identifier of the Order given by the Seller. Additional Information: This identifier is different than the identifier of the Order given by the Buyer and it is useful for internal purposes.|epo-ord:Order → adms:Identifier [0..1] +
epo-ord:Order → adms:Identifier [0..1]

  

  
  
| epo-ord:hasTotalAllowanceAmount| 
  Relation indicating the overall Monetary Value of the Allowance.|epo-ord:Order → epo:MonetaryValue [0..1] +
epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasTotalChargeAmount| 
  Relation indicating the overall Monetary Value of the Charge.|epo-ord:Order → epo:MonetaryValue [0..1] +
epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasTotalLineAmount| 
  Relation indicating the overall Monetary Value of the Line.|epo-ord:Order → epo:MonetaryValue [1] +
epo-ord:Order → epo:MonetaryValue [1]

  

  
  
| epo-ord:hasTotalTaxExclusiveAmount| 
  Relation indicating the overall Monetary Value without Tax.|epo-ord:Order → epo:MonetaryValue [0..1] +
epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasTotalTaxInclusiveAmount| 
  Relation indicating the overall Monetary Value with Tax.|epo-ord:Order → epo:MonetaryValue [0..1] +
epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo:refersToProject| 
  Reference to a Project.|epo-ord:Order → epo:Project [0..1] +
epo-ord:Order → epo:Project [0..1]

  

  
  
| epo-ord:specifiesAllowanceInformation| 
  Relation indicating the Allowance Information.|epo-ord:Order → epo-ord:AllowanceInformation [0..&#42;]

  

  
  
| epo:specifiesBuyer| 
  Relation indicating that the instance of the concept involves the Buyer.|epo-ord:Order → epo:Buyer [1] +
epo-ord:Order → epo:Buyer [1] +
epo-ord:OrderCancellation → epo:Buyer [1] +
epo-ord:OrderCancellation → epo:Buyer [1] +
epo-ord:OrderCancellationConfirmation → epo:Buyer [1] +
epo-ord:OrderCancellationConfirmation → epo:Buyer [1] +
epo-ord:OrderCancellationRejection → epo:Buyer [1] +
epo-ord:OrderCancellationRejection → epo:Buyer [1] +
epo-ord:OrderChangeConfirmation → epo:Buyer [1] +
epo-ord:OrderChangeConfirmation → epo:Buyer [1] +
epo-ord:OrderChangeRejection → epo:Buyer [1] +
epo-ord:OrderChangeRejection → epo:Buyer [1]

  

  
  
| epo-cat:specifiesChargeInformation| 
  Relation indicating the Charge Information.|epo-ord:Order → epo-cat:ChargeInformation [0..&#42;]

  

  
  
| epo-ord:specifiesContractInformation| 
  Relation indicating the Contract Information.|epo-ord:Order → epo-ord:ContractInformation [0..&#42;]

  

  
  
| epo-ord:specifiesDeliveryInformation| 
  Relation indicating the Delivery Information.|epo-ord:Order → epo-ord:DeliveryInformation [0..&#42;]

  

  
  
| epo-ful:specifiesDespatcher| 
  Relation indicating that the instance of the concept involves the Despatcher.|epo-ord:Order → epo-ful:Despatcher [0..1]

  

  
  
| epo:specifiesInvoicee| 
  Relation indicating that the instance of the concept involves the Invoicee.|epo-ord:Order → epo-ord:Invoicee [0..1]

  

  
  
| epo-ord:specifiesOriginatorInformation| 
  Relation indicating the Originator Information.|epo-ord:Order → epo-ord:OriginatorInformation [0..1]

  

  
  
| epo:specifiesSeller| 
  Relation indicating that the instance of the concept involves the Seller.|epo-ord:Order → epo-ord:Seller [1] +
epo-ord:OrderCancellation → epo-ord:Seller [1] +
epo-ord:OrderCancellationConfirmation → epo-ord:Seller [1] +
epo-ord:OrderCancellationRejection → epo-ord:Seller [1] +
epo-ord:OrderChangeConfirmation → epo-ord:Seller [1] +
epo-ord:OrderChangeRejection → epo-ord:Seller [1]

  

  
  
| epo-ord:comprisesOrderAgreementLine| 
  Incorporates Order Agreement Line.|epo-ord:OrderAgreement → epo-ord:OrderAgreementLine [0..&#42;]

  

  
  
| epo-ord:isSubmittedForOrder| 
  Relation indicating that the instance of the concept is sent for a specific Order.|epo-ord:OrderCancellation → epo-ord:Order [1] +
epo-ord:OrderChange → epo-ord:Order [1] +
epo-ord:OrderResponse → epo-ord:Order [1]

  

  
  
| epo-ord:respondsToOrderCancellation| 
  Takes action in reaction to an Order Cancellation.|epo-ord:OrderCancellationConfirmation → epo-ord:OrderCancellation [0..1] +
epo-ord:OrderCancellationRejection → epo-ord:OrderCancellation [0..1]

  

  
  
| epo-ord:comprisesOrderChangeLine| 
  Incorporates Order Change Line.|epo-ord:OrderChange → epo-ord:OrderChangeLine [0..&#42;]

  

  
  
| epo-ord:respondsToOrderChange| 
  Takes action in reaction to an Order Change.|epo-ord:OrderChangeConfirmation → epo-ord:OrderChange [1] +
epo-ord:OrderChangeRejection → epo-ord:OrderChange [1]

  

  
  
| epo-ord:hasStatus| 
  Relation indicating the status.|epo-ord:OrderChangeLine → at-voc-new:ResponseStatus [0..1] +
epo-ord:OrderResponseInformation → at-voc-new:ResponseStatus [1]

  

  
  
| epo-ord:isSubmittedForOrderLine| 
  Relation indicating that the instance of the concept is sent for a specific Order Line.|epo-ord:OrderChangeLine → epo-ord:OrderLine [1] +
epo-ord:OrderResponseLine → epo-ord:OrderLine [1]

  

  
  
| epo-cat:hasPrice| 
  Relation indicating that the instance of the concept has a Price.|epo-ord:OrderLine → epo-cat:Price [0..&#42;]

  

  
  
| epo-cat:hasQuantity| 
  Relation indicating that the instance of the concept has a Quantity.|epo-ord:OrderLine → epo:Quantity [1] +
epo-ord:OrderLine → epo:Quantity [1]

  

  
  
| epo-ord:refersToCatalogueLine| 
  Additional Information: The reference to the catalogue line is for information only, to trace the source of the information provided in the order line.|epo-ord:OrderLine → epo-cat:CatalogueLine [0..1]

  

  
  
| epo-ord:comprisesOrderResponseLine| 
  Incorporates Order Response Line.|epo-ord:OrderResponse → epo-ord:OrderResponseLine [0..&#42;]

  

  
  
  

  
  
| epo-ord:specifiesOrderResponseInformation| 
  Relation indicating the Order Response Information.|epo-ord:OrderResponse → epo-ord:OrderResponseInformation [0..&#42;]

  

  
  
| epo-ord:isSpecificToOrderResponseLine| 
  Information that is particular to an Order Response Line.|epo-ord:OrderResponseInformation → epo-ord:OrderResponseLine [0..&#42;]

  

  
  
| epo-ord:hasBackorderQuantity| 
  Relation indicating the number of Items that cannot be fulfilled immediately.|epo-ord:OrderResponseLine → epo:Quantity [0..1] +
epo-ord:OrderResponseLine → epo:Quantity [0..1]

  

  
  
  

  
  
| epo:hasMember| 
  Relation indicating a part of the instance of the concept.|epo:OrganisationGroup → org:Organization [1..&#42;]

  

  
  
| epo:leadBy| 
  The epo:OrganisationGroup epo:leadBy org:Organization was implemented to be used in case of an Economic Operator Group.|epo:OrganisationGroup → org:Organization [0..1]

  

  
  
| epo:canProvideEvidence| 
  Relation showing that an Organization can supply an Evidence with regard to the payment of social security contributions and taxes.|org:Organization → cccev:Evidence [0..&#42;]

  

  
  
| epo:canProvideNonDiscriminatoryEvidence| 
  Relation showing that an Organization can supply an Evidence with regard to the fulfilment of non-discriminatory criteria or the rules applied in order to reduce the number of participants.|org:Organization → cccev:Evidence [0..&#42;]

  

  
  
| epo:hasBuyerLegalType| 
  A category that indicates the right of an Organisation to play the role of a buyer. Additional Information: The category also effects the rules that the buyer has to abide to within the public procurement procedure.|org:Organization → at-voc:buyer-legal-type [0..1]

  

  
  
  

  
  
  

  
  
| epo:hasLegalIdentifier| 
  The officially registered Identifier.|org:Organization → adms:Identifier [0..&#42;]

  

  
  
  

  
  
| epo:hasMainActivity| 
  The principal sectoral area in which an organisation operates. Additional information: The activities associated with buyers are derived from the top level of the Classification of the functions of the government (COFOG) from the United Nations Statistics Division. The activities associated with buyer are derived from sectors explicitly falling within the sectoral directive (2014/25/EU Art. 8 - Art. 14).|org:Organization → at-voc:main-activity [0..&#42;]

  

  
  
  

  
  
| epo:hasPrimaryContactPoint| 
  Relation indicating the main Contact Point.|org:Organization → cpov:ContactPoint [0..1]

  

  
  
| epo:hasRegistrationCountry| 
  Relation indicating the official country.|org:Organization → at-voc:country [0..1]

  

  
  
| epo:hasTaxIdentifier| 
  Relation indicating the Identifier used for Tax purposes.|org:Organization → adms:Identifier [0..&#42;]

  

  

  

  

  
  
| epo-ord:concernsOriginator| 
  Relates to Originator.|epo-ord:OriginatorInformation → epo-ord:Originator [1]

  

  
  
| epo-ord:concernsOriginatorRequest| 
  Relates to Originator Request.|epo-ord:OriginatorInformation → epo:OriginatorRequest [0..1] +
epo-ord:OriginatorInformation → epo:OriginatorRequest [0..1]

  

  
  
| epo:hasReservedProcurement| 
  Explanation as to whether a procurement may be reserved for the participation of certain types of organisation.|epo:ParticipationCondition → at-voc:reserved-procurement [0..&#42;] +
epo:ParticipationConditionsSummary → at-voc:reserved-procurement [0..&#42;]

  

  
  
  

  
  
  

  
  
| epo:definesParticipationRequestProcessor| 
  Relation indicating a ParticipationRequestTerm has a ParticipationRequestProcessor.|epo:ParticipationRequestTerm → epo:ParticipationRequestProcessor [0..1]

  

  
  
| epo:definesParticipationRequestReceiver| 
  Relation indicating a ParticipationRequestTerm has a ParticipationRequestReceiver.|epo:ParticipationRequestTerm → epo:ParticipationRequestReceiver [0..1]

  

  

  

  

  

  

  
  
| epo:hasCountryOfBirth| 
  The country in which the Person was born.|person:Person → at-voc:country [0..1]

  

  
  
| epo:hasNationality| 
  Relation indicating the country code to which the instance of the concept officially belongs to.|person:Person → at-voc:country [0..&#42;]

  

  
  
| epo:isBeneficialOwnerOf| 
  A role of any natural person(s) who ultimately owns or controls the organisation or on whose behalf a transaction or activity is being conducted. Additional Information: This role is defined in the directive EU 2015/849 and it's beyond the scope for public eProcurement domain.|person:Person → epo:Business [0..&#42;]

  

  

  

  
  
| epo:foreseesProcurementObject| 
  Relation indicating the instance of a Procurement Object that is planned. Additional Information: The properties of the Procurement Object that is foreseen should be read as foreseen properties. For example, Procedure isSMESuitable should be read as Procedure foreseesToBeSMESuitable. For example, Procedure isFundedBy should be read as Procedure foreseesToBeFundedBy.|epo:PlannedProcurementPart → epo:ProcurementObject [0..1]

  

  
  
| epo:foreseesTechnique| 
  Relation indicating that an instance of the concept plans to apply a Technique.|epo:PlannedProcurementPart → epo:Technique [0..&#42;]

  

  
  
| epo:hasPlannedDuration| 
  Relation indicating the foreseen Duration.|epo:PlannedProcurementPart → time:Duration [0..1]

  

  
  
| epo:hasPlannedPeriod| 
  Relation indicating the foreseen time range.|epo:PlannedProcurementPart → time:Interval [0..1]

  

  
  
  

  
  
| epo:hasPrizeValue| 
  The monetary value of a prize, if any, for the winner (or runners-up) of the design contest.|epo:Prize → epo:MonetaryValue [0..1]

  

  
  
  

  
  
  

  
  
| epo:hasProcedureType| 
  Identification of the Procedure used.|epo:Procedure → at-voc:procurement-procedure-type [0..1]

  

  
  
| epo:hasProcurementScopeDividedIntoLot| 
  Defines Lot.|epo:Procedure → epo:Lot [1..&#42;]

  

  
  
| epo:involvesBuyer| 
  Requires Buyer.|epo:Procedure → epo:Buyer [0..&#42;]

  

  
  
  

  
  
  

  
  
| epo:isExecutedByProcurementServiceProvider| 
  Relation indicating the Procurement Service Provider that carries out the instance of the concept.|epo:Procedure → epo:ProcurementServiceProvider [0..1]

  

  
  
  

  
  
| epo:isResponsibilityOfBuyer| 
  The buyer in charge of the procedure. Additional Information: In case there are multiple buyers, it may be the case that one or more buyers are in charge of the procedure.|epo:Procedure → epo:Buyer [0..&#42;]

  

  
  
| epo:specifiesProcurementCriteriaSummary| 
  Relation indicating the Procurement Criteria Summary to be used.|epo:Procedure → epo:ProcurementCriteriaSummary [0..&#42;]

  

  
  
| epo:definesBudgetProvider| 
  Relation indicating a ProcedureTerm has a BudgetProvider.|epo:ProcedureTerm → epo:BudgetProvider [0..1]

  

  
  
| epo:definesInformationProvider| 
  Relation indicating a ProcedureTerm has an information provider.|epo:ProcedureTerm → epo:AuxiliaryParty [0..&#42;]

  

  
  
| epo:definesLotGroup| 
  Relation indicating a ProcedureTerm has a LotGroup.|epo:ProcedureTerm → epo:LotGroup [0..&#42;]

  

  
  
| epo:definesMediator| 
  Relation indicating a ProcedureTerm has a Mediator.|epo:ProcedureTerm → epo:Mediator [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasWeightValueType| 
  No definition. Waiting on CCCEV alignment.|epo:ProcurementCriterion → at-voc:number-weight [0..1]

  

  
  
  

  
  
| epo:doesNotRequireSelectionCriterionType| 
  Relation indicating that a Selection Criterion type is not used.|epo:ProcurementElement → at-voc:selection-criterion [0..&#42;]

  

  
  
| epo:foreseesTerm| 
  Relation indicating that an instance of the concept plans to be subject to a Term.|epo:ProcurementElement → epo:Term [0..&#42;]

  

  
  
  

  
  
| epo:hasUnknownUsageOfSelectionCriterionType| 
  Relation indicating that it is not known whether a Selection Criterion type is to be used or not.|epo:ProcurementElement → at-voc:selection-criterion [0..&#42;]

  

  
  
  

  
  
| epo:usesChannel| 
  Relation indicating the Channel to be utilised.|epo:ProcurementElement → cv:Channel [0..&#42;]

  

  
  
| epo:foreseesConcession| 
  Relation indicating that an instance of the concept plans to have a Concession.|epo:ProcurementObject → epo:ConcessionEstimate [0..1] +
epo:Tender → epo:ConcessionEstimate [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:usesTechnique| 
  Relation indicating that a Technique is being applied.|epo:ProcurementObject → epo:Technique [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:actsOnBehalfOf| 
  Represents.|epo:ProcurementServiceProvider → epo:Buyer [1..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:followsRulesSetBy| 
  Complies with established norms.|epo:PurchaseContract → epo:FrameworkAgreement [0..1]

  

  
  
| epo:resultsFromMiniCompetitionAwardOutcome| 
  Relation to indicate that a given type of Purchase Contract is a consequence of a given Mini Competition Award Outcome.|epo:PurchaseContract → epo:MiniCompetitionAwardOutcome [0..1]

  

  
  
| epo:hasAdditionalClassification| 
  Relation indicating the additional Common Procurement Vocabulary code.|epo:Purpose → at-voc:cpv [0..&#42;]

  

  
  
| epo:hasMainClassification| 
  Relation indicating the main Common Procurement Vocabulary code.|epo:Purpose → at-voc:cpv [1..&#42;]

  

  
  
| epo:hasTotalQuantity| 
  The number of units required. Additional Information: The quantity needs to go along with the unit.|epo:Purpose → epo:Quantity [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:includesNationalCriterion| 
  Relation indicating that a Criterion contains a Criterion that is specific to a given Member State. Additional Information: In the ESPD, a Subcriterion is used to define national sub-criteria; maps to a UBL-2.3 cac:SubTenderingCriterion class. It is currently used only for purely national criteria, to be able to establish the mapping from eCertis.|epo:QualificationCriterion → epo:QualificationCriterion [0..&#42;]

  

  
  
| epo:concernsContractTerm| 
  Relates to Contract Term.|epo:QualityTargetInformation → epo:ContractTerm [1]

  

  
  
| epo:hasQualityTargetCode| 
  Relation indicating the type of performance goal.|epo:QualityTargetInformation → at-voc:customer-service [1]

  

  
  
  

  
  
  

  
  
| epo:hasUnitCode| 
  Relation indicating the Measurement Unit.|epo:Quantity → at-voc:measurement-unit [0..1]

  

  
  
  

  

  

  

  

  
  
| epo:answersReviewRequest| 
  Responds to a Review Request.|epo:ReviewDecision → epo:ReviewRequest [0..&#42;]

  

  
  
| epo:hasConfirmedIrregularityType| 
  Relation indicating the confirmed Irregularity Type.|epo:ReviewDecision → at-voc:irregularity-type [0..&#42;]

  

  
  
| epo:hasRemedyValue| 
  Relation indicating the Monetary Value of a compensation, penalty, or corrective measure applied when a contract, obligation, or agreement is breached or not fulfilled.|epo:ReviewDecision → epo:MonetaryValue [0..1]

  

  
  
| epo:hasReviewDecisionType| 
  Relation indicating the Review Decision Type.|epo:ReviewDecision → at-voc:review-decision-type [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:providesRulingOnRemedy| 
  States the measures to be taken after a review procedure.|epo:ReviewDecision → at-voc:remedy-type [0..&#42;]

  

  
  
| epo:specifiesReviewRequester| 
  Relation indicating that the instance of the concept involves the Review Requester.|epo:ReviewDecision → epo:ReviewRequester [0..1] +
epo:ReviewRequest → epo:ReviewRequester [0..1]

  

  
  
| epo:specifiesReviewer| 
  Relation indicating that the instance of the concept involves the Reviewer.|epo:ReviewDecision → epo:Reviewer [0..1]

  

  
  
| epo:hasIrregularityType| 
  Relation indicating the Irregularity Type.|epo:ReviewIrregularitySummary → at-voc:irregularity-type [1]

  

  
  
  

  
  
| epo:hasAllegedIrregularityType| 
  Relation indicating the presumed Irregularity Type.|epo:ReviewRequest → at-voc:irregularity-type [1..&#42;]

  

  
  
| epo:hasReviewRequestFee| 
  Relation indicating the charge or cost required for processing the Review Request.|epo:ReviewRequest → epo:MonetaryValue [0..1]

  

  
  
| epo:requestsRemedyType| 
  Relation indicating the demanded Remedy Type.|epo:ReviewRequest → at-voc:remedy-type [0..&#42;]

  

  
  
| epo:concernsReviewSummaryForLot| 
  Relates to Lot review summary.|epo:ReviewRequestSummary → epo:Lot [1]

  

  
  
  

  
  
| epo:hasReviewIrregularitySummary| 
  Relation indicating the Review Irregularity Summary.|epo:ReviewRequestSummary → epo:ReviewIrregularitySummary [0..&#42;]

  

  
  
  

  
  
| epo:definesReviewProcedureInformationProvider| 
  Relation indicating a ReviewTerm has a ReviewProcedureInformationProvider.|epo:ReviewTerm → epo:ReviewProcedureInformationProvider [0..1]

  

  
  
| epo:definesReviewer| 
  Relation indicating a ReviewTerm has a Reviewer.|epo:ReviewTerm → epo:Reviewer [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasReviewBodyType| 
  Relation indicating the Review Body Type.|epo:Reviewer → at-voc:review-body-type [0..&#42;]

  

  
  
  

  
  
  

  
  
| epo:containsCandidate| 
  Includes Candidate.|epo:SelectedCandidateList → epo:Candidate [0..&#42;]

  

  
  
| epo:hasStartDate| 
  Relation indicating the beginning date.|epo:SelectedCandidateList → time:Interval [0..1]

  

  
  
  

  
  
  

  
  
| epo:hasSelectionCriterionType| 
  The classification of the selection criteria.|epo:SelectionCriterion → at-voc:selection-criterion [0..1]

  

  
  
  

  
  
  

  
  
| epo:includesAccessibilityCriterion| 
  Explanation as to whether accessibility Criterion are used or not.|epo:SocialProcurement → at-voc:accessibility [0..&#42;]

  

  
  
| epo:hasSourceSpecificationCustomisation| 
  Relation indicating the Identifier of a tailored version of a standard.|epo:SpecificationInformation → adms:Identifier [0..1]

  

  
  
| epo:hasSourceVersionSpecification| 
  Relation indicating the Identifier of the standard used and its version.|epo:SpecificationInformation → adms:Identifier [0..1]

  

  
  
| epo:isUsedInProfile| 
  Relation indicating the profile Identifier.|epo:SpecificationInformation → adms:Identifier [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasSubcontractingObligation| 
  The requirement the tender must meet with regard to subcontracting parts of the contract.|epo:SubcontractTerm → at-voc:subcontracting-obligation [0..&#42;]

  

  
  
  

  
  
  

  
  
| epo:hasSubcontractingEstimatedValue| 
  The estimated value of a single subcontract.|epo:SubcontractingEstimate → epo:MonetaryValue [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasHighestReceivedTenderValue| 
  Amount of the Tender with the highest value. Additional Information The value must correspond to an admissible tender. For example, tenders compliant with the procurement document requirements, not having an abnormally low price or cost, etc.|epo:SubmissionStatisticalInformation → epo:MonetaryValue [0..1]

  

  
  
  

  
  
| epo:hasLowestReceivedTenderValue| 
  Amount of the Tender with the lowest value. Additional Information The value must correspond to an admissible tender. For example, tenders compliant with the procurement document requirements, not having an abnormally low price or cost, etc.|epo:SubmissionStatisticalInformation → epo:MonetaryValue [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:summarisesInformationForAwardOutcome| 
  Relates to submission for the given competition, either at Lot level or Mini-Competition level.|epo:SubmissionStatisticalInformation → epo:AwardOutcome [1]

  

  
  
| epo:definesTenderProcessor| 
  Relation indicating a SubmissionTerm has a TenderProcessor.|epo:SubmissionTerm → epo:TenderProcessor [0..1]

  

  
  
| epo:definesTenderReceiver| 
  Relation indicating a SubmissionTerm has a TenderReceiver.|epo:SubmissionTerm → epo:TenderReceiver [0..1]

  

  
  
  

  
  
| epo:hasECataloguePermission| 
  The extent to which electronic catalogues may be used in tenders.|epo:SubmissionTerm → at-voc:permission [0..1]

  

  
  
| epo:hasESubmissionPermission| 
  The requirements as to what extent electronic submission is allowed.|epo:SubmissionTerm → at-voc:permission [0..1]

  

  
  
  

  
  
| epo:hasLanguage| 
  Language in which the submitted information is to be expressed.|epo:SubmissionTerm → at-voc:language [0..&#42;]

  

  
  
  

  
  
| epo:hasLateSubmissionPermission| 
  Whether economic operator-related information can be supplemented even after the submission deadline. Additional Information This is specific to the information on the economic operator and not the actual offer. This does not apply to the requests for clarification.|epo:SubmissionTerm → at-voc:missing-info-submission [0..1]

  

  
  
  

  
  
| epo:hasNonElectronicSubmissionJustification| 
  Reason for not accepting electronic information.|epo:SubmissionTerm → at-voc:communication-justification [0..&#42;]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo:hasTenderSubcontractingInformation| 
  The information about subcontracting that must be indicated in the tender.|epo:SubmissionTerm → at-voc:subcontracting-indication [0..&#42;]

  

  
  
| epo:hasTenderValidityDuration| 
  Relation indicating the length of time a Tender remains valid.|epo:SubmissionTerm → time:Duration [0..1]

  

  
  
| epo:hasTenderValidityPeriod| 
  The relation indicating until when a tender instance is applicable.|epo:SubmissionTerm → time:Interval [0..1]

  

  
  
| epo:hasVariantPermission| 
  The obligation or possibility for tenderers to submit variants or not. Additional Information: Variants are alternative ways to fulfil the buyer's needs as opposed to solutions indicated in the procurement documents. eForms: Whether tenderers are required, allowed or forbidden to submit tenders which fulfil the buyer's needs differently than as proposed in the procurement documents. Additional Information: Further conditions for submitting variant tenders are in the procurement documents.|epo:SubmissionTerm → at-voc:permission [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
| epo:isOwnedByAgent| 
  Relation indicating the System over which the instance of the concept holds the legal rights. Relation indicating the Agent who holds the legal rights over the instance of the concept.|epo:System → foaf:Agent [0..1]

  

  
  
| epo-cat:hasTaxCategory| 
  Relation indicating the Tax Category.|epo-ord:TaxInformation → at-voc-new:tax-category [0..1]

  

  
  
| epo-cat:hasTaxScheme| 
  Relation indicating the Tax Scheme.|epo-ord:TaxInformation → at-voc-new:tax-scheme [1]

  

  
  
| epo:hasEstimatedValidityPeriod| 
  Relation indicating the time range in which the instance of the concept is valid.|epo:Technique → time:Interval [0..1]

  

  

  

  

  

  
  
| epo:foreseesSubcontracting| 
  Relation indicating that an instance of the concept plans to be Subcontracted.|epo:Tender → epo:SubcontractingEstimate [0..&#42;]

  

  
  
  

  
  
| epo:hasFinancialOfferValue| 
  The value offered by the Tenderer for a Lot. Additional Information: This value is normally the one awarded for a winning Tender Lot. In case of negotiated procedures the original financial value may be reviewed and the offer updated.|epo:Tender → epo:MonetaryValue [0..1]

  

  
  
| epo:hasSubcontracting| 
  Relation indicating whether the Tender is subject to Subcontracting or not.|epo:Tender → at-voc:applicability [0..1]

  

  
  
| epo:isSubjectToGrouping| 
  Relation indicating that the instance of the concept belongs to a Group.|epo:Tender → epo:LotGroup [0..1]

  

  
  
| epo:isSubmittedBy| 
  Relation indicating the submission of a tender by an economic operator.|epo:Tender → epo:Tenderer [0..1]

  

  
  
| epo:isSubmittedForLot| 
  Relation indicating that the instance of the concept is formally sent for a Lot.|epo:Tender → epo:Lot [1]

  

  
  
| epo:isSupportedBy| 
  Relation indicating the proof for the instance of the concept.|epo:Tender → epo:Offer [0..1]

  

  
  
  

  
  
| epo:concernsTender| 
  Relates to Tender.|epo:TenderAwardOutcome → epo:Tender [1]

  

  
  
  

  
  
| epo:indicatesAwardToWinner| 
  Reveals the winner to whom the tender award outcome is attributed.|epo:TenderAwardOutcome → epo:Winner [0..1]

  

  
  
| epo:specifiesForeignSubsidiesMeasureConclusion| 
  Relation indicating the Foreign Subsidy Measure Conclusion.|epo:TenderAwardOutcome → at-voc:foreign-subsidy-measure-conclusion [0..1]

  

  
  
| epo:comprisesTender| 
  Incorporates Tender.|epo:TenderGroup → epo:Tender [1..&#42;]

  

  
  
| epo:hasTotalValue| 
  Relation indicating the overall Monetary Value.|epo:TenderGroup → epo:MonetaryValue [0..1]

  

  
  
| epo:isSubmittedForLotGroup| 
  Relation indicating that the instance of the concept is formally sent for a Lot Group.|epo:TenderGroup → epo:LotGroup [1]

  

  
  
| epo:substantiatesExclusionGround| 
  Demonstrates Exclusion Ground.|epo:Tenderer → epo:ExclusionGround [0..1]

  

  
  
| epo:signsAwardDecision| 
  Relation indicating the Award Decision that was signed.|epo:UniqueResponsibleOfTheProcurement → epo:AwardDecision [0..&#42;]

  

  
  
| epo:needsToBeATenderer| 
  The Winner must be a Tenderer.|epo:Winner → epo:Tenderer [0..1]

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].