



= Glossary

== Class names and definitions

[options="header"]
|===
| Class name | Definition

      
| epo-ord:AllowanceChargeInformation | Information about discounts, taxes, duties and fees imposed.
      
    
      
| epo-ord:AllowanceInformation | Information about the discounts imposed.
      
    
      
| epo-ord:Consignee | A Role of an Agent that receives the Shipment of the Procurement (service, goods or works) and who is taking possession. Additional information: The Role is carried out by the Customer or on behalf of the Customer. The possession of the goods does not necessary imply ownership. The Consignee may be the end-user or the beneficiary. (Consignee) Definition from PEPPOL Despatch: The Consignee is the person or Organisation to which the products will be shipped and who is taking possession. The Role is carried out by the Customer or on behalf of the Customer.
      
    
      
| epo-ord:ContractInformation | Information about the Contract.
      
    
      
| epo-ord:DeliveryAgreement | Term applying to the delivery of goods, services and works. Additional Information: Delivery terms identifier can normally be Incoterms accompanied by the description of specific conditions related to the delivery.
      
    
      
| epo-ord:DeliveryInformation | Information about the timing, the delivery destination, the delivery agreement and the involved parties.
      
    
      
| epo-ord:Invoicee | The Role of an Agent who receives and processes the Invoices.
      
    
      
| epo-ord:Order | A formal request of the Buyer to the Seller specifying the goods, services or works to be delivered. Additional Information: A Buyer submits an Order for delivery of goods, services or works to a Seller.
      
    
      
| epo-ord:OrderAgreement | A Document sent from the Seller to Buyer specifying the goods, services or works to be delivered concerning a specific Order.
      
    
      
| epo-ord:OrderAgreementLine | Details concerning a given unit of goods, services or works mentioned in the Order Agreement.
      
    
      
| epo-ord:OrderCancellation | A Document providing information on the formal response from the Buyer to the Seller to cancel a previous Order or Order Change.
      
    
      
| epo-ord:OrderCancellationConfirmation | A Document providing information on the acknowledgment of the Order Cancellation.
      
    
      
| epo-ord:OrderCancellationRejection | A Document providing information on the non-acceptance of the Order Cancellation.
      
    
      
| epo-ord:OrderChange | A Document providing information on the formal request from the Buyer to the Seller specifying the requested change in goods, services or works to be delivered in respect to a previous Order.
      
    
      
| epo-ord:OrderChangeConfirmation | A Document providing information on the acknowledgment of the Order Change.
      
    
      
| epo-ord:OrderChangeLine | Details concerning a given unit of goods, services or works requested in the Order Change.
      
    
      
| epo-ord:OrderChangeRejection | A Document providing information on the non-acceptance of the Order Change.
      
    
      
| epo-ord:OrderLine | Details concerning a given unit of goods, services or works requested in the Order. Additional information: In general, an Order Line contains the Quantity and Price of the goods, services and goods requested in the Order. However, in certain cases, the Price may not be known, as the Price may fluctuate from one day to the other.
      
    
      
| epo-ord:OrderResponse | A formal reply from the Seller to the Buyer stating the Seller's ability to fulfil the order. Additional Information: The Order Response is used to inform on the acceptance or rejection of an Order or to make a counter-offer.
      
    
      
| epo-ord:OrderResponseInformation | Information about an Order Response.
      
    
      
| epo-ord:OrderResponseLine | Details concerning the Seller's ability to fulfil a given Order Line. Additional Information: The Order Response Line is used to inform on the acceptance or rejection of an Order Line or to make a counter-offer.
      
    
      
| epo-ord:Originator | A Role of an Agent that expresses the needs to trigger the Procurement. Additional Information: The Originator is often the end-user or the Beneficiary.
      
    
      
| epo-ord:OriginatorInformation | Information about the Originator of the Order.
      
    
      
| epo-ord:Seller | A Role of an Agent who transfers the ownership of the Procurement results (goods, services or works) to the Buyer. Additional information: A Role of an Agent that sells a Procurement Result (goods, services or work) to a Buyer. The Seller is bound by a Contract i.e. it has legal responsibility. The Seller may or may not be the same as the Supplier. The Seller may or may not issue the Invoice. The Seller may or may not be the owner of the credit owed by the Buyer.
      
    
      
| epo-ord:TaxInformation | Information about the imposition of mandatory levies required by law.
      
    
|===

== Attributes (datatype properties) names and definitions

[cols="20%,20%,40%,20%", options="header"]
|===
| Class name | Attribute name | Definition | Data type / cardinality




  
  
| epo-ord:AllowanceChargeInformation
| epo-ord:hasVATExemptionReason| 
  Explanation on why the instance of the concept is not subject to value-added tax.|rdf:PlainLiteral [0..1]
  
  
  
| epo-ord:AllowanceChargeInformation
| epo-ord:hasVATExemptionReasonDescription| 
  Explanatory text about the VAT Exemption Reason.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-ord:AllowanceChargeInformation
| epo-ful:hasAllowanceChargeReasonDescription| 
  Explanatory text about the motive of the Allowance Charge.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
| epo-ord:AllowanceChargeInformation + 
epo-ord:TaxInformation
| epo-cat:hasPercentage| 
  The factor relative to the price charged in addition.|xsd:decimal [0..1] +
  xsd:decimal [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ord:DeliveryAgreement
| epo-ord:hasGeneralDeliveryTerm| 
  Terms and conditions related to the delivery of goods.|rdf:PlainLiteral [0..1]
  
  
  
| epo-ord:DeliveryAgreement
| epo-ord:hasRequestedShippingPriority| 
  The level of importance or sequence assigned to the delivery.|rdf:PlainLiteral [0..1]
  
  
  
| epo-ord:DeliveryAgreement
| epo-ord:isPartialDeliveryAllowed| 
  An indicator to state if partial delivery is allowed or not.|xsd:boolean [0..1]
  
  
  
  
  
  
  
| epo-ord:DeliveryInformation
| epo:hasAccessURL| 
  Location where the resource can be accessed.|xsd:anyURI [0..&#42;]
  
  
  
| epo-ord:DeliveryInformation
| epo-inv:hasActualDeliveryDate| 
  The date when the Delivery occured.|xsd:dateTime [0..1]
  
  
  
| epo-ord:DeliveryInformation
| epo-ord:hasDeliveryDeadline| 
  The final accepted date for Delivery.|xsd:dateTime [0..1]
  
  
  
| epo-ord:DeliveryInformation
| epo-ord:hasDeliveryEmail| 
  The electronic address to which the products or services are to be delivered.|rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-ord:DeliveryInformation
| epo-ord:hasDownloadURL| 
  Location where the resource can be downloaded.|xsd:anyURI [0..&#42;]
  
  
  
  
  
| epo-ord:DeliveryInformation
| epo-ord:hasShippingMark| 
  A text that the buyer requests to be printed on the packing labels.|rdf:PlainLiteral [0..&#42;]
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ord:Order + 
epo-ord:OrderLine
| epo-ord:hasAccountingCost| 
  The accounting reference used by the Buyer to specify the account to which the order and the corresponding invoice are booked.|rdf:PlainLiteral [0..1] +
  rdf:PlainLiteral [0..1]
  
  
  
  
  
| epo-ord:Order
| epo-ord:hasPaymentTerm| 
  Condition and stipulation of the Payment.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
| epo-ord:OrderResponse
| epo-ord:hasResponseDescription| 
  Explanation of the response.|rdf:PlainLiteral [0..1]
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
|===

== Predicates (object properties) and definitions

[cols="20%,50%,30%", options="header"]
|===
| Predicate name | Definition | Domain, Range and Cardinality


  
  
  

  
  
  

  
  
| epo-ful:hasAllowanceChargeReason| 
  The justification for using the Allowance or the Charge.|epo-ord:AllowanceChargeInformation → at-voc-new:allowance-charge-reason [0..1]

  

  
  
  

  
  
| epo-cat:hasAmount| 
  The predetermined monetary value charged in addition to the price.|epo-ord:AllowanceChargeInformation → epo:MonetaryValue [0..1] +
epo-ord:TaxInformation → epo:MonetaryValue [0..1]

  

  
  
  

  
  
| epo-ord:hasTaxInformation| 
  Relation indicating the Tax Information.|epo-ord:AllowanceChargeInformation → epo-ord:TaxInformation [0..1]

  

  
  
| epo:isCalculatedOn| 
  The monetary amount to which the multiplier factor is applied in calculating the amount of this allowance, charge or tax.|epo-ord:AllowanceChargeInformation → epo:MonetaryValue [0..1] +
epo-ord:TaxInformation → epo:MonetaryValue [0..1]

  

  
  
| epo-inv:isSpecificToInvoiceLine| 
  Information that is particular to an Invoice Line.|epo-ord:AllowanceInformation → epo-inv:InvoiceLine [0..&#42;]

  

  
  
| epo-ord:isSpecificToOrderLine| 
  Information that is particular to one or multiple Order Lines.|epo-ord:AllowanceInformation → epo-ord:OrderLine [0..&#42;] +
epo-ord:ContractInformation → epo-ord:OrderLine [0..&#42;] +
epo-ord:DeliveryInformation → epo-ord:OrderLine [0..&#42;] +
epo-ord:OriginatorInformation → epo-ord:OrderLine [0..&#42;]

  

  
  
| epo-ord:concernsContract| 
  Relates to Contractor.|epo-ord:ContractInformation → epo:Contract [1]

  

  

  
  
  

  
  
  

  
  
  

  
  
| epo-ord:specifiesDeliveryAgreementLocation| 
  Relation indicating the Location from the Delivery Agreement.|epo-ord:DeliveryAgreement → dct:Location [0..1]

  

  
  
| epo-ord:concernsConsignee| 
  Relates to Consignee.|epo-ord:DeliveryInformation → epo-ord:Consignee [0..1]

  

  
  
  

  
  
  

  
  
  

  
  
  

  
  
| epo-ord:hasDeliveryPeriod| 
  Relation indicating the time range for the delivery.|epo-ord:DeliveryInformation → time:Interval [0..1]

  

  
  
  

  
  
| epo-ord:hasRequestedDeliveryPeriod| 
  Relation indicating the sought time range for the delivery.|epo-ord:DeliveryInformation → time:Interval [0..1]

  

  
  
  

  
  
| epo-ful:hasTrackingID| 
  Relation indicating that thedelivery has an identifier for traceability purposes.|epo-ord:DeliveryInformation → adms:Identifier [0..1]

  

  
  
| epo-ord:isSpecificToRequestForOfferLine| 
  Information that is particular to a Request For Offer Line.|epo-ord:DeliveryInformation → epo-req:RequestForOfferLine [0..&#42;]

  

  
  
| epo-ord:specifiesDeliveryAgreement| 
  Relation indicating the Delivery Agreement.|epo-ord:DeliveryInformation → epo-ord:DeliveryAgreement [0..1]

  

  
  
| epo-ord:specifiesPlaceOfDelivery| 
  Relation indicating the Location of the despatch.|epo-ord:DeliveryInformation → dct:Location [0..1]

  

  
  
| epo-ord:comprisesOrderLine| 
  Incorporates Order Line.|epo-ord:Order → epo-ord:OrderLine [0..&#42;]

  

  
  
  

  
  
| epo-ord:hasAmountDueForPayment| 
  Relation indicating the Monetary Value that has to be paid.|epo-ord:Order → epo:MonetaryValue [1]

  

  
  
  

  
  
| epo-ord:hasPrepaidAmount| 
  Relation indicating the Monetary Value that is paid in advance.|epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasRoundingAmount| 
  Relation indicating the adjustment Monetary Value applied to bring calculated total to a convenient value.|epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasSellerOrderID| 
  The identifier of the Order given by the Seller. Additional Information: This identifier is different than the identifier of the Order given by the Buyer and it is useful for internal purposes.|epo-ord:Order → adms:Identifier [0..1]

  

  
  
| epo-ord:hasTotalAllowanceAmount| 
  Relation indicating the overall Monetary Value of the Allowance.|epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasTotalChargeAmount| 
  Relation indicating the overall Monetary Value of the Charge.|epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasTotalLineAmount| 
  Relation indicating the overall Monetary Value of the Line.|epo-ord:Order → epo:MonetaryValue [1]

  

  
  
| epo-ord:hasTotalTaxExclusiveAmount| 
  Relation indicating the overall Monetary Value without Tax.|epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo-ord:hasTotalTaxInclusiveAmount| 
  Relation indicating the overall Monetary Value with Tax.|epo-ord:Order → epo:MonetaryValue [0..1]

  

  
  
| epo:hasValidityPeriod| 
  |epo-ord:Order → time:Interval [0..1]

  

  
  
| epo:refersToProject| 
  Reference to a Project.|epo-ord:Order → epo:Project [0..1]

  

  
  
| epo-ord:specifiesAllowanceInformation| 
  Relation indicating the Allowance Information.|epo-ord:Order → epo-ord:AllowanceInformation [0..&#42;]

  

  
  
| epo:specifiesBuyer| 
  Relation indicating that the instance of the concept involves the Buyer.|epo-ord:Order → epo:Buyer [1] +
epo-ord:OrderCancellation → epo:Buyer [1] +
epo-ord:OrderCancellationConfirmation → epo:Buyer [1] +
epo-ord:OrderCancellationRejection → epo:Buyer [1] +
epo-ord:OrderChangeConfirmation → epo:Buyer [1] +
epo-ord:OrderChangeRejection → epo:Buyer [1]

  

  
  
| epo-cat:specifiesChargeInformation| 
  Relation indicating the Charge Information.|epo-ord:Order → epo-cat:ChargeInformation [0..&#42;]

  

  
  
| epo-ord:specifiesContractInformation| 
  Relation indicating the Contract Information.|epo-ord:Order → epo-ord:ContractInformation [0..&#42;]

  

  
  
| epo-ord:specifiesDeliveryInformation| 
  Relation indicating the Delivery Information.|epo-ord:Order → epo-ord:DeliveryInformation [0..&#42;]

  

  
  
| epo-ful:specifiesDespatcher| 
  Relation indicating that the instance of the concept involves the Despatcher.|epo-ord:Order → epo-ful:Despatcher [0..1]

  

  
  
| epo:specifiesInvoicee| 
  Relation indicating that the instance of the concept involves the Invoicee.|epo-ord:Order → epo-ord:Invoicee [0..1]

  

  
  
| epo-ord:specifiesOriginatorInformation| 
  Relation indicating the Originator Information.|epo-ord:Order → epo-ord:OriginatorInformation [0..1]

  

  
  
| epo:specifiesSeller| 
  Relation indicating that the instance of the concept involves the Seller.|epo-ord:Order → epo-ord:Seller [1] +
epo-ord:OrderCancellation → epo-ord:Seller [1] +
epo-ord:OrderCancellationConfirmation → epo-ord:Seller [1] +
epo-ord:OrderCancellationRejection → epo-ord:Seller [1] +
epo-ord:OrderChangeConfirmation → epo-ord:Seller [1] +
epo-ord:OrderChangeRejection → epo-ord:Seller [1]

  

  
  
| epo-ord:comprisesOrderAgreementLine| 
  Incorporates Order Agreement Line.|epo-ord:OrderAgreement → epo-ord:OrderAgreementLine [0..&#42;]

  

  
  
| epo-ord:isSubmittedForOrder| 
  Relation indicating that the instance of the concept is sent for a specific Order.|epo-ord:OrderCancellation → epo-ord:Order [1] +
epo-ord:OrderChange → epo-ord:Order [1] +
epo-ord:OrderResponse → epo-ord:Order [1]

  

  
  
| epo-ord:respondsToOrderCancellation| 
  Takes action in reaction to an Order Cancellation.|epo-ord:OrderCancellationConfirmation → epo-ord:OrderCancellation [0..1] +
epo-ord:OrderCancellationRejection → epo-ord:OrderCancellation [0..1]

  

  
  
| epo-ord:comprisesOrderChangeLine| 
  Incorporates Order Change Line.|epo-ord:OrderChange → epo-ord:OrderChangeLine [0..&#42;]

  

  
  
| epo-ord:respondsToOrderChange| 
  Takes action in reaction to an Order Change.|epo-ord:OrderChangeConfirmation → epo-ord:OrderChange [1] +
epo-ord:OrderChangeRejection → epo-ord:OrderChange [1]

  

  
  
| epo-ord:hasStatus| 
  Relation indicating the status.|epo-ord:OrderChangeLine → at-voc-new:ResponseStatus [0..1] +
epo-ord:OrderResponseInformation → at-voc-new:ResponseStatus [1]

  

  
  
| epo-ord:isSubmittedForOrderLine| 
  Relation indicating that the instance of the concept is sent for a specific Order Line.|epo-ord:OrderChangeLine → epo-ord:OrderLine [1] +
epo-ord:OrderResponseLine → epo-ord:OrderLine [1]

  

  
  
| epo-cat:hasPrice| 
  Relation indicating that the instance of the concept has a Price.|epo-ord:OrderLine → epo-cat:Price [0..&#42;]

  

  
  
| epo-cat:hasQuantity| 
  Relation indicating that the instance of the concept has a Quantity.|epo-ord:OrderLine → epo:Quantity [1]

  

  
  
| epo-ord:refersToCatalogueLine| 
  Additional Information: The reference to the catalogue line is for information only, to trace the source of the information provided in the order line.|epo-ord:OrderLine → epo-cat:CatalogueLine [0..1]

  

  
  
| epo-ord:comprisesOrderResponseLine| 
  Incorporates Order Response Line.|epo-ord:OrderResponse → epo-ord:OrderResponseLine [0..&#42;]

  

  
  
  

  
  
| epo-ord:specifiesOrderResponseInformation| 
  Relation indicating the Order Response Information.|epo-ord:OrderResponse → epo-ord:OrderResponseInformation [0..&#42;]

  

  
  
| epo-ord:isSpecificToOrderResponseLine| 
  Information that is particular to an Order Response Line.|epo-ord:OrderResponseInformation → epo-ord:OrderResponseLine [0..&#42;]

  

  
  
| epo-ord:hasBackorderQuantity| 
  Relation indicating the number of Items that cannot be fulfilled immediately.|epo-ord:OrderResponseLine → epo:Quantity [0..1]

  

  
  
| epo-ord:concernsOriginator| 
  Relates to Originator.|epo-ord:OriginatorInformation → epo-ord:Originator [1]

  

  
  
| epo-ord:concernsOriginatorRequest| 
  Relates to Originator Request.|epo-ord:OriginatorInformation → epo:OriginatorRequest [0..1]

  

  
  
| epo-cat:hasTaxCategory| 
  Relation indicating the Tax Category.|epo-ord:TaxInformation → at-voc-new:tax-category [0..1]

  

  
  
| epo-cat:hasTaxScheme| 
  Relation indicating the Tax Scheme.|epo-ord:TaxInformation → at-voc-new:tax-scheme [1]

  


|===


This document is generated automatically by the link:https://github.com/OP-TED/model2owl[model2owl tool] developed in the context of link:https://interoperable-europe.ec.europa.eu/collection/eprocurement/solution/eprocurement-ontology[the eProcurement Ontology initiative].